### ISSUE TITLE
Unexpected result for max,min

### ISSUE THREAD

**Issue by zhixinwang** [torch/torch7#1001]
```lua
th> x=torch.rand(3,4)
th> x
 0.9382  0.0923  0.7964  0.5702
 0.7325  0.1997  0.7330  0.3008
 0.4828  0.4719  0.4796  0.2431
[torch.DoubleTensor of size 3x4]
th> y=x:select(2,2)
th> value,idx=torch.max(y,1)
th> value
 0.4719
[torch.DoubleTensor of size 1]
th> idx
 1
[torch.LongTensor of size 1]
```

If the tensor is not contiguous,the "max" operation cannot get a right result for "index",the same problem as "min" operation.
The problem can be found in the  torch7 distribution version [2f95bf3](https://github.com/torch/distro/commit/2f95bf3ac5c6653b12ce7e5db1c8c0564c501b99). The old version may not have this problem.

**Comment by soumith** [comment]
i'm failing to reproduce this on torch7 master.
Can you run: `luarocks install torch` and see if that fixes it?

**Comment by zhixinwang** [comment]
Thanks for fixing in time.  Install the new version has solved this problem. The problem happened in the torch distribution version [2f95bf3](https://github.com/torch/distro/tree/2f95bf3ac5c6653b12ce7e5db1c8c0564c501b99) and corresponding torch7 version [ac3751c](https://github.com/torch/torch7/tree/ac3751c63d38207b5703ba0f77001705e56a734a).
