### ISSUE TITLE
Bug when comparing byteTensor with floating point numbers

### ISSUE THREAD

**Issue by zck119** [torch/torch7#1019]
I know in general byteTensor should be converted to doubleTensor before comparing with a floating point number, but this is really weird...

```Lua
torch.zeros(1):byte():gt(0.5)  -- should be 0, and gives 0
torch.zeros(1):byte():lt(0.5)  -- should be 1, but gives 0
torch.zeros(1):byte():ge(0.5)  -- should be 0, but gives 1
torch.zeros(1):byte():le(0.5)  -- should be 1, and gives 1
```

**Comment by iamalbert** [comment]
this is (technically) not a bug.  ByteTensor operators only accept an `int`, so `0.5` is converted to `0` before comparison
