### ISSUE TITLE
fixed random seed but different results on different versions of gpus.

### ISSUE THREAD

**Issue by haanvid** [torch/torch7#1033]
Hello,

 I fixed random seed by the code written below but it seems the results are different when the code is run on different versions of GPUs (Titan X, Titan Black, 980ti). Is this inevitable? Thank you in advance.

function make_deterministic(seed)
  torch.manualSeed(seed)
  cutorch.manualSeed(seed)
  math.randomseed(seed)
end

**Comment by albanD** [comment]
Hi,

Unfortunately yes, some cudnn kernels have non deterministic behaviors.
Especially the reduce operations can happen in different order and due to floating point arithmetic, this will give you different results (that will be amplified during training and lead to different results).

**Comment by haanvid** [comment]
@albanD  thanks alot!
