### ISSUE TITLE
AMD Ryzen poor performance

### ISSUE THREAD

**Issue by viktorheli** [torch/torch7#1034]
I upgraded my system to AMD Ryzen 1800x and 64GGb memory and get very poor performance with torch then using neural net on CPU. 

For example:
picture forward throgh net:
AMD Ryzen: 
Time to processing:6632ms

 Intel Pentium Dual-Core G4500:
Time to processing:433ms

System in both cases Ubuntu 16.04
Installing Torch on instruction from torch.ch

My Luascript:

--[[
This script loads the neural network into memory. Listens to the tcp port
and waits for the image file to load. Next, the image passes through the neural network,
which gives a good or bad response for image.
--]]

require 'nn'
require 'image'

torch.setdefaulttensortype('torch.FloatTensor')

--images dimensions. Must match what is specified in the neural network
imgheight = 164
imgwidth = 160

--categories
classes = {'bad', 'good'}

--round function

function round(num, numDecimalPlaces)
  return tonumber(string.format("%." .. (numDecimalPlaces or 0) .. "f", num))
end

--enable waffle module
app = require 'waffle'

--loading neuralnetwork in memory
                net = torch.load("clear-fotograf-1000cpu.dat")

--define simple web form to browse and upload file

        app.get('/', function(req, res)
           res.send(html { body { form {
                method = 'POST',
                enctype = 'multipart/form-data',
                p { input {
                type = 'file',
                name = 'file'
                }},
                p { input {
                type = 'submit',
                'Upload'
                }}
                }}})
        end)

--Processing request from client

        app.post('/', function(req, res)

--upload image
        time = sys.clock()
                img = nill
                img = req.form.file:toImage()

-- if file not load or incorrect file format
                if img == nill or img:size(1) ~=3 then
                        print("kosyak!!!")
                        res.send("Incorrect file type.")
                else
--load image, scale it and forwarding througth neural net
                load = img
                imgscaled = image.scale(load, imgwidth, imgheight)
                imgdata = torch.Tensor(imgscaled,3, imgwidth, imgheight)

                predict = net:forward(imgdata)

                predicted = predict:exp()*100

--define temporary lua table for predicted data
mytable = ""

--Do the matching category and predicted probability and concatenate to table. For example bad: 40 good: 60.

                for i=1,predicted:size(1) do

                mytable = mytable..classes[i]..": "..round(predicted[i],3).."\n "
                end

--send data to client
        res.send(mytable)

print (mytable)
                end
                 time = sys.clock() - time
                print("Time to processing:"..round(time*1000).."ms")
end)

--permanent listening tcp port for connections
app.listen({host='0.0.0.0', port=8787})

_____________________

Neural network was created and training on GPU and converted to work on CPU. Training and converting I did in my old system with Intel CPU Core I7 860. 
In system monitoring (htop) I see that my script on Ryzen CPU workd in single thread. In system with Intel CPU multithread used normally. 

Torch on Ryzen system see 16 threads:
th> torch.getnumthreads()
16

Maybe problem in nn package? Or in Torch?

**Comment by pavanky** [comment]
It could be that you are using different BLAS libraries on different machines ? Can you run ldd on libTHNN.so on both systems ?

**Comment by viktorheli** [comment]
Ryzen System:
 ldd /home/vik/torch/extra/nn/build/lib/THNN/libTHNN.so
        linux-vdso.so.1 =>  (0x00007ffea36ea000)
        libTH.so.0 => /home/vik/torch/install/lib/libTH.so.0 (0x00007f989e503000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f989e1d4000)
        libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f989dfb2000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f989dd95000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f989d9cb000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f989d7c3000)
        /lib64/ld-linux-x86-64.so.2 (0x000055d5983bc000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f989d5be000)


Pentium Dual-Core G4500 system:

 ldd /home/vik/torch/extra/nn/build/lib/THNN/libTHNN.so
        linux-vdso.so.1 =>  (0x00007ffc9f3d2000)
        libTH.so.0 => /home/vik/torch/install/lib/libTH.so.0 (0x00007f0158583000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f015825f000)
        libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f015803d000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0157e20000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0157a56000)
        libblas.so.3 => /usr/lib/libblas.so.3 (0x00007f0157818000)
        liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007f0157034000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0156e2b000)
        /lib64/ld-linux-x86-64.so.2 (0x000055e78b4a3000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0156c27000)
        libatlas.so.3 => /usr/lib/libatlas.so.3 (0x00007f0156689000)
        libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007f015635d000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0156147000)
        libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f0155f07000)

**Comment by viktorheli** [comment]
Thanks for the help.
Perhaps, when I compiled the torch, I did not have the BLAS installed in the Ryzen system. I installed BLAS, recompiled the torch, and it all worked.  Perhaps when compiling, need to somehow warn that it will work slowly without BLAS. :)

picture forward throgh net:
AMD Ryzen:
Time to processing:201ms
