### ISSUE TITLE
Installation Problem: Missing dependency 

### ISSUE THREAD

**Issue by omair-kg** [torch/torch7#1045]
I'm getting the following message while trying to install torch 

```
Scanning dependencies of target sys
[100%] Building C object CMakeFiles/sys.dir/sys.c.o
Linking C shared module libsys.so
[100%] Built target sys
cd build && make install
[100%] Built target sys
Install the project...
-- Install configuration: "Release"
-- Installing: /home/torch/install/lib/luarocks/rocks/sys/1.1-0/lib/libsys.so
-- Set runtime path of "/home/torch/install/lib/luarocks/rocks/sys/1.1-0/lib/libsys.so" to "$ORIGIN/../lib:/home/torch/install/lib"
-- Installing: /home/torch/install/lib/luarocks/rocks/sys/1.1-0/lua/sys/init.lua
-- Installing: /home/torch/install/lib/luarocks/rocks/sys/1.1-0/lua/sys/colors.lua
-- Installing: /home/torch/install/lib/luarocks/rocks/sys/1.1-0/lua/sys/fpath.lua
Updating manifest for /home/torch/install/lib/luarocks/rocks
sys 1.1-0 is now built and installed in /home/torch/install/ (license: BSD)

Updating manifest for /home/torch/install/lib/luarocks/rocks
xlua 1.0-0 is now built and installed in /home/torch/install/ (license: BSD)


Missing dependencies for nn:
moses >= 1.0

Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/torch/rocks/master - Failed downloading https://raw.githubusercontent.com/torch/rocks/master/manifest - /home/goh4hi/.cache/luarocks/https___raw.githubusercontent.com_torch_rocks_master/manifest
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master - Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/manifest - /home/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moonrocks-mirror_master/manifest

Error: Could not satisfy dependency: moses >= 1.0
```

I tried following the advice given [here](https://github.com/torch/nn/issues/1219) but still get the same message (missing dependency for nn).

Any idea what i should try next? Thanks in anticipation.

**Comment by shriyashchougule** [comment]
I had the same issue. And I followed the same advice as you did, given [here](https://github.com/torch/nn/issues/1219). I used following commands to install moses after downloading it from [Moses](https://github.com/Yonaba/Moses).
`extract to torch folder`
`cd Moses-master`
  `luarocks make rockspec/moses-1.6.0-1.rockspec`

After that I went with ./install.sh for torch.

**Comment by hemanthkatari97** [comment]
I am facing the same issue. I am behind a proxy and figured out the problem is due to proxy. I tried above commands and install it. On completion gives same problem again. can anyone help in configuring proxy settings of github so it fetches raw.githubusercontent ?

**Comment by Naruto-Sasuke** [comment]
@hemanthkatari97 Have u tried the specific way of install moses?   `luarocks install --tree /home/xxx/torch/install rockspec/moses-1.6.1-1.rockspec`

**Comment by hemanthkatari97** [comment]
Getting the following error:
luarocks install --tree=/home/edx/torch/install rockspec/moses-1.6.1-1.rockspec
Using rockspec/moses-1.6.1-1.rockspec... switching to 'build' mode

Error: Error fetching file: Failed downloading https://github.com/Yonaba/Moses/archive/Moses-1.6.1-1.tar.gz

Thanks for reply.

**Comment by Naruto-Sasuke** [comment]
@hemanthkatari97 I don't know why you just download it from a browser? And extract it, get into the folder, and install it `luarocks make --tree /home/xxx/torch/install rockspec/moses-1.6.1-1.rockspec`, I just made a typo, it should be `make` instead of `install`

**Comment by karthik-govindappa** [comment]
Since I was installing torch on my machine for first time, I had no chance to download and install `moses` via `luarocks make rockspec/*`. The following method worked for me.
1. Comment out lines having `nn`, `nngraph` and `cunn` in `install.sh`. Doing so does not install the aforementioned packages.
2. Running `./install.sh` should install torch without any errors
3. Now `luarocks` will be available. Download [moses](https://github.com/Yonaba/Moses) and install it via `luarocks make rockspec/*`.
4. Go back to `install.sh`, uncomment the lines and run `./install.sh`. All nn packages should be installed now without any errors.

**Comment by Marauderer97** [comment]
I have tried all the solutions mentioned above, each time I get a message saying 
`moses 1.6.1-1 is now built and installed in /home/torch (license: MIT <http://www.opensource.org/licenses/mit-license.php>)`
But on running ./install.sh in `/home/torch` I get the exact same error. What is going wrong?

**Comment by hemanthkatari97** [comment]
@Marauderer97 It is due to proxy. Are you working behind a proxy?

**Comment by kamranthomas** [comment]
sudo luarocks make *.rockspec try that

**Comment by hhwxxx** [comment]
@hemanthkatari97 hello, I am facing the same issue. How did you configure the proxy settings to slove this problem? Thanks!

**Comment by hemanthkatari97** [comment]
Ya you can check the detailed configuration proxy settings required in
installation steps in the link provided


https://github.com/hemanthkatari97/EproctorX/blob/master/README.md

**Comment by HarshGrandeur** [comment]
I was facing the same issue.
I followed the steps mentioned by **shriyashchougule**. But was still getting the dependency issue with moses.
Then I ran the ./install.sh with sudo and could complete the installation.

**Comment by yonihei** [comment]
by using karthik-govindappa's suggestions i managed to install ./install.sh after removing grahp, cunn, nn.

then by using:
luarocks make --tree /home/xxx/torch/install moses-package

finally ./install.sh without comments ran well.

do NOT use sudo anywhere here. it only caused me troubles.
