### ISSUE TITLE
torch.max error: bad argument #3 to '?'

### ISSUE THREAD

**Issue by wudapeng268** [torch/torch7#1048]
When I run my code, I got the error as follow:
ps: In my code CRF.lua:79 is ` self.alpha[i], self.beta[i] = torch.max(self.tempMat, 2)`
train_crf.lua:150 is `local pred = linearCRF:forward(seqVec)`
In train_crf.lua `local linearCRF = CRF(opt.numClass, opt.maxSeqLen, loader.batchSize)`
But when I open a `th`, `require 'cutorch'` `torch.max(x,2)` It is all right.
I also can see that `self.tempMat` in CRF.lua is a torch.CudaTensor of size 128x2x2
Thanks everyone who can give me some advice!

/home/wup/torch/install/bin/luajit: bad argument #3 to '?' (torch.*Tensor expected, got userdata)
stack traceback:
	[C]: at 0x7fd41b0529a0
	[C]: in function '__newindex'
	/home/wup/CFO/src/model/CRF.lua:79: in function 'forward'
	train_crf.lua:150: in main chunk
	[C]: in function 'dofile'
	.../wup/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670

**Comment by Naruto-Sasuke** [comment]
I wonder that if your `self.alpha and self.beta`are just tensors？ If so, transfer them to cudaTensor, and it will work, I think.

**Comment by wudapeng268** [comment]
Agree Naruto-Sasuke, Although not this problem, but you give a good idea, now I solve this problem half, could you tell me how to transfer a cudaLongTensor to cudaTensor? because our `self.beta = torch.zeros(1,2,3)` is a cudaTensor, but after max() the second variable is cudaLongTensor. thx.

**Comment by Naruto-Sasuke** [comment]
just add `:cuda()` is ok.  
```lua
c,d = torch.max(a,2)
d:cuda() -- It can change CudaLongTensor to CudaTensor
```

**Comment by wudapeng268** [comment]
It's ok, thanks!
