### ISSUE TITLE
load ***.t7 model , i got some error

### ISSUE THREAD

**Issue by visonpon** [torch/torch7#1058]
```
require 'nn'
require 'cunn'
require 'torch'
require 'cutorch'
require 'cudnn'

th> m =torch.load('***.t7')

```

then the error like this:

torch_install/torch/install****/Fiule.lua  unknow torch class <nn.gModule> stack traceback:
[C]: in function 'error'.
anyone know why? thanks~

**Comment by albanD** [comment]
It is because your model uses 'nngraph' but you did not require it before loading.

**Comment by visonpon** [comment]
thanks, @albanD it works~

**Comment by salihkaragoz** [comment]
@albanD @visonpon so well what is the correct way load the model? 
Which parameter or settings I should change?
Thanks in advance...
