### ISSUE TITLE
Manually compilation failed on Red-hat

### ISSUE THREAD

**Issue by jakezhaojb** [torch/torch7#106]
I want to install Torch locally on REDHAT since I don't have sudo privilege:

```
cd torch7
mkdir build
cmake ..
make
```

I got the following errors:

```
/torch7/lib/luaT/luaT.c: In function ‘luaT_lua_newmetatable’:
/torch7/lib/luaT/luaT.c:454: error: ‘LUA_GLOBALSINDEX’ undeclared (first use in this function)
/torch7/lib/luaT/luaT.c:454: error: (Each undeclared identifier is reported only once
/torch7/lib/luaT/luaT.c:454: error: for each function it appears in.)
make[2]: *** [lib/luaT/CMakeFiles/luaT.dir/luaT.c.o] Error 1
make[1]: *** [lib/luaT/CMakeFiles/luaT.dir/all] Error 2
make: *** [all] Error 2
```

I thereby try:

```
ack LUA_GLOBALSINDEX
```

got:

```
init.c
59:  lua_setfield(L, LUA_GLOBALSINDEX, "torch");

lib/luaT/luaT.c
454:    lua_getfield(L, LUA_GLOBALSINDEX, module_name);
456:    lua_pushvalue(L, LUA_GLOBALSINDEX);

utils.c
116:  lua_getfield(L, LUA_GLOBALSINDEX, "torch");
```

I am just wondering where LUA_GLOBALSINDEX is declared... Any help is appreciated in advance!!

**Comment by viral612** [comment]
I am trying to install Torch on redhat.
i got from https://github.com/torch/distro 
cd build
cmake ..
I get the following issues
CMake Error at exe/CMakeLists.txt:1 (ADD_SUBDIRECTORY):
  The source directory

    /bb/adsk/users/vgupta1/torch/exe/luajit-rocks

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
