### ISSUE TITLE
CharStorage() not reading file.

### ISSUE THREAD

**Issue by Minilei89** [torch/torch7#1064]
lhuang@localhost annotations]$ echo "Hello World" > hello.txt
[lhuang@localhost annotations]$ lua
Lua 5.2.3  Copyright (C) 1994-2013 Lua.org, PUC-Rio
\> require 'torch'
\> x = torch.CharStorage('hello.txt')
\> = x
[torch.CharStorage of size 0]

Not sure what the problem is here but CharStorage is not loading the files correctly. If someone can confirm or point out the cause that would be really helpful.

**Comment by soumith** [comment]
this bug was introduced in a recent commit while fixing another bug. I'm working on fixing it.

**Comment by Minilei89** [comment]
Thanks for the hard work! Best of luck fixing it. In the meantime I can use an older version.

**Comment by soumith** [comment]
last working commit is https://github.com/torch/torch7/commit/2186e414ad8fc4dfc9f2ed090c0bf8a0e1946e62
Thanks for your patience.

**Comment by soumith** [comment]
fixed on master via https://github.com/torch/torch7/commit/89ede3ba90c906a8ec6b9a0f4bef188ba5bb2fd8
