### ISSUE TITLE
Missing Dependency while installing torch 

### ISSUE THREAD

**Issue by Priyansh2** [torch/torch7#1076]
After running this command :- ./install-deps , it shows me this error :- 

Get:1 http://security.ubuntu.com/ubuntu zesty-security InRelease [89.2 kB]
Hit:2 http://ppa.launchpad.net/wine/wine-builds/ubuntu zesty InRelease          
Hit:3 http://archive.ubuntu.com/ubuntu zesty InRelease                               
Get:4 http://archive.ubuntu.com/ubuntu zesty-updates InRelease [89.2 kB]
Hit:5 https://dl.winehq.org/wine-builds/ubuntu zesty InRelease
Fetched 178 kB in 2s (65.3 kB/s)                               
Reading package lists... Done
Updated successfully.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-software-properties is already the newest version (0.96.24.13).
The following packages were automatically installed and are no longer required:
  linux-headers-4.10.0-28 linux-headers-4.10.0-28-generic linux-headers-4.10.0-30 linux-headers-4.10.0-30-generic linux-headers-4.10.0-32
  linux-headers-4.10.0-32-generic linux-image-4.10.0-28-generic linux-image-4.10.0-30-generic linux-image-4.10.0-32-generic
  linux-image-extra-4.10.0-28-generic linux-image-extra-4.10.0-30-generic linux-image-extra-4.10.0-32-generic
  linux-signed-image-4.10.0-28-generic linux-signed-image-4.10.0-30-generic linux-signed-image-4.10.0-32-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
==> Found Ubuntu version 17.xx
Reading package lists... Done
Building dependency tree       
Reading state information... Done
software-properties-common is already the newest version (0.96.24.13).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgraphicsmagick1-dev : Depends: libtiff-dev
                          Depends: libjbig-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Any idea what to do ?

**Comment by tastyminerals** [comment]
```
sudo apt-get update
sudo apt-get install libtiff5-dev libtiff5 libjbig-dev
```

**Comment by Priyansh2** [comment]
i have tried what you have said @tastyminerals  but it shows this error :- 

Reading package lists... Done
Building dependency tree       
Reading state information... Done
libtiff5 is already the newest version (4.0.7-5).
libtiff5 set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libjbig-dev : Depends: libjbig0 (= 2.1-3.1) but 2.1-3.1+deb.sury.org~xenial+1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by tastyminerals** [comment]
Well, the answer was somewhat given to you already:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
``` 
This is not a torch issue but your specific Linux distribution. What apt repositories are you using? Have you modified your apt sources? Why is does apt attempt to install **xenial** package but your distro is **zesty**? Torch installs on Ubuntu without any problems unless your're using unstable or testing release branch.

**Comment by Priyansh2** [comment]
@tastyminerals thank you for your support . Yes , I'm using the latest release of Ubuntu (this is of course not the stable one) .

**Comment by 314rated** [comment]
Hi @Priyansh2 ,
Could you please tell how was this resolved?

Thanks

**Comment by Priyansh2** [comment]
@314rated previously i had unstable version of ubuntu (latest) , then i reinstall ubuntu (16.04) and it works.

**Comment by 314rated** [comment]
I am on Ubuntu 16.04.3, yet getting dependency errors like you did.
The error on running 'install-deps' is:
libgraphicsmagick1-dev : Depends: libwmf-dev but it is not going to be installed
                          Depends: libfreetype6-dev but it is not going to be installed
                          Depends: libtiff-dev
                          Depends: zlib1g-dev but it is not going to be installed or
                                   libz-dev
                          Depends: libpng-dev
E: Unable to correct problems, you have held broken packages
I tried 'sudo apt --fix-broken install' and 'sudo apt autoremove', and consulted online resources. However, it isn't getting resolved. 
Could you shed some light on this?
Thanks
