### ISSUE TITLE
Installation failure when running './install.sh'

### ISSUE THREAD

**Issue by cole106** [torch/torch7#1086]
The following are the error messages received after running './install.sh'

```
1 error detected in the compilation of "/tmp/tmpxft_000005a7_00000000-6_THCTensorMathPairwise.cpp1.ii".
CMake Error at THC_generated_THCTensorMathPairwise.cu.o.cmake:267 (message):
  Error generating file
  /home/vipaacc/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathPairwise.cu.o

lib/THC/CMakeFiles/THC.dir/build.make:4216: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMathPairwise.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMathPairwise.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/vipaacc/torch/extra/cutorch/lib/THC/generic/THCTensorMath.cu(393): error: more than one operator "==" matches these operands:
            function "operator==(const __half &, const __half &)"
            function "operator==(half, half)"
            operand types are: half == half

/home/vipaacc/torch/extra/cutorch/lib/THC/generic/THCTensorMath.cu(414): error: more than one operator "==" matches these operands:
            function "operator==(const __half &, const __half &)"
            function "operator==(half, half)"
            operand types are: half == half

2 errors detected in the compilation of "/tmp/tmpxft_00000605_00000000-6_THCTensorMath.cpp1.ii".
CMake Error at THC_generated_THCTensorMath.cu.o.cmake:267 (message):
  Error generating file
  /home/vipaacc/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMath.cu.o


lib/THC/CMakeFiles/THC.dir/build.make:2735: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o] Error 1
CMakeFiles/Makefile2:172: recipe for target 'lib/THC/CMakeFiles/THC.dir/all' failed
make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed building.
```

**Comment by sdlmw** [comment]
i have a same error

**Comment by zhouqilin1993** [comment]
Same error, Ubuntu 16.04, cuda 9.0

**Comment by soveraign** [comment]
Same problem, further up the compile log I see:
`
/home/brian/torch/extra/cutorch/lib/THC/generic/THCTensorMathPairwise.cu(66): error: more than one operator "!=" matches these operands:
            function "operator!=(const __half &, const __half &)"
            function "operator!=(half, half)"
            operand types are: half != half

1 error detected in the compilation of "/tmp/tmpxft_000078f9_00000000-6_THCTensorMathPairwise.cpp1.ii".
CMake Error at THC_generated_THCTensorMathPairwise.cu.o.cmake:267 (message):
  Error generating file
  /home/brian/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathPairwise.cu.o


lib/THC/CMakeFiles/THC.dir/build.make:140: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMathPairwise.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMathPairwise.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/brian/torch/extra/cutorch/lib/THC/generic/THCTensorMath.cu(393): error: more than one operator "==" matches these operands:
            function "operator==(const __half &, const __half &)"
            function "operator==(half, half)"
            operand types are: half == half

/home/brian/torch/extra/cutorch/lib/THC/generic/THCTensorMath.cu(414): error: more than one operator "==" matches these operands:
            function "operator==(const __half &, const __half &)"
            function "operator==(half, half)"
            operand types are: half == half

2 errors detected in the compilation of "/tmp/tmpxft_00007911_00000000-6_THCTensorMath.cpp1.ii".
CMake Error at THC_generated_THCTensorMath.cu.o.cmake:267 (message):
  Error generating file
  /home/brian/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMath.cu.o

lib/THC/CMakeFiles/THC.dir/build.make:112: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o' failed
make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorMath.cu.o] Error 1
CMakeFiles/Makefile2:172: recipe for target 'lib/THC/CMakeFiles/THC.dir/all' failed
make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

`

**Comment by tastyminerals** [comment]
This has been reported and fixed in https://github.com/torch/cutorch/issues/797

**Comment by hzxie** [comment]
@tastyminerals
Still not working in CUDA 9.1

**Comment by tastyminerals** [comment]
Are you sure, because I have CUDA 9.1 installed and working with Torch :)

**Comment by hzxie** [comment]
@tastyminerals 
I've solved this problem.
Because I used `sudo` but `export` is for the current user.

**Comment by hzxie** [comment]
@tastyminerals 
Just use `su` and it will solve this problem.

**Comment by Harry-675** [comment]
Met the same question,not work by using method above,any other suggestions?

**Comment by adam-dziedzic** [comment]
This worked for me:
```
sudo su
export TORCH_NVCC_FLAGS="-D__CUDA_NO_HALF_OPERATORS__"
bash install-deps
yes | bash ./install.sh
```

**Comment by Spandan-Madan** [comment]
The solution given by @adam-dziedzic worked for me! Thanks!

**Comment by mherrera-dsci** [comment]
The solution given by @adam-dziedzic worked for me too! Only a few modifications on ~/torch/install/bin/torch-activate and chown for some files in ~/torch/install/bin. Thanks!

**Comment by btomtom5** [comment]
Be careful with the solution that @adam-dziedzic provided because installing torch under `sudo su` changes the installation path of torch which may break your luarocks package manager.

**Comment by frahman5** [comment]
@mherrera-dsci Did the chown you did on ~/torch/install/bin and the other modifications you did allow you to use luarocks from a non super-user? I'm finding that I can only use luarocks in super-user mode.

**Comment by ShijianXu** [comment]
> The solution given by @adam-dziedzic worked for me too! Only a few modifications on ~/torch/install/bin/torch-activate and chown for some files in ~/torch/install/bin. Thanks!

Hi, could you please tell me how to modify? I found that after using sudo su to install torch, the torch can only be used in su.

**Comment by wu-yy** [comment]
> This worked for me:
> 
> ```
> sudo su
> export TORCH_NVCC_FLAGS="-D__CUDA_NO_HALF_OPERATORS__"
> bash install-deps
> yes | bash ./install.sh
> ```

year, this is also worked for me! I solved this problem.

**Comment by dinhphuong98** [comment]
> This worked for me:
> 
> ```
> sudo su
> export TORCH_NVCC_FLAGS="-D__CUDA_NO_HALF_OPERATORS__"
> bash install-deps
> yes | bash ./install.sh
> ```

thanks, worked for me

**Comment by BurkeyLai** [comment]
@adam-dziedzic 's solution works for me, however I don't use the command `sudo su`. Many thxs!

**Comment by Ujang24** [comment]
> Be careful with the solution that @adam-dziedzic provided because installing torch under `sudo su` changes the installation path of torch which may break your luarocks package manager.

Yes, mine is broken. How to solve this?

**Comment by Lilidamowang** [comment]
> 

Thanks!!! it works for me!!
