### ISSUE TITLE
Meaning of comment.

### ISSUE THREAD

**Issue by singam-sanjay** [torch/torch7#1099]
What does the comment at the end of this line mean ?
https://github.com/torch/torch7/blob/3864f3782a74715e35d98176f9014a74524a868a/lib/TH/THTensorApply.h#L201

**Comment by albanD** [comment]
It means: "0 and not TENSOR##_dim !".
This is an outdated comment, because in the original code, `TENSOR##_i` was initialized in this loop and was initialized to `0`. You can see it [here](https://github.com/torch/torch7/blame/053065ba239e3421d1b2cbec55e3f177a21d6829/lib/TH/THTensorApply.h#L394)

**Comment by clement-masson** [comment]
This is legacy French comment, ^^

**Comment by singam-sanjay** [comment]
Thanks for the clarification !!
