### ISSUE TITLE
PReLU_backward and PReLU_forward test error

### ISSUE THREAD

**Issue by chenbohua3** [torch/torch7#1104]
when i ran test.sh in torch7 it happened that "Completed 2103 asserts in 190 tests with 0 failures and 2 errors". the specific information is listed below(about PReLU function):

Function call failed
/home/face/torch/install/share/lua/5.1/nn/THNN.lua:110: Wrong number of input planes. Expected 8 but got 7. at /tmp/luarocks_nn-scm-1-3820/nn/lib/THNN/generic/PReLU.c:29
stack traceback:
	[C]: in function 'v'
	/home/face/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'PReLU_updateOutput'
	/home/face/torch/install/share/lua/5.1/nn/PReLU.lua:12: in function 'forward'
	/home/face/torch/install/share/lua/5.1/cunn/test.lua:5545: in function 'v'
	/home/face/torch/install/share/lua/5.1/cunn/test.lua:6670: in function </home/face/torch/install/share/lua/5.1/cunn/test.lua:6668>
	[C]: in function 'xpcall'
	/home/face/torch/install/share/lua/5.1/torch/Tester.lua:477: in function '_pcall'
	/home/face/torch/install/share/lua/5.1/torch/Tester.lua:436: in function '_run'
	/home/face/torch/install/share/lua/5.1/torch/Tester.lua:355: in function 'run'
	/home/face/torch/install/share/lua/5.1/cunn/test.lua:6691: in function 'testcuda'
	[string "nn.testcuda()"]:1: in main chunk
	[C]: in function 'pcall'
	...face/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:136: in main chunk
	[C]: at 0x00405d50

--------------------------------------------------------------------------------
PReLU_forward
 Function call failed
/home/face/torch/install/share/lua/5.1/nn/THNN.lua:110: Wrong number of input planes. Expected 8 but got 81. at /tmp/luarocks_nn-scm-1-3820/nn/lib/THNN/generic/PReLU.c:29
stack traceback:
	[C]: in function 'v'
	/home/face/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'PReLU_updateOutput'
	/home/face/torch/install/share/lua/5.1/nn/PReLU.lua:12: in function 'forward'
	/home/face/torch/install/share/lua/5.1/cunn/test.lua:5519: in function 'v'
	/home/face/torch/install/share/lua/5.1/cunn/test.lua:6670: in function </home/face/torch/install/share/lua/5.1/cunn/test.lua:6668>
	[C]: in function 'xpcall'
	/home/face/torch/install/share/lua/5.1/torch/Tester.lua:477: in function '_pcall'
	/home/face/torch/install/share/lua/5.1/torch/Tester.lua:436: in function '_run'
	/home/face/torch/install/share/lua/5.1/torch/Tester.lua:355: in function 'run'
	/home/face/torch/install/share/lua/5.1/cunn/test.lua:6691: in function 'testcuda'
	[string "nn.testcuda()"]:1: in main chunk
	[C]: in function 'pcall'
	...face/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:136: in main chunk
	[C]: at 0x00405d50

how can i solve this problem?  Thanks for ur patience.

**Comment by Naruto-Sasuke** [comment]
Just ignore it. It does not matter much

**Comment by junjun16** [comment]
Same problems. 
Hope it doesn't hurt.

**Comment by AleximusOrloff** [comment]
problem still occurs ubuntu 16.04

**Comment by screnary** [comment]
problem still occurs on Ubuntu 18.04
