### ISSUE TITLE
Cannot read .bin file with torch.TYPEStorage()

### ISSUE THREAD

**Issue by pierrelzw** [torch/torch7#1112]
Hi,

I'm new to torch and git. I installed [torch7](http://torch.ch/docs/getting-started.html#_) on Ubuntu14.04. And I come across the same problem as [#1071](https://github.com/torch/torch7/issues/1071).
Since i don't know how to install older version of torch. I followed changes of [89ede3b](https://github.com/torch/torch7/commit/89ede3ba90c906a8ec6b9a0f4bef188ba5bb2fd8) indicated in   [#1071](https://github.com/torch/torch7/issues/1071)., but i always failed to load .bin file([myPerm.bin.zip](https://github.com/torch/torch7/files/1550779/myPerm.bin.zip)) using torch.FloatStorage(), as shown below. 
`th> torch.FloatStorage("myPerm.bin")

[torch.FloatStorage of size 0]
`

**Comment by pierrelzw** [comment]
after reinstall the lastest torch, the problem solved

**Comment by Hancminnah** [comment]
Hi there, i also faced the same problem when i tried to read .bin files with torch.FloatStorage("data.bin"). What do you mean by reinstalling the latest torch? I have just installed torch following through getting started page "http://torch.ch/docs/getting-started.html" with Lua 5.2. Any help to solve this problem would be appreciated.
