### ISSUE TITLE
Converting a torch7 model to a binary view for C/C++/C# programs

### ISSUE THREAD

**Issue by PABCSoft** [torch/torch7#1144]
I would like to rewrite [this](https://github.com/zeruniverse/neural-colorization) neural network to pure C++ (or C#) without using GPU and deep learning packages (torch, caffe, TensorFlow, keras), for the simplest and most understandable code (in fact, pure mathematics). But I've run into a few problems. One of them is reading a pre-learned model on torch7. Could you convert the data of this model to binary form or JSON? At the same time, I have no experience with Linux. Of course I need this solely for educational purposes and personal use.

**Comment by greed2411** [comment]
this from pytorch to C++ using [ATen](https://github.com/zdevito/ATen), but i guess this is the only close solution i could find:

* [custom C++ and CUDA extnesions](https://pytorch.org/tutorials/advanced/cpp_extension.html)
