### ISSUE TITLE
Error occurred when I install torch with the env of  nvidia-docker run tensorflow image

### ISSUE THREAD

**Issue by whytin** [torch/torch7#1154]
I use nvidia-docker to run tensorflow/tensorflow:latest-gpu image. And then I want to install torch. Some problems happened. Env: Ubuntu16.04、Cuda 9.0、 Cudnn 7.0.5、 GPU:1080ti
How can I figure out this? Thanks!

**Error flew out in process:**

Found CUDA on your machine. Installing CUDA packages
Warning: unmatched variable LUALIB

jopts=$(getconf _NPROCESSORS_CONF)

echo "Building on $jopts cores"
cmake -E make_directory build && cd build && cmake .. -DLUALIB= -DLUA_INCDIR=/distro/install/include -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS} -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/distro/install/bin/.." -DCMAKE_INSTALL_PREFIX="/distro/install/lib/luarocks/rocks/cutorch/scm-1" && make -j$jopts install

Building on 12 cores
-- Found Torch7 in /distro/install
-- Removing -DNDEBUG from compile flags
-- TH_LIBRARIES: TH
-- MAGMA not found. Compiling without MAGMA support
-- Autodetected CUDA architecture(s): 6.1
-- got cuda version 9.0
-- Found CUDA with FP16 support, compiling with torch.CudaHalfTensor
-- CUDA_NVCC_FLAGS: -gencode;arch=compute_61,code=sm_61;-DCUDA_HAS_FP16=1
-- THC_SO_VERSION: 0
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_LIBRARY (ADVANCED)
    linked by target "THC" in directory /distro/extra/cutorch/lib/THC
CUDA_cublas_device_LIBRARY (ADVANCED)
    linked by target "THC" in directory /distro/extra/cutorch/lib/THC
CUDA_curand_LIBRARY (ADVANCED)
    linked by target "THC" in directory /distro/extra/cutorch/lib/THC
CUDA_cusparse_LIBRARY (ADVANCED)
    linked by target "THC" in directory /distro/extra/cutorch/lib/THC

-- Configuring incomplete, errors occurred!
See also "/distro/extra/cutorch/build/CMakeFiles/CMakeOutput.log".
See also "/distro/extra/cutorch/build/CMakeFiles/CMakeError.log".

Error: Build error: Failed building.

**And Cat with CMakeError.log:**

Performing C SOURCE FILE Test HAS_LUAL_SETFUNCS failed with the following output:
Change Dir: /distro/extra/cutorch/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_74126/fast"
/usr/bin/make -f CMakeFiles/cmTC_74126.dir/build.make CMakeFiles/cmTC_74126.dir/build
make[1]: Entering directory '/distro/extra/cutorch/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_74126.dir/src.c.o
/usr/bin/cc   -I/distro/install/include  -std=c99 -Werror=implicit-function-declaration  -DHAS_LUAL_SETFUNCS   -o CMakeFiles/cmTC_74126.dir/src.c.o   -c /distro/extra/cutorch/build/CMakeFiles/CMakeTmp/src.c
/distro/extra/cutorch/build/CMakeFiles/CMakeTmp/src.c: In function 'main':
/distro/extra/cutorch/build/CMakeFiles/CMakeTmp/src.c:5:20: error: 'luaL_setfuncs' undeclared (first use in this function)
   long i = sizeof(&luaL_setfuncs);
                    ^
/distro/extra/cutorch/build/CMakeFiles/CMakeTmp/src.c:5:20: note: each undeclared identifier is reported only once for each function it appears in
CMakeFiles/cmTC_74126.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_74126.dir/src.c.o' failed
make[1]: *** [CMakeFiles/cmTC_74126.dir/src.c.o] Error 1
make[1]: Leaving directory '/distro/extra/cutorch/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_74126/fast' failed
make: *** [cmTC_74126/fast] Error 2

Source file was:

#include <lauxlib.h>
int main()
{
  long i = sizeof(&luaL_setfuncs);
  return 0;
}

**Comment by greed2411** [comment]
@whytinI found this nvidia-docker image to be useful, [ufoym/deepo](https://github.com/ufoym/deepo). Let me know if it works out.

**Comment by whytin** [comment]
@greed2411 It did work for me, Thank you!
