### ISSUE TITLE
Error message when I open Terminal after removing Torch

### ISSUE THREAD

**Issue by zosob** [torch/torch7#1160]
Hello,

I am unsure if this is the correct place for this issue, but after I remove Torch from my Mac, I get a message on my terminal saying '-bash: ~/torch/install/bin/torch-activate: No such file or directory'.

I have no solutions on how to remove this. 

Please help.

Regards.

**Comment by tastyminerals** [comment]
Open `~/.bashrc` file and remove the `. $PREFIX/bin/torch-activate` line.

**Comment by zosob** [comment]
I tried that, but nothing worked. I just reinstalled torch and no more error messages. I'll live with it.

**Comment by mulanshine** [comment]
> The line about add torch to your bashrc it is in 2 files `.bashrc` and `.profile`. Remove it from `.profile` too and problem solved

Thanks!

**Comment by codesmith25103** [comment]
@zosob i am also facing same error. How to download torch. can you please guide?
