### ISSUE TITLE
Linkage failure on libluaT.so

### ISSUE THREAD

**Issue by v1993** [torch/torch7#1168]
v@v-xubuntu:~/compile/luaffifb$ sudo luarocks --from=https://raw.githubusercontent.com/torch/rocks/master/ install torch
    Warning: The directory '/home/v/.cache/luarocks' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing /usr/lib/luarocks/rocks-5.2/luarocks/3.0.3-1/bin/luarocks with sudo, you may want sudo's -H flag.
    Installing https://raw.githubusercontent.com/torch/rocks/master/torch-scm-1.rockspec

    Клонирование в «torch7»…
    remote: Enumerating objects: 181, done.
    remote: Counting objects: 100% (181/181), done.
    remote: Compressing objects: 100% (174/174), done.
    remote: Total 181 (delta 8), reused 57 (delta 5), pack-reused 0
    Получение объектов: 100% (181/181), 335.51 KiB | 789.00 KiB/s, готово.
    Определение изменений: 100% (8/8), готово.
    cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DLUA=/usr/bin/lua5.2 -DLUALIB=liblua5.2.a -DLUA_BINDIR="/usr/bin" -DLUA_INCDIR="/usr/include/lua5.2" -DLUA_LIBDIR="/usr/lib/x86_64-linux-gnu" -DLUADIR="/usr/lib/luarocks/rocks-5.2/torch/scm-1/lua" -DLIBDIR="/usr/lib/luarocks/rocks-5.2/torch/scm-1/lib" -DCMAKE_INSTALL_PREFIX="/usr/lib/luarocks/rocks-5.2/torch/scm-1" && make

    -- The C compiler identification is GNU 7.3.0
    -- The CXX compiler identification is GNU 7.3.0
    -- Check for working C compiler: /usr/bin/gcc
    -- Check for working C compiler: /usr/bin/gcc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found OpenMP_C: -fopenmp (found version "4.5")
    -- Found OpenMP_CXX: -fopenmp (found version "4.5")
    -- Found OpenMP: TRUE (found version "4.5")
    -- Compiling with OpenMP support
    CMake Deprecation Warning at lib/TH/CMakeLists.txt:5 (CMAKE_POLICY):
      The OLD behavior for policy CMP0026 will be removed from a future version
      of CMake.

      The cmake-policies(7) manual explains that the OLD behaviors of all
      policies are deprecated and that a policy should be set to OLD only under
      specific short-term circumstances.  Projects should be ported to the NEW
      behavior and not rely on setting a policy to OLD.

    -- Found OpenMP_C: -fopenmp (found version "4.5")
    -- Found OpenMP_CXX: -fopenmp (found version "4.5")
    -- Compiling with OpenMP support
    -- Could not find hardware support for NEON on this machine.
    -- No OMAP3 processor on this machine.
    -- No OMAP4 processor on this machine.
    -- Looking for cpuid.h
    -- Looking for cpuid.h - found
    -- Performing Test HAVE_GCC_GET_CPUID
    -- Performing Test HAVE_GCC_GET_CPUID - Success
    -- Performing Test NO_GCC_EBX_FPIC_BUG
    -- Performing Test NO_GCC_EBX_FPIC_BUG - Success
    -- Performing Test C_HAS_SSE1_1
    -- Performing Test C_HAS_SSE1_1 - Success
    -- Performing Test C_HAS_SSE2_1
    -- Performing Test C_HAS_SSE2_1 - Success
    -- Performing Test C_HAS_SSE3_1
    -- Performing Test C_HAS_SSE3_1 - Failed
    -- Performing Test C_HAS_SSE3_2
    -- Performing Test C_HAS_SSE3_2 - Success
    -- Performing Test C_HAS_SSE4_1_1
    -- Performing Test C_HAS_SSE4_1_1 - Failed
    -- Performing Test C_HAS_SSE4_1_2
    -- Performing Test C_HAS_SSE4_1_2 - Success
    -- Performing Test C_HAS_SSE4_2_1
    -- Performing Test C_HAS_SSE4_2_1 - Failed
    -- Performing Test C_HAS_SSE4_2_2
    -- Performing Test C_HAS_SSE4_2_2 - Success
    -- Performing Test C_HAS_AVX_1
    -- Performing Test C_HAS_AVX_1 - Failed
    -- Performing Test C_HAS_AVX_2
    -- Performing Test C_HAS_AVX_2 - Success
    -- Performing Test C_HAS_AVX2_1
    -- Performing Test C_HAS_AVX2_1 - Failed
    -- Performing Test C_HAS_AVX2_2
    -- Performing Test C_HAS_AVX2_2 - Success
    -- Performing Test CXX_HAS_SSE1_1
    -- Performing Test CXX_HAS_SSE1_1 - Success
    -- Performing Test CXX_HAS_SSE2_1
    -- Performing Test CXX_HAS_SSE2_1 - Success
    -- Performing Test CXX_HAS_SSE3_1
    -- Performing Test CXX_HAS_SSE3_1 - Failed
    -- Performing Test CXX_HAS_SSE3_2
    -- Performing Test CXX_HAS_SSE3_2 - Success
    -- Performing Test CXX_HAS_SSE4_1_1
    -- Performing Test CXX_HAS_SSE4_1_1 - Failed
    -- Performing Test CXX_HAS_SSE4_1_2
    -- Performing Test CXX_HAS_SSE4_1_2 - Success
    -- Performing Test CXX_HAS_SSE4_2_1
    -- Performing Test CXX_HAS_SSE4_2_1 - Failed
    -- Performing Test CXX_HAS_SSE4_2_2
    -- Performing Test CXX_HAS_SSE4_2_2 - Success
    -- Performing Test CXX_HAS_AVX_1
    -- Performing Test CXX_HAS_AVX_1 - Failed
    -- Performing Test CXX_HAS_AVX_2
    -- Performing Test CXX_HAS_AVX_2 - Success
    -- Performing Test CXX_HAS_AVX2_1
    -- Performing Test CXX_HAS_AVX2_1 - Failed
    -- Performing Test CXX_HAS_AVX2_2
    -- Performing Test CXX_HAS_AVX2_2 - Success
    -- SSE2 Found
    -- SSE3 Found
    -- AVX Found
    -- AVX2 Found
    -- Performing Test HAS_C11_ATOMICS
    -- Performing Test HAS_C11_ATOMICS - Success
    -- TH_SO_VERSION: 0
    -- Atomics: using C11 intrinsics
    -- Looking for sys/types.h
    -- Looking for sys/types.h - found
    -- Looking for stdint.h
    -- Looking for stdint.h - found
    -- Looking for stddef.h
    -- Looking for stddef.h - found
    -- Check size of void*
    -- Check size of void* - done
    -- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf_lp64 - mkl_intel_thread - mkl_core - gomp - pthread - m - dl]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
    --   Library mkl_gf: not found
    -- Checking for [mkl_gf - mkl_intel_thread - mkl_core - gomp - pthread - m - dl]
    --   Library mkl_gf: not found
    -- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - gomp - pthread - m - dl]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
    --   Library mkl_intel: not found
    -- Checking for [mkl_intel - mkl_intel_thread - mkl_core - gomp - pthread - m - dl]
    --   Library mkl_intel: not found
    -- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m - dl]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m - dl]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - iomp5 - pthread - m - dl]
    --   Library mkl_gf: not found
    -- Checking for [mkl_gf - mkl_intel_thread - mkl_core - iomp5 - pthread - m - dl]
    --   Library mkl_gf: not found
    -- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m - dl]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m - dl]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - iomp5 - pthread - m - dl]
    --   Library mkl_intel: not found
    -- Checking for [mkl_intel - mkl_intel_thread - mkl_core - iomp5 - pthread - m - dl]
    --   Library mkl_intel: not found
    -- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - pthread - m - dl]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf_lp64 - mkl_intel_thread - mkl_core - pthread - m - dl]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - pthread - m - dl]
    --   Library mkl_gf: not found
    -- Checking for [mkl_gf - mkl_intel_thread - mkl_core - pthread - m - dl]
    --   Library mkl_gf: not found
    -- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - pthread - m - dl]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - pthread - m - dl]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - pthread - m - dl]
    --   Library mkl_intel: not found
    -- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m - dl]
    --   Library mkl_intel: not found
    -- Checking for [mkl_gf_lp64 - mkl_sequential - mkl_core - m - dl]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf - mkl_sequential - mkl_core - m - dl]
    --   Library mkl_gf: not found
    -- Checking for [mkl_intel_lp64 - mkl_sequential - mkl_core - m - dl]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel - mkl_sequential - mkl_core - m - dl]
    --   Library mkl_intel: not found
    -- Checking for [mkl_gf_lp64 - mkl_sequential - mkl_core - m - dl]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf - mkl_sequential - mkl_core - m - dl]
    --   Library mkl_gf: not found
    -- Checking for [mkl_intel_lp64 - mkl_sequential - mkl_core - m - dl]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel - mkl_sequential - mkl_core - m - dl]
    --   Library mkl_intel: not found
    -- Checking for [mkl_gf_lp64 - mkl_sequential - mkl_core - m - dl]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf - mkl_sequential - mkl_core - m - dl]
    --   Library mkl_gf: not found
    -- Checking for [mkl_intel_lp64 - mkl_sequential - mkl_core - m - dl]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel - mkl_sequential - mkl_core - m - dl]
    --   Library mkl_intel: not found
    -- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf_lp64 - mkl_intel_thread - mkl_core - gomp - pthread - m - dl]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
    --   Library mkl_gf: not found
    -- Checking for [mkl_gf - mkl_intel_thread - mkl_core - gomp - pthread - m - dl]
    --   Library mkl_gf: not found
    -- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - gomp - pthread - m - dl]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
    --   Library mkl_intel: not found
    -- Checking for [mkl_intel - mkl_intel_thread - mkl_core - gomp - pthread - m - dl]
    --   Library mkl_intel: not found
    -- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m - dl]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m - dl]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - iomp5 - pthread - m - dl]
    --   Library mkl_gf: not found
    -- Checking for [mkl_gf - mkl_intel_thread - mkl_core - iomp5 - pthread - m - dl]
    --   Library mkl_gf: not found
    -- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - iomp5 - pthread - m - dl]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - iomp5 - pthread - m - dl]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - iomp5 - pthread - m - dl]
    --   Library mkl_intel: not found
    -- Checking for [mkl_intel - mkl_intel_thread - mkl_core - iomp5 - pthread - m - dl]
    --   Library mkl_intel: not found
    -- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - pthread - m - dl]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf_lp64 - mkl_intel_thread - mkl_core - pthread - m - dl]
    --   Library mkl_gf_lp64: not found
    -- Checking for [mkl_gf - mkl_gnu_thread - mkl_core - pthread - m - dl]
    --   Library mkl_gf: not found
    -- Checking for [mkl_gf - mkl_intel_thread - mkl_core - pthread - m - dl]
    --   Library mkl_gf: not found
    -- Checking for [mkl_intel_lp64 - mkl_gnu_thread - mkl_core - pthread - m - dl]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel_lp64 - mkl_intel_thread - mkl_core - pthread - m - dl]
    --   Library mkl_intel_lp64: not found
    -- Checking for [mkl_intel - mkl_gnu_thread - mkl_core - pthread - m - dl]
    --   Library mkl_intel: not found
    -- Checking for [mkl_intel - mkl_intel_thread - mkl_core - pthread - m - dl]
    --   Library mkl_intel: not found
    -- Checking for [mkl - guide - pthread - m]
    --   Library mkl: not found
    -- MKL library not found
    -- Checking for [openblas]
    --   Library openblas: /usr/lib/x86_64-linux-gnu/libopenblas.so
    -- Looking for sgemm_
    -- Looking for sgemm_ - found
    -- Performing Test BLAS_F2C_DOUBLE_WORKS
    -- Performing Test BLAS_F2C_DOUBLE_WORKS - Failed
    -- Performing Test BLAS_F2C_FLOAT_WORKS
    -- Performing Test BLAS_F2C_FLOAT_WORKS - Success
    -- Performing Test BLAS_USE_CBLAS_DOT
    -- Performing Test BLAS_USE_CBLAS_DOT - Success
    -- Found a library with BLAS API (open).
    -- Looking for cheev_
    -- Looking for cheev_ - found
    -- Found a library with LAPACK API. (open)
    -- Looking for clock_gettime in rt
    -- Looking for clock_gettime in rt - found
    -- Looking for mmap
    -- Looking for mmap - found
    -- Looking for shm_open
    -- Looking for shm_open - found
    -- Looking for shm_unlink
    -- Looking for shm_unlink - found
    -- Looking for malloc_usable_size
    -- Looking for malloc_usable_size - found
    -- Performing Test C_HAS_THREAD
    -- Performing Test C_HAS_THREAD - Success
    CMake Deprecation Warning at lib/luaT/CMakeLists.txt:3 (CMAKE_POLICY):
      The OLD behavior for policy CMP0026 will be removed from a future version
      of CMake.

      The cmake-policies(7) manual explains that the OLD behaviors of all
      policies are deprecated and that a policy should be set to OLD only under
      specific short-term circumstances.  Projects should be ported to the NEW
      behavior and not rely on setting a policy to OLD.

    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/luarocks_torch-scm-1-bTKYJG/torch7/build
    Scanning dependencies of target TH
    [  2%] Building C object lib/TH/CMakeFiles/TH.dir/THGeneral.c.o
    [  5%] Building C object lib/TH/CMakeFiles/TH.dir/THHalf.c.o
    [  7%] Building C object lib/TH/CMakeFiles/TH.dir/THAllocator.c.o
    [ 10%] Building C object lib/TH/CMakeFiles/TH.dir/THSize.c.o
    [ 12%] Building C object lib/TH/CMakeFiles/TH.dir/THStorage.c.o
    [ 15%] Building C object lib/TH/CMakeFiles/TH.dir/THTensor.c.o
    [ 17%] Building C object lib/TH/CMakeFiles/TH.dir/THBlas.c.o
    [ 20%] Building C object lib/TH/CMakeFiles/TH.dir/THLapack.c.o
    [ 23%] Building C object lib/TH/CMakeFiles/TH.dir/THLogAdd.c.o
    [ 25%] Building C object lib/TH/CMakeFiles/TH.dir/THRandom.c.o
    [ 28%] Building C object lib/TH/CMakeFiles/TH.dir/THFile.c.o
    [ 30%] Building C object lib/TH/CMakeFiles/TH.dir/THDiskFile.c.o
    [ 33%] Building C object lib/TH/CMakeFiles/TH.dir/THMemoryFile.c.o
    [ 35%] Building C object lib/TH/CMakeFiles/TH.dir/THAtomic.c.o
    [ 38%] Building C object lib/TH/CMakeFiles/TH.dir/THVector.c.o
    [ 41%] Building C object lib/TH/CMakeFiles/TH.dir/generic/simd/convolve.c.o
    [ 43%] Building C object lib/TH/CMakeFiles/TH.dir/generic/simd/convolve5x5_sse.c.o
    [ 46%] Building C object lib/TH/CMakeFiles/TH.dir/vector/AVX.c.o
    [ 48%] Building C object lib/TH/CMakeFiles/TH.dir/generic/simd/convolve5x5_avx.c.o
    [ 51%] Building C object lib/TH/CMakeFiles/TH.dir/vector/AVX2.c.o
    [ 53%] Linking C shared library libTH.so
    [ 53%] Built target TH
    Scanning dependencies of target luaT
    [ 56%] Building C object lib/luaT/CMakeFiles/luaT.dir/luaT.c.o
    [ 58%] Linking C shared library libluaT.so
    /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/liblua5.2.a(lstate.o): relocation R_X86_64_PC32 against symbol `lua_newstate' can not be used when making a shared object; перекомпилируйте с параметром -fPIC
    /usr/bin/ld: final link failed: Некорректное значение
    collect2: error: ld returned 1 exit status
    lib/luaT/CMakeFiles/luaT.dir/build.make:94: recipe for target 'lib/luaT/libluaT.so.0' failed
    make[2]: *** [lib/luaT/libluaT.so.0] Error 1
    CMakeFiles/Makefile2:199: recipe for target 'lib/luaT/CMakeFiles/luaT.dir/all' failed
    make[1]: *** [lib/luaT/CMakeFiles/luaT.dir/all] Error 2
    Makefile:129: recipe for target 'all' failed
    make: *** [all] Error 2

    Error: Build error: Failed building.

**Comment by tastyminerals** [comment]
I don't think this is Torch related, see relevant [stackoverflow issue](https://stackoverflow.com/questions/19768267/relocation-r-x86-64-32s-against-linking-error).

**Comment by tastyminerals** [comment]
Why are you running `torch-scm-1.rockspec` with `luarocks` and even using `sudo`? Please read the official installation guidelines.

**Comment by v1993** [comment]
This issue has been fixed by itself…

BTW, I've using torcho with usual luarocks for a long time without luarocks-related problems.

**Comment by tastyminerals** [comment]
Then you probably have not installed some of the torch dependencies that are only available via `torch/install/bin/luarocks` version. For example, `rnn`, `dpnn`, `cunn` packages. There is a reason why Torch lives in a separate dir :)
