### ISSUE TITLE
Improving Random number initialization on Unix platforms

### ISSUE THREAD

**Issue by jjh42** [torch/torch7#117]
Currently torch initializes its random number generation by using the time in seconds. When running jobs in parallel this makes it easy to accidentally have jobs which have the same seed.

I'm opening this issue to propose:
attempting to fopen '/dev/urandom' in THRandom_seed and use that to initialize seed the seed. If this fails fall back to using time (i.e. on non-unix systems).

If this approach seems reasonable I'll work on a patch.

**Comment by chavman69** [comment]
Hi

**Comment by soumith** [comment]
i dont see a reason why it is not acceptable. As long as it is guarded with ah #ifdef to keep windows compatibility (not sure why we still care, but for the core, let's pretend it works with windows)

**Comment by jjh42** [comment]
PR https://github.com/torch/torch7/pull/118
