### ISSUE TITLE
Installation failed on Ubuntu 18.04.1 LTS Build Error

### ISSUE THREAD

**Issue by johhnry** [torch/torch7#1177]
Hello,

I have a problem with installing Torch with this link : http://torch.ch/docs/getting-started.html#_
I am on Ubuntu 18.04.1 LTS 64 bit and when I run the `./install.sh`, I have this error (two times even after uninstalling) : 

```readline.c:8:10: fatal error: readline/readline.h: Any file or folder of this type
 #include <readline/readline.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Error: Build error: Failed compiling object readline.o
```

Thanks

**Comment by alexmyczko** [comment]
Try installing `libreadline-dev`

**Comment by ucasiggcas** [comment]
> Try installing `libreadline-dev`

It's important.
I have the same question, and then solve it
