### ISSUE TITLE
Installation error with RTX 2080, CUDA 9.0, CUDNN 7.4 nvcc fatal : Unsupported gpu architecture 'compute_75'

### ISSUE THREAD

**Issue by nohboogy** [torch/torch7#1190]
While trying to install torch, same error comes out.

> 
> canning dependencies of target image
> [ 87%] Building C object CMakeFiles/image.dir/image.c.o
> [100%] Linking C shared module libimage.so
> [100%] Built target image
> cd build && make install
> [ 25%] Built target jpeg
> [ 50%] Built target ppm
> [ 75%] Built target lua_png
> [100%] Built target image
> Install the project...
> -- Install configuration: "Release"
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lib/libppm.so
> -- Set runtime path of "/home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lib/libppm.so" to "$ORIGIN/../lib:/home/wooseok/torch/install/lib:/opt/OpenBLAS/lib"
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lib/libjpeg.so
> -- Set runtime path of "/home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lib/libjpeg.so" to "$ORIGIN/../lib:/home/wooseok/torch/install/lib:/opt/OpenBLAS/lib"
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lib/liblua_png.so
> -- Set runtime path of "/home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lib/liblua_png.so" to "$ORIGIN/../lib:/home/wooseok/torch/install/lib:/opt/OpenBLAS/lib"
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lib/libimage.so
> -- Set runtime path of "/home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lib/libimage.so" to "$ORIGIN/../lib:/home/wooseok/torch/install/lib:/opt/OpenBLAS/lib"
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lua/image/init.lua
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lua/image/win.ui
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lua/image/test.lua
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lua/image/assets
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lua/image/assets/grace_hopper_512.jpg
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lua/image/assets/corrupt-ihdr.png
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lua/image/assets/gray3x1.png
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lua/image/assets/grace_hopper_512.png
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lua/image/assets/rectangle.png
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lua/image/assets/P4.pbm
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lua/image/assets/rgb2x1.png
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lua/image/assets/foobar.png
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lua/image/assets/P6.ppm
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lua/image/assets/P5.pgm
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lua/image/assets/P2.pgm
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lua/image/assets/gray16-1x2.png
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lua/image/assets/bmp-without-ext
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lua/image/assets/fabio.png
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lua/image/assets/fabio.jpg
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lua/image/assets/rgb16-2x1.png
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/image/1.1.alpha-0/lua/image/README.md
> Updating manifest for /home/wooseok/torch/install/lib/luarocks/rocks
> image 1.1.alpha-0 is now built and installed in /home/wooseok/torch/install/ (license: BSD)
> 
> cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/wooseok/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0" && make
>    
> -- The C compiler identification is GNU 5.4.0
> -- The CXX compiler identification is GNU 5.4.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found Torch7 in /home/wooseok/torch/install
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/wooseok/torch/pkg/optim/build
> cd build && make install
> Install the project...
> -- Install configuration: "Release"
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/adadelta.lua
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/cg.lua
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/lswolfe.lua
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/nag.lua
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/rmsprop.lua
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/ConfusionMatrix.lua
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/adagrad.lua
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/sgd.lua
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/polyinterp.lua
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/lbfgs.lua
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/adamax.lua
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/adam.lua
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/init.lua
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/de.lua
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/fista.lua
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/cmaes.lua
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/rprop.lua
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/checkgrad.lua
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/Logger.lua
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/asgd.lua
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/doc
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/doc/intro.md
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/doc/algos.md
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/doc/logger.md
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/doc/logger_plot.png
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/doc/image
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/doc/image/parameterflattening.svg
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/doc/image/parameterflattening.png
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/doc/image/parameterflattening.svg.png
> -- Installing: /home/wooseok/torch/install/lib/luarocks/rocks/optim/1.0.5-0/lua/optim/README.md
> Updating manifest for /home/wooseok/torch/install/lib/luarocks/rocks
> optim 1.0.5-0 is now built and installed in /home/wooseok/torch/install/ (license: BSD)
> 
> Found CUDA on your machine. Installing CUDA packages
> Warning: unmatched variable LUALIB
> 
> jopts=$(getconf _NPROCESSORS_CONF)
> 
> echo "Building on $jopts cores"
> cmake -E make_directory build && cd build && cmake .. -DLUALIB= -DLUA_INCDIR=/home/wooseok/torch/install/include -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS} -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/wooseok/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/wooseok/torch/install/lib/luarocks/rocks/cutorch/scm-1" && make -j$jopts install
> 
> Building on 8 cores
> -- The C compiler identification is GNU 5.4.0
> -- The CXX compiler identification is GNU 5.4.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found Torch7 in /home/wooseok/torch/install
> -- Found CUDA: /usr/local/cuda-9.0 (found suitable version "9.0", minimum required is "6.5") 
> -- Removing -DNDEBUG from compile flags
> -- TH_LIBRARIES: TH
> -- MAGMA not found. Compiling without MAGMA support
> -- Autodetected CUDA architecture(s): 7.5
> -- got cuda version 9.0
> -- Found CUDA with FP16 support, compiling with torch.CudaHalfTensor
> -- CUDA_NVCC_FLAGS: -D__CUDA_NO_HALF_OPERATORS__;-gencode;arch=compute_75,code=sm_75;-DCUDA_HAS_FP16=1
> -- THC_SO_VERSION: 0
> -- Performing Test HAS_LUAL_SETFUNCS
> -- Performing Test HAS_LUAL_SETFUNCS - Failed
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/wooseok/torch/extra/cutorch/build
> [  2%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o
> [  2%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o
> [  3%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o
> [  4%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCSleep.cu.o
> [  5%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o
> [  6%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o
> [  7%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o
> [  8%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o
> nvcc fatal   : Unsupported gpu architecture 'compute_75'
> nvcc fatal   : Unsupported gpu architecture 'compute_75'
> CMake Error at THC_generated_THCSleep.cu.o.cmake:207 (message):
>   Error generating
>   /home/wooseok/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCSleep.cu.o
> 
> 
> CMake Error at THC_generated_THCReduceApplyUtils.cu.o.cmake:207 (message):
>   Error generating
>   /home/wooseok/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCReduceApplyUtils.cu.o
> 
> 
> lib/THC/CMakeFiles/THC.dir/build.make:77: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCSleep.cu.o' failed
> make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCSleep.cu.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> lib/THC/CMakeFiles/THC.dir/build.make:63: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o' failed
> make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCReduceApplyUtils.cu.o] Error 1
> nvcc fatal   : Unsupported gpu architecture 'compute_75'
> nvcc fatal   : Unsupported gpu architecture 'compute_75'
> CMake Error at THC_generated_THCBlas.cu.o.cmake:207 (message):
>   Error generating
>   /home/wooseok/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCBlas.cu.o
> 
> 
> CMake Error at THC_generated_THCTensor.cu.o.cmake:207 (message):
>   Error generating
>   /home/wooseok/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensor.cu.o
> 
> 
> lib/THC/CMakeFiles/THC.dir/build.make:70: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o' failed
> make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCBlas.cu.o] Error 1
> lib/THC/CMakeFiles/THC.dir/build.make:98: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o' failed
> make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensor.cu.o] Error 1
> nvcc fatal   : Unsupported gpu architecture 'compute_75'
> CMake Error at THC_generated_THCTensorCopy.cu.o.cmake:207 (message):
>   Error generating
>   /home/wooseok/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorCopy.cu.o
> 
> 
> nvcc fatal   : Unsupported gpu architecture 'compute_75'
> CMake Error at THC_generated_THCStorage.cu.o.cmake:207 (message):
>   Error generating
>   /home/wooseok/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorage.cu.o
> 
> 
> nvcc fatal   : Unsupported gpu architecture 'compute_75'
> nvcc fatal   : Unsupported gpu architecture 'compute_75'
> CMake Error at THC_generated_THCHalf.cu.o.cmake:207 (message):
>   Error generating
>   /home/wooseok/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCHalf.cu.o
> 
> 
> CMake Error at THC_generated_THCStorageCopy.cu.o.cmake:207 (message):
>   Error generating
>   /home/wooseok/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorageCopy.cu.o
> 
> 
> lib/THC/CMakeFiles/THC.dir/build.make:105: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o' failed
> make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCTensorCopy.cu.o] Error 1
> lib/THC/CMakeFiles/THC.dir/build.make:84: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o' failed
> make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorage.cu.o] Error 1
> lib/THC/CMakeFiles/THC.dir/build.make:560: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o' failed
> make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCHalf.cu.o] Error 1
> lib/THC/CMakeFiles/THC.dir/build.make:91: recipe for target 'lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o' failed
> make[2]: *** [lib/THC/CMakeFiles/THC.dir/THC_generated_THCStorageCopy.cu.o] Error 1
> CMakeFiles/Makefile2:172: recipe for target 'lib/THC/CMakeFiles/THC.dir/all' failed
> make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2
> 
> Error: Build error: Failed building.
> 

I think it is because I'm using RTX graphic driver, but I cannot find any way to install torch now. 
Anyone can solve this problem?

**Comment by zhangqijun** [comment]
same question，need some help

**Comment by pablovicentem** [comment]
Did you achieve to solve the problem? I have the same problem with the RTX2080 and ubuntu 18.04 and I really need to solve it. Thanks

**Comment by nohboogy** [comment]
@zhangqijun @pablovicentem
I solved this problem with reinstalling CUDA 10.0.
CUDA 9.0 dosen't support rtx 2080 even though it looks like we could install many applications with it.

**Comment by WanliXue** [comment]
I am with CUDA 10.0, still suffers this issue:

`nvcc fatal   : Unsupported gpu architecture 'compute_75'`  when install Torch on `	Ubuntu 16.04.6 LTS`


 Fri Mar 29 10:12:20 2019       
	+-----------------------------------------------------------------------------+
	| NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.0     |
	|-------------------------------+----------------------+----------------------+
	| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
	| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
	|===============================+======================+======================|
	|   0  GeForce RTX 208...  Off  | 00000000:19:00.0 Off |                  N/A |
	| 27%   29C    P8    11W / 250W |     11MiB / 10989MiB |      0%      Default |
	+-------------------------------+----------------------+----------------------+
	|   1  GeForce RTX 208...  Off  | 00000000:1A:00.0 Off |                  N/A |
	| 27%   31C    P8    10W / 250W |     11MiB / 10989MiB |      0%      Default |
	+-------------------------------+----------------------+----------------------+
	|   2  GeForce RTX 208...  Off  | 00000000:67:00.0 Off |                  N/A |
	| 27%   35C    P8    21W / 250W |     11MiB / 10989MiB |      0%      Default |
	+-------------------------------+----------------------+----------------------+
	|   3  GeForce RTX 208...  Off  | 00000000:68:00.0  On |                  N/A |
	| 27%   34C    P8    21W / 250W |     71MiB / 10986MiB |      0%      Default |
	+-------------------------------+----------------------+----------------------+
	                                                                               
	+-----------------------------------------------------------------------------+
	| Processes:                                                       GPU Memory |
	|  GPU       PID   Type   Process name                             Usage      |
	|=============================================================================|
	|    3      1055      G   /usr/lib/xorg/Xorg                            59MiB |
	+-----------------------------------------------------------------------------+

**Comment by ha-lins** [comment]
> I am with CUDA 10.0, still suffers this issue:
> 
> `nvcc fatal : Unsupported gpu architecture 'compute_75'` when install Torch on `	Ubuntu 16.04.6 LTS`
> 
> Fri Mar 29 10:12:20 2019
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 410.78 Driver Version: 410.78 CUDA Version: 10.0 |
> |-------------------------------+----------------------+----------------------+
> | GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
> | Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
> |===============================+======================+======================|
> | 0 GeForce RTX 208... Off | 00000000:19:00.0 Off | N/A |
> | 27% 29C P8 11W / 250W | 11MiB / 10989MiB | 0% Default |
> +-------------------------------+----------------------+----------------------+
> | 1 GeForce RTX 208... Off | 00000000:1A:00.0 Off | N/A |
> | 27% 31C P8 10W / 250W | 11MiB / 10989MiB | 0% Default |
> +-------------------------------+----------------------+----------------------+
> | 2 GeForce RTX 208... Off | 00000000:67:00.0 Off | N/A |
> | 27% 35C P8 21W / 250W | 11MiB / 10989MiB | 0% Default |
> +-------------------------------+----------------------+----------------------+
> | 3 GeForce RTX 208... Off | 00000000:68:00.0 On | N/A |
> | 27% 34C P8 21W / 250W | 71MiB / 10986MiB | 0% Default |
> +-------------------------------+----------------------+----------------------+
> 
> ```
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |    3      1055      G   /usr/lib/xorg/Xorg                            59MiB |
> +-----------------------------------------------------------------------------+
> ```

Hi, have you solved the torch installition problem ? I have the same problem and cannot solve it.
Thanks!

**Comment by WanliXue** [comment]
> > I am with CUDA 10.0, still suffers this issue:
> > `nvcc fatal : Unsupported gpu architecture 'compute_75'` when install Torch on `	Ubuntu 16.04.6 LTS`
> > Fri Mar 29 10:12:20 2019
> > +-----------------------------------------------------------------------------+
> > | NVIDIA-SMI 410.78 Driver Version: 410.78 CUDA Version: 10.0 |
> > |-------------------------------+----------------------+----------------------+
> > | GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
> > | Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
> > |===============================+======================+======================|
> > | 0 GeForce RTX 208... Off | 00000000:19:00.0 Off | N/A |
> > | 27% 29C P8 11W / 250W | 11MiB / 10989MiB | 0% Default |
> > +-------------------------------+----------------------+----------------------+
> > | 1 GeForce RTX 208... Off | 00000000:1A:00.0 Off | N/A |
> > | 27% 31C P8 10W / 250W | 11MiB / 10989MiB | 0% Default |
> > +-------------------------------+----------------------+----------------------+
> > | 2 GeForce RTX 208... Off | 00000000:67:00.0 Off | N/A |
> > | 27% 35C P8 21W / 250W | 11MiB / 10989MiB | 0% Default |
> > +-------------------------------+----------------------+----------------------+
> > | 3 GeForce RTX 208... Off | 00000000:68:00.0 On | N/A |
> > | 27% 34C P8 21W / 250W | 71MiB / 10986MiB | 0% Default |
> > +-------------------------------+----------------------+----------------------+
> > ```
> > +-----------------------------------------------------------------------------+
> > | Processes:                                                       GPU Memory |
> > |  GPU       PID   Type   Process name                             Usage      |
> > |=============================================================================|
> > |    3      1055      G   /usr/lib/xorg/Xorg                            59MiB |
> > +-----------------------------------------------------------------------------+
> > ```
> 
> Hi, have you solved the torch installition problem ? I have the same problem and cannot solve it.
> Thanks!

**Comment by WanliXue** [comment]
> > I am with CUDA 10.0, still suffers this issue:
> > `nvcc fatal : Unsupported gpu architecture 'compute_75'` when install Torch on `	Ubuntu 16.04.6 LTS`
> > Fri Mar 29 10:12:20 2019
> > +-----------------------------------------------------------------------------+
> > | NVIDIA-SMI 410.78 Driver Version: 410.78 CUDA Version: 10.0 |
> > |-------------------------------+----------------------+----------------------+
> > | GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
> > | Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
> > |===============================+======================+======================|
> > | 0 GeForce RTX 208... Off | 00000000:19:00.0 Off | N/A |
> > | 27% 29C P8 11W / 250W | 11MiB / 10989MiB | 0% Default |
> > +-------------------------------+----------------------+----------------------+
> > | 1 GeForce RTX 208... Off | 00000000:1A:00.0 Off | N/A |
> > | 27% 31C P8 10W / 250W | 11MiB / 10989MiB | 0% Default |
> > +-------------------------------+----------------------+----------------------+
> > | 2 GeForce RTX 208... Off | 00000000:67:00.0 Off | N/A |
> > | 27% 35C P8 21W / 250W | 11MiB / 10989MiB | 0% Default |
> > +-------------------------------+----------------------+----------------------+
> > | 3 GeForce RTX 208... Off | 00000000:68:00.0 On | N/A |
> > | 27% 34C P8 21W / 250W | 71MiB / 10986MiB | 0% Default |
> > +-------------------------------+----------------------+----------------------+
> > ```
> > +-----------------------------------------------------------------------------+
> > | Processes:                                                       GPU Memory |
> > |  GPU       PID   Type   Process name                             Usage      |
> > |=============================================================================|
> > |    3      1055      G   /usr/lib/xorg/Xorg                            59MiB |
> > +-----------------------------------------------------------------------------+
> > ```
> 
> Hi, have you solved the torch installition problem ? I have the same problem and cannot solve it.
> Thanks!

I am sorry, I didnt get a solution for this.

**Comment by talkenig** [comment]
Had the same problem and got to the bottom of it. My configuration is a Tesla T4 with 410.92 driver and CUDA 9.2, Ubuntu 18.10.
The thing is, the torch installer tries for some reason to use the highest compute capability supported by the device (or the driver - not sure which), but ignores the compute capability supported by the CUDA toolkit.
So, in my case the device supports compute capability 7.5, but CUDA 9.2 supports only 7.0 or 7.2 (not sure which one). You can guess I got the same` nvcc fatal : Unsupported gpu architecture 'compute_75'`
The solution is to force the nvcc compile options to use a lower compute capability. This can be achieved by setting the following environment variable:

>  export TORCH_CUDA_ARCH_LIST="7.0"
Just before running ./install.sh from the torch directory.
Note that the list may contain more than one compute capability, e.g. it can be "6.0 6.2 7.0 7.2". This will be reflected in the CUDA_NVCC_FLAGS -gencode arch=compute_70,code=sm_70 and those will be outputted to the terminal during the build.

**Comment by RishengZhou** [comment]
> @ha-lins @WanliXue @pablovicentem @nohboogy @zhangqijun
> Had the same problem and got to the bottom of it. My configuration is a Tesla T4 with 410.92 driver and CUDA 9.2, Ubuntu 18.10.
> The thing is, the torch installer tries for some reason to use the highest compute capability supported by the device (or the driver - not sure which), but ignores the compute capability supported by the CUDA toolkit.
> So, in my case the device supports compute capability 7.5, but CUDA 9.2 supports only 7.0 or 7.2 (not sure which one). You can guess I got the same` nvcc fatal : Unsupported gpu architecture 'compute_75'`
> The solution is to force the nvcc compile options to use a lower compute capability. This can be achieved by setting the following environment variable:
> 
> > export TORCH_CUDA_ARCH_LIST="7.0"
> 
> Just before running ./install.sh from the torch directory.
> Note that the list may contain more than one compute capability, e.g. it can be "6.0 6.2 7.0 7.2". This will be reflected in the CUDA_NVCC_FLAGS -gencode arch=compute_70,code=sm_70 and those will be outputted to the terminal during the build.

Thanks! It works.

**Comment by talkenig** [comment]
By the way, another approach that worked for me without any tweaks needed, on a machine with Ubuntu 18.04 and CUDA 10.1 is simply using the following git repo instead of the official one: 
https://github.com/nagadomi/distro

**Comment by vicya** [comment]
> @ha-lins @WanliXue @pablovicentem @nohboogy @zhangqijun
> Had the same problem and got to the bottom of it. My configuration is a Tesla T4 with 410.92 driver and CUDA 9.2, Ubuntu 18.10.
> The thing is, the torch installer tries for some reason to use the highest compute capability supported by the device (or the driver - not sure which), but ignores the compute capability supported by the CUDA toolkit.
> So, in my case the device supports compute capability 7.5, but CUDA 9.2 supports only 7.0 or 7.2 (not sure which one). You can guess I got the same` nvcc fatal : Unsupported gpu architecture 'compute_75'`
> The solution is to force the nvcc compile options to use a lower compute capability. This can be achieved by setting the following environment variable:
> 
> > export TORCH_CUDA_ARCH_LIST="7.0"
> 
> Just before running ./install.sh from the torch directory.
> Note that the list may contain more than one compute capability, e.g. it can be "6.0 6.2 7.0 7.2". This will be reflected in the CUDA_NVCC_FLAGS -gencode arch=compute_70,code=sm_70 and those will be outputted to the terminal during the build.


Thanks ! My configuration is a RTX 2080  CUDA 7.5, Ubuntu 16.04, 
>> export TORCH_CUDA_ARCH_LIST="5.0"

**Comment by viven12138** [comment]
> @ha-lins @WanliXue @pablovicentem @nohboogy @zhangqijun
> Had the same problem and got to the bottom of it. My configuration is a Tesla T4 with 410.92 driver and CUDA 9.2, Ubuntu 18.10.
> The thing is, the torch installer tries for some reason to use the highest compute capability supported by the device (or the driver - not sure which), but ignores the compute capability supported by the CUDA toolkit.
> So, in my case the device supports compute capability 7.5, but CUDA 9.2 supports only 7.0 or 7.2 (not sure which one). You can guess I got the same` nvcc fatal : Unsupported gpu architecture 'compute_75'`
> The solution is to force the nvcc compile options to use a lower compute capability. This can be achieved by setting the following environment variable:
> 
> > export TORCH_CUDA_ARCH_LIST="7.0"
> 
> Just before running ./install.sh from the torch directory.
> Note that the list may contain more than one compute capability, e.g. it can be "6.0 6.2 7.0 7.2". This will be reflected in the CUDA_NVCC_FLAGS -gencode arch=compute_70,code=sm_70 and those will be outputted to the terminal during the build.

Thanks!  I met the issue when i install detectron2. It works! You are amazing!

**Comment by morganmcg1** [comment]
I had 2 different versions of CUDA, but solved it by removing everything and re-installing 10.1

I'm on Ubuntu 18.04 with 2080

Highly recommend following the instructions in this blog, worked perfectly for me: https://medium.com/@exesse/cuda-10-1-installation-on-ubuntu-18-04-lts-d04f89287130

**Comment by duybn-0885** [comment]
> @ha-lins @WanliXue @pablovicentem @nohboogy @zhangqijun
> Had the same problem and got to the bottom of it. My configuration is a Tesla T4 with 410.92 driver and CUDA 9.2, Ubuntu 18.10.
> The thing is, the torch installer tries for some reason to use the highest compute capability supported by the device (or the driver - not sure which), but ignores the compute capability supported by the CUDA toolkit.
> So, in my case the device supports compute capability 7.5, but CUDA 9.2 supports only 7.0 or 7.2 (not sure which one). You can guess I got the same` nvcc fatal : Unsupported gpu architecture 'compute_75'`
> The solution is to force the nvcc compile options to use a lower compute capability. This can be achieved by setting the following environment variable:
> 
> > export TORCH_CUDA_ARCH_LIST="7.0"
> 
> Just before running ./install.sh from the torch directory.
> Note that the list may contain more than one compute capability, e.g. it can be "6.0 6.2 7.0 7.2". This will be reflected in the CUDA_NVCC_FLAGS -gencode arch=compute_70,code=sm_70 and those will be outputted to the terminal during the build.

I follow this solution but seem it does not work for me. I have tried other lower version, but still not working.
