### ISSUE TITLE
ubuntu 18.04 Build Error

### ISSUE THREAD

**Issue by xuliang-a** [torch/torch7#1224]
When I run  “sudo ./install.sh" errors occurred!

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_device_LIBRARY (ADVANCED)
    linked by target "THC" in directory /home/a/torch/extra/cutorch/lib/THC

-- Configuring incomplete, errors occurred!
See also "/home/a/torch/extra/cutorch/build/CMakeFiles/CMakeOutput.log".
See also "/home/a/torch/extra/cutorch/build/CMakeFiles/CMakeError.log".

=============================================================================
CMakeError.log

Run Build Command:"/usr/bin/make" "cmTC_8b6f2/fast"
/usr/bin/make -f CMakeFiles/cmTC_8b6f2.dir/build.make CMakeFiles/cmTC_8b6f2.dir/build
make[1]: 进入目录“/home/a/torch/build/CMakeFiles/CMakeTmp”
Building C object CMakeFiles/cmTC_8b6f2.dir/src.c.o
/usr/bin/cc  -I/home/a/torch/build/exe/luajit-rocks/luajit-2.1 -I/home/a/torch/exe/luajit-rocks/luajit-2.1/src  -DLJ_ABI_SOFTFP_1   -o CMakeFiles/cmTC_8b6f2.dir/src.c.o   -c /home/a/torch/build/CMakeFiles/CMakeTmp/src.c
/home/a/torch/build/CMakeFiles/CMakeTmp/src.c:7:2: error: #error "not defined"
 #error "not defined"
  ^~~~~
CMakeFiles/cmTC_8b6f2.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_8b6f2.dir/src.c.o' failed
make[1]: *** [CMakeFiles/cmTC_8b6f2.dir/src.c.o] Error 1
make[1]: 离开目录“/home/a/torch/build/CMakeFiles/CMakeTmp”
Makefile:126: recipe for target 'cmTC_8b6f2/fast' failed
make: *** [cmTC_8b6f2/fast] Error 2

Source file was:

#undef LJ_ABI_SOFTFP
#include "lj_arch.h"
#if LJ_ABI_SOFTFP == 1
int main() { return 0; }
#else
#error "not defined"
#endif
=============================================================================

**Comment by xuliang-a** [comment]
I found the answer.
https://github.com/torch/cutorch/issues/834

**Comment by bapijun** [comment]
good answer for me
