### ISSUE TITLE
`help` command in iTorch does not understand symbols iTorch is procesing

### ISSUE THREAD

**Issue by jkbrooks** [torch/torch7#133]
I am following the Torch tutorial here: http://code.madbits.com/wiki/doku.php?id=tutorial_basics

When I try to use the `help` function in iTorch, I cannot get help on certain functions.  For example:

````
In [17]:
help(itorch.image)

Out[17]:
undocumented symbol	

In [18]:
help(res:view)
[string "help(res:view)..."]:1: function arguments expected near ')'
````

These functions themselves work correctly (after adding the appropriate preceding code from the tutorial).  Am I calling the `help` command incorrectly or is there just missing documentation?

**Comment by soumith** [comment]
@jkbrooks iTorch does not yet have documentation that is generated for inline help. What you are doing is correct.

For view, you have to call help on torch.view, i.e.
?torch.view
or 
help(torch.view)

**Comment by kirk86** [comment]
@soumith I'm experiencing the same thing after a fresh install of torch
`?torch.Tensor`
`undocumented symbol`

`require(nn)`
`?nn.Sequential`
`undocumented symbol`

is that normal behaviour?

**Comment by hyiltiz** [comment]
I tried `?itorch.image` to see what are the input arguments for this function from within Jupyter notebook, but got nothing informative. If the documentation is not ready yet, at least putting dummy documentation that says `The documentation for this function is not written yet; please check source code for this function at file file:///path/to/the/implementation` would be great. As I am very new to Jupyter and Lua, I am even not sure how to check where those implementations come from (probably Google can tell me, but just as I am, not every user knows how to lookup the implementation).
