### ISSUE TITLE
module 'cunn' not found

### ISSUE THREAD

**Issue by jiangfeng15** [torch/torch7#142]
when I run the code, require 'cunn' ,it appears,
no field package.preload['cunn']
	no file './cunn.lua'
	no file '/usr/local/share/luajit-2.0.2/cunn.lua'
	no file '/usr/local/share/lua/5.1/cunn.lua'
	no file '/usr/local/share/lua/5.1/cunn/init.lua'
	no file './cunn.lua'
	no file './cunn/init.lua'
	no file './lua/cunn.lua'
	no file './lua/cunn/init.lua'
	no file '/opt/zbstudio/lualibs/cunn/cunn.lua'
	no file '/opt/zbstudio/lualibs/cunn.lua'
	no file '/opt/zbstudio/bin/linux/x64/libcunn.so'
	no file '/opt/zbstudio/bin/linux/x64/clibs/cunn.so'
	no file './cunn.so'
	no file '/usr/local/lib/lua/5.1/cunn.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/opt/zbstudio/bin/linux/x64/libcunn.so'
	no file '/opt/zbstudio/bin/linux/x64/clibs/cunn.so'
stack traceback:
	[C]: in function 'require'
I need your help,thanks

**Comment by nicholas-leonard** [comment]
Try:
```lua
sudo luarocks install cutorch
sudo luarocks install cunn
```

**Comment by jiangfeng15** [comment]
when I run the script on the Zero Brane studio,It appear like this,but I test (require 'cunn') on the command window,it is ok.

**Comment by soumith** [comment]
open an issue on the zbs-torch repo
