### ISSUE TITLE
CmdLine: parsing boolean options impractical

### ISSUE THREAD

**Issue by mys007** [torch/torch7#149]
When parsing a command line, CmdLine interprets given boolean options as the negation of their default value. This is very annoying in the cases where one has fixed shell scripts controlling torch scripts and one fiddles around with default values in torch - the behaviour is then broken. I suggest that the special handling of boolean values in `CmdLine:__readOption__()` is dropped. In order to remain compatible with the current behaviour, there could be a "legacy" switch in `CmdLine:__init()` controlling this.

**Comment by soumith** [comment]
how do you propose it handled instead? with an explicit -opt true or -opt false?

**Comment by andresy** [comment]
please, no

**Comment by soumith** [comment]
@mys007 i suggest penlight's command-line interface for alternative behavior. I think we will keep the current boolean implementation in torch CmdLine

http://stevedonovan.github.io/Penlight/api/libraries/pl.lapp.html

**Comment by mys007** [comment]
Well, it could be also possible to follow GNU-style `-flag` and `-no-flag`. Afaik, penlight implements the same negating behavior as CmdLine, so I'll just stick with using numbers instead. Nevertheless, the current behavior of booleans should be documented in cmdline.md...

**Comment by soumith** [comment]
Fair enough, I'll document it in cmdline.md
thanks for the feedback.

**Comment by suryabhupa** [comment]
Is the -no-flag option implemented for negating a default true option?

**Comment by soumith** [comment]
@suryabhupa not in torch.CmdLine or pl.lapp

**Comment by suryabhupa** [comment]
Is this something that could be done or does it not fit well with the design/can be underspecified? I would be happy to try to implement it if it's something worthwhile.

**Comment by soumith** [comment]
@andresy would you be okay with the GNU-style `-flag` and `-no-flag` ?

**Comment by suryabhupa** [comment]
It might have an affect on backwards compatibility? I'm not actually sure if this is cleanly possible, or there might be another solution.
