### ISSUE TITLE
Torch on windows

### ISSUE THREAD

**Issue by stonebig** [torch/torch7#150]
Hi,

What is roughly needed work to have torch working also on windows ?

**Comment by mszlazak** [comment]
Yes! When is a Windows version coming out?

They say soon on the Torch7 website but what does that mean? 1 week, 1 month, 1 year.

Please folks,  get this out. I dying without it. Lol

**Comment by soumith** [comment]
@stonebig someone did compile the core stack for windows. See this for more details:
https://github.com/torch/luajit-rocks/pull/10

However, we do not plan to officially support torch on windows anytime soon.

**Comment by pkulchenko** [comment]
@stonebig, @mszlazak, I've compiled torch7 on Windows using mingw and the changes have been merged already (#287). I'd be interested to know if they work for you.

Note that the changes are only for the core repository (and not for any supporting tools).

**Comment by stonebig** [comment]
hi @pkulchenko,

Thank you.

For the moment I'm trying with python stack packages. I'll come back to Torch if I give up on this track.

**Comment by mszlazak** [comment]
Sorry. Don't use Windows anymore.

**Comment by Coderx7** [comment]
any new changes ?!

**Comment by mzeidhassan** [comment]
Any plans for a real Windows support?
