### ISSUE TITLE
nn.Reshape not reshaping leading dimensions of size 1

### ISSUE THREAD

**Issue by lacker** [torch/torch7#156]
The docs for Reshape say:

module = Reshape(dimension1, dimension2, ..)

Reshapes an nxpxqx.. Tensor into a dimension1xdimension2x... Tensor, taking the elements column-wise. 

However it appears to leave initial dimensions of size 1 unchanged.

    >>> nn.Reshape(6):forward(torch.Tensor(1, 2, 3)):size()
    1
    6
    [torch.LongStorage of size 2]

Is this a bug or is this intended behavior?

**Comment by nicholas-leonard** [comment]
Intended behaviour. Quoting the docs:

> The optional last argument batchMode, when true forces the first dimension of the input to be considered the batch dimension, and thus keep its size fixed. This is necessary when dealing with batch sizes of one. When false, it forces the entire input (including the first dimension) to be reshaped to the input size. Default batchMode=nil, which means that the module considers inputs with more elements than the produce of provided sizes, i.e. dimension1xdimension2x..., to be batches.

Use `nn.Reshape(8,false)`.

**Comment by lacker** [comment]
Oh, what docs should I be looking at? I don't see that paragraph on http://torch.cogbits.com/doc/nn/index.html#

**Comment by nicholas-leonard** [comment]
https://github.com/torch/nn/blob/master/doc/simple.md#nn.Reshape
