### ISSUE TITLE
File reading

### ISSUE THREAD

**Issue by ibmua** [torch/torch7#160]
``
[string] readString(format)
...
If no data is available, then an error is raised, except if File is in quiet() mode where it then returns nil.
..
``
No it doesn't. This is a misdocumentation. It returns '' - an empty string. But one can check through my_file:hasError() to find out if he had already hit this last empty string.

**Comment by nicholas-leonard** [comment]
Could you submit a PR to update the doc?

**Comment by ibmua** [comment]
Done.
