### ISSUE TITLE
Problems using th and iTorch from the very beginning

### ISSUE THREAD

**Issue by abria** [torch/torch7#162]
Hi all,

I am following the [Getting started with Torch](http://code.madbits.com/wiki/doku.php?id=tutorial_basics) tutorial but I am experiencing problems from the very beginning.

When I launch ```itorch```, whatever command I write (even the basic command ```require```), it complains about bad syntax. For instance:

```
[alessandro@localhost]$ itorch
Python 2.7.6 (default, Feb 20 2015, 17:19:50)
Type "copyright", "credits" or "license" for more information.

IPython 2.4.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

IPython profile: torch

In [1]: require 'image'
  File "<ipython-input-1-62061b945f94>", line 1
    require 'image'
                  ^
SyntaxError: invalid syntax
```

The same command works from ```th```. But when I try to display an image, I get a libjpeg error:

```
th> i=image.lena()
/usr/local/torch/share/lua/5.1/trepl/init.lua:319: /usr/local/torch/share/lua/5.1/luarocks/loader.lua:117: error loading module 'libjpeg' from file '/usr/local/torch/lib/lua/5.1/libjpeg.so':
        /usr/local/torch/lib/lua/5.1/libjpeg.so: undefined symbol: jpeg_mem_src
warning: <libjpeg> could not be loaded (is it installed?)
```

This is strange, because I do have a working libjpeg and libpng:
```
Package libjpeg-turbo-devel-1.2.1-3.el6_5.x86_64 already installed and latest version
Package 2:libpng-devel-1.2.49-1.el6_2.x86_64 already installed and latest version
```

So neither ```th``` nor ```itorch``` are working as expected, despite they have been built w/o problems.

I am running on CentOS 6.4.

Thank you in advance for your helpfulness.

**Comment by soumith** [comment]
hey there. We (Torch-7) do not officially support CentOS, even though many of us use it.

For bugs and issues with itorch, please open an issue here:
https://github.com/facebook/iTorch/issues
