### ISSUE TITLE
New docs hosted on readthedocs.org

### ISSUE THREAD

**Issue by nicholas-leonard** [torch/torch7#163]
Hi guys, 

Have been working with @soumith on making the docs look more professional. We decided to use readthedocs.org. Here is what the new docs could look like:

 * [torch docs](http://torch7.readthedocs.org/en/rtd/index.html)
 * [nn docs](http://nn.readthedocs.org/en/rtd/)

I should push some PRs to at least nn and torch in a weeks or so. Open to review, comments, etc.

**Comment by clementfarabet** [comment]
This is great!

**Comment by soumith** [comment]
ping ping! any update on this @nicholas-leonard ?

**Comment by nicholas-leonard** [comment]
I still need to update dok so that it is compatible with xhtml tags,
specifically `<a></a>` instead of `<a/>`.

Nicholas Léonard
450-210-1214
