### ISSUE TITLE
bad rng with cutorch.manualSeed()

### ISSUE THREAD

**Issue by bjaros** [torch/torch7#167]
The following code generates the same tiny number for every value beyond column 96.

```lua
require "cutorch"

dims = 256
cutorch.manualSeed(1)
torch.setdefaulttensortype("torch.CudaTensor")
tmp = torch.zeros(1, 1):uniform()
noise = torch.rand(1,dims)
print(noise)
```

Output:
```
Columns 1 to 6
 8.9963e-01  7.7519e-01  9.3784e-01  8.8920e-01  1.3110e-01  2.0172e-01

[...]

Columns 241 to 246
 1.1642e-10  1.1642e-10  1.1642e-10  1.1642e-10  1.1642e-10  1.1642e-10

Columns 247 to 252
 1.1642e-10  1.1642e-10  1.1642e-10  1.1642e-10  1.1642e-10  1.1642e-10

Columns 253 to 256
 1.1642e-10  1.1642e-10  1.1642e-10  1.1642e-10
```

Bug goes away without cutorch.manualSeed(), and/or without that call to uniform().

If I make some calls to rand() in between runs, I'll occasionally get the proper behavior on the initial run -- but not on repeated runs.

**Comment by dominikgrewe** [comment]
I can confirm the issue. It seems like sometimes the call to `rand` has no effect at all. The tensor just stays uninitialised. If you change the `tmp` tensor to size 256, the problem seems to go away...
I'll look into it.

**Comment by dominikgrewe** [comment]
Resetting the MTGP32 constants in manualSeed seems to solve the issue of getting bogus numbers.

I noticed, though, that the output wasn't deterministic any more. It seems that generating N numbers with N not a multiple of 256 (the block size we use) messes up the cuRAND state. If we always generate multiples of 256 numbers (and discarding the ones not needed), it seems to work.

I've created a pull request for cutorch: https://github.com/torch/cutorch/pull/116
Can you please try it and see it this fixes your problems?

**Comment by bobbyjaros** [comment]
Confirming that this passes my test.  Thanks @dominikgrewe!
