### ISSUE TITLE
one over X function

### ISSUE THREAD

**Issue by soumith** [torch/torch7#168]
A useful function to have would be 1/x of a tensor (in-place and out-of-place).

**Comment by andresy** [comment]
yes, it is on my todo list

**Comment by AjayTalati** [comment]
That would be really cool !!! 

Here's a concrete example of what I guess people want to do more efficiently 

`one_over_Z = torch.cdiv(torch.ones(N) , Z)`

If you can please post [here](https://groups.google.com/forum/#!topic/torch7/R_PA1Cnu6QA) when this is implemented.

Kind regards, Aj

**Comment by nicholas-leonard** [comment]
`a:pow(-1)`?

**Comment by andresy** [comment]
yes, that is what i do for now

**Comment by hughperkins** [comment]
`:inv()`?

**Comment by hughperkins** [comment]
Following Jonathan Tomson's advice, changing to `:cinv()`

**Comment by soumith** [comment]
Merged into trunk!
