### ISSUE TITLE
cannot download packages using luarocks

### ISSUE THREAD

**Issue by thomaswangyiwen** [torch/torch7#169]
I tried luarocks in the terminal:
$ luarocks install image

but it said this:
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/torch/rocks/master - Failed downloading https://raw.githubusercontent.com/torch/rocks/master/manifest
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master - Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/manifest

Error: No results matching query were found.

How can I get rid of this problem? Thanks!

**Comment by soumith** [comment]
sudo rm -rf ~/.cache/luarocks

Then try again.

**Comment by thomaswangyiwen** [comment]
Thanks. Problem solved.

**Comment by thomaswangyiwen** [comment]
Thanks. Problem solved.

**Comment by ashwinnair14** [comment]
Hi,
Running into the same problem.
already tried the sudo rm -rf ~/.cache/luarocks and tried again.
And still get the same error. @soumith 

I'm running the torch7 on a ubuntu 14.04 LTS pc behind a proxy. I have already made environment variables Http_proxy and proxy.

The default options for wget and curl and git has been set to run via this proxy. here are the steps I used to change the settings of the packages of [Wget proxy](http://stackoverflow.com/questions/11211705/setting-proxy-in-wget), [Curl proxy](http://stackoverflow.com/questions/7559103/how-to-setup-curl-to-permanently-use-a-proxy) & [git proxy](http://stackoverflow.com/questions/783811/getting-git-to-work-with-a-proxy-server)

The env variables are available in my .bashrc and /etc/enviornmentfiles.

I have also added the proxy in the config.lua file as per [this](https://github.com/keplerproject/luarocks/wiki/LuaRocks-through-a-proxy) post as well.

The error I get when i try to install this is

```
$sudo luarocks install cunn
Warning: Failed searching manifest: Failed loading manifest: 
Failed fetching manifest for http://luarocks.org/repositories/rocks 
- Error fetching file: Failed downloading 
http://luarocks.org/repositories/rocks/manifest


Error: No results matching query were found.
```

**Comment by ranka47** [comment]
I am trying to download qtlua and facing the same issue: 
`sudo luarocks install qtlua`
`Warning: Failed searching manifest: Failed fetching manifest for https://luarocks.org - Failed downloading https://luarocks.org/manifest - /home/ubuntu/.cache/luarocks/https___luarocks.org/manifest`

**Comment by RudyQ** [comment]
In my case,  the following code solved the problem. In ubuntu 16.04
sudo rm -rf ~/.luarocks

**Comment by vegerot** [comment]
@RudyQ Don't have that directory
