### ISSUE TITLE
Lua can't find Torch

### ISSUE THREAD

**Issue by AKstatistics** [torch/torch7#172]
I installed torch yesterday following the instruction on torch.ch
th successfully launches the torch environment but when I go into the Lua environment and try to require torch I get the following error.

    Adam-Levys-MacBook-Pro:~ adamlevy$ lua
    Lua 5.3.0  Copyright (C) 1994-2015 Lua.org, PUC-Rio
    \> require 'torch'
    stdin:1: module 'torch' not found:
        no field package.preload['torch']
        no file '/usr/local/share/lua/5.3/torch.lua'
        no file '/usr/local/share/lua/5.3/torch/init.lua'
        no file '/usr/local/lib/lua/5.3/torch.lua'
        no file '/usr/local/lib/lua/5.3/torch/init.lua'
        no file './torch.lua'
        no file './torch/init.lua'
        no file '/usr/local/lib/lua/5.3/torch.so'
        no file '/usr/local/lib/lua/5.3/loadall.so'
        no file './torch.so'
    stack traceback:
        [C]: in function 'require'
        stdin:1: in main chunk
        [C]: in ?

How do I get Lua to find the torch package?

**Comment by soumith** [comment]
we only support the lua we ship with (which is likely called luajit).

**Comment by nk0307** [comment]
hey i have the same problem. it is like this:
qian@ubuntu-14:~/workspace/DeepDeblur_release/code$ qlua -i demo.lua -load -save release_scale3_adv_gamma -blur_type gamma2.2
qlua: demo.lua:4: module 'torch' not found:
	no field package.preload['torch']
	no file '/home/qian/.luarocks/share/lua/5.1/torch.lua'
	no file '/home/qian/.luarocks/share/lua/5.1/torch/init.lua'
	no file '/home/qian/torch/install/share/lua/5.1/torch.lua'
	no file '/home/qian/torch/install/share/lua/5.1/torch/init.lua'
	no file './torch.lua'
	no file '/home/qian/torch/install/share/luajit-2.1.0-beta1/torch.lua'
	no file '/usr/local/share/lua/5.1/torch.lua'
	no file '/usr/local/share/lua/5.1/torch/init.lua'
	no file '/home/qian/torch/install/lib/torch.so'
	no file '/home/qian/.luarocks/lib/lua/5.1/torch.so'
	no file '/home/qian/torch/install/lib/lua/5.1/torch.so'
	no file './torch.so'
	no file '/usr/local/lib/lua/5.1/torch.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: at 0x7fb546b209c0
	[C]: in function 'require'
	demo.lua:4: in main chunk

I think this might br a bug of this package?
