### ISSUE TITLE
Running Torch7 as an HTTP/ API server

### ISSUE THREAD

**Issue by grzesir** [torch/torch7#186]
Hey guys,

Excellent job on Torch! Great library and very easy to use.

We would like to set up Torch7 to accept GET/ POST requests from an application to execute Lua scripts. For example if we have a set of images that we want to add to our training data, or to use it perform NLP calculations on text. Is it possible to turn Torch7 into an HTTP/ JSON server?

**Comment by soumith** [comment]
Hey @grzesir , the answer is yes and we've done this multiple times in the past.
Look at the async package (it's tests serve also as examples).
https://github.com/clementfarabet/async

**Comment by soumith** [comment]
also an Express-like framework on top of async: https://github.com/benglard/waffle

**Comment by ibmua** [comment]
It would be very helpful if there was a real example of, say, HTTP POST'ed base64 image being processed by 'async' into a Tensor. So far I've tried hard making all sorts of different Lua servers work, but none could do anything like that. It's one thing if you've made that Lua module yourself and know it all the way through. Other people have no idea what to do with it.
