### ISSUE TITLE
nn.SelectTable:type() overrides Model:type() and leaves some fields with the wrong type.

### ISSUE THREAD

**Issue by francisr** [torch/torch7#190]
In https://github.com/torch/nn/blob/master/SelectTable.lua, Model:type() is overriden:
```Lua
function SelectTable:type(type)
  self.gradInput = {}
end
```
However, SelectTable has other fields: output and _type, which should be changed by this function.
Proposed fix: add `return parent.type(self,type)` before the end of the function.
`parent:type(type)` doesn't work, because the `self` that is used in this call does not contain the attributes of SelectTable.
`return` should probably be added because it is done like this in the other :type() functions.

**Comment by nicholas-leonard** [comment]
Can you submit a Pull Request to torch/nn?

**Comment by soumith** [comment]
closed via https://github.com/torch/nn/pull/218
