### ISSUE TITLE
THRandom_isValidState

### ISSUE THREAD

**Issue by andresy** [torch/torch7#194]
@GeorgOstrovski I believe you introduced THRandom_isValidState.

However:
- at THRandom.c:181 you have a comparison of an unsigned with >= 0 which generates a warning
- THTensorRandom uses it a line 232, but there is no declaration of the function so another warning is also generated.

Could you fix it?
Thanks

**Comment by GeorgOstrovski** [comment]
Both issues are addressed in my (open) PR #184 .

**Comment by andresy** [comment]
ach, yes,  :+1:
