### ISSUE TITLE
torch.symeig fails when resv is not contiguous

### ISSUE THREAD

**Issue by gdesjardins** [torch/torch7#208]
torch.symeig currently fails to properly handle non-contiguous storage for `resv`. This is especially problematic as the in-out value `resv` becomes non-contiguous after the call to torch.symeig (and so consecutive calls to torch.symeig fail). This is highlighted in the unit-test below.

Additionally, it appears that the torch documentation is incorrect. Given the decomposition A = V' diag(e) V, torch.symeig is described as returning V in `resv`. This would mean that the eigenvectors are stored as rows of `resv. However, from the code below, we can see that they are stored as columns.

```
require 'totem'
local tester = totem.Tester()
local test = {}

function test.test_symeig()
  local xval = torch.rand(100,3)
  local cov = torch.mm(xval:t(), xval)
  local rese = torch.zeros(3)
  local resv = torch.zeros(3,3)

  -- First call to symeig
  tester:assert(resv:isContiguous()) -- PASS
  torch.symeig(rese, resv, cov:clone(), 'V')
  local ahat = torch.mm(torch.mm(resv, torch.diag(rese)), resv:t())
  tester:assertTensorEq(cov, ahat, 1e-8) -- PASS

  -- Second call to symeig
  tester:assert(resv:isContiguous()) -- FAIL
  torch.symeig(rese, resv, cov:clone(), 'V')
  local ahat = torch.mm(torch.mm(resv, torch.diag(rese)), resv:t())
  tester:assertTensorEq(cov, ahat, 1e-8) -- FAIL
end

tester:add(test)
tester:run()
```

**Comment by soumith** [comment]
Would one of the LAPACK geniuses look at this, @koraykv ?

**Comment by koraykv** [comment]
I will look into this.
