### ISSUE TITLE
doc for: torch.randperm 

### ISSUE THREAD

**Issue by ameenetemady** [torch/torch7#220]
not high priority, but I wasted some time, figuring this out, so ...:
The second argument to torch.randperm, is the type of output variable (e.g. 'torch.LongTensor'), it's worth mentioning it in the documentation (torch7/blob/master/doc/maths.md). I faced this while debugging nn.StochasticGradient:train
Also a question, I couldn't find the source of torch.randperm, how/where can I find it?

I'm a newbie to torch, excuse me if this is too dumb
Thanks,
Ameen.

**Comment by soumith** [comment]
@ameenetemady The second argument is not designed to be there, it is really a mere accident of our wrappers. What is the issue you faced with nn.StochasticGradient:train? I am happy to fix the underlying issue if needed.

The code for torch.randperm is here:
(1) The wrapper to the C library (using torch/cwrap):
https://github.com/torch/torch7/blob/master/TensorMath.lua#L461

(2) The actual C code:
https://github.com/torch/torch7/blob/master/lib/TH/generic/THTensorMath.c#L1031

**Comment by ameenetemady** [comment]
Thanks for the pointers. My issue was that, I didn't know the "train" doesn't take Tensor, and takes a "table" instead. I was getting the following error when I gave it a tensor (n by 3):
"/usr/local/bin/luajit: expected arguments: [*DoubleTensor*] [Generator] long"

**Comment by soumith** [comment]
oh ok. yes train takes a table with defined length and index operators (table has defaults, but you can go fancy by setting your own functions in the metatable of the table).

http://www.lua.org/pil/13.4.1.html

**Comment by ameenetemady** [comment]
I see. thanks for the quick and informative response. Also, a guard for a better error regarding the type of the parameter, could be useful. Cheers.
