### ISSUE TITLE
config = config or {...} paradigm does not seem to work

### ISSUE THREAD

**Issue by lelikchern** [torch/torch7#224]
The paradigm used in many demos and tutorials for specifying parameters for SGD or other optimization methods does not seem to work. Example on my machine (first line after starting Trepl):

th> config
{
  read : function: 0x411f8840
  lines : function: 0x40db4fc8
}
th> config = config or {learningRate = 0.01}

th> config
{
  read : function: 0x411f8840
  lines : function: 0x40db4fc8
}
So apparently this had no effect?

This explicit approach works:

th> config.learningRate = 0.01

th> config
{
  read : function: 0x411f8840
  lines : function: 0x40db4fc8
  learningRate : 0.01
}

I noticed that if I run "th -g" for running global monitoring, then the "config" variable is not created and so the config = config or {} paradigm works as intended.

**Comment by szagoruyko** [comment]
config and lapp are automatically created by penlight https://github.com/stevedonovan/Penlight
I'd say the names in demos have to be changed from "config" to something else

**Comment by soumith** [comment]
good catch. opened an issue in the demos repository.
