### ISSUE TITLE
model:forward() cause 'Illegal Instruction' in docker container on VM.

### ISSUE THREAD

**Issue by kai-zhong** [torch/torch7#226]
Use boot2docker to run docker daemon in both Mac and Windows. Install Torch7 by docker image ([abhishekkr/ml-torch](https://www.google.com/url?q=https%3A%2F%2Fregistry.hub.docker.com%2Fu%2Fabhishekkr%2Fml-torch%2F&sa=D&sntz=1&usg=AFQjCNHoNwd5FSkkHPyWLWuqbVRrM_3tUA)).  Run script of [Machine Learning with Torch7](http://www.google.com/url?q=http%3A%2F%2Fcode.madbits.com%2Fwiki%2Fdoku.php%3Fid%3Dtutorial_supervised&sa=D&sntz=1&usg=AFQjCNGuxFZ896gK-x3DWijGtIGZ8VUxKw).  'Illegal Instruction' will occur. Somebody also encounter this issue?

**Comment by soumith** [comment]
@kai-zhong this seems to be an issue with LuaJIT 2.1 and Virtual machines. A good start would be to post to the LuaJIT mailing list. Alternatively, installing torch with LuaJIT 2.0, by changing this line:
https://github.com/torch/distro/blob/master/install.sh#L49 to have -DWITH_LUAJIT21=OFF

**Comment by nhynes** [comment]
If anyone else runs into this issue in the future, the issue is that the machine that built the image--and compiled Torch--has a different CPU architecture than the one running the image.
