### ISSUE TITLE
nn.Sigmoid.updateGradInput calculation is wrong ?

### ISSUE THREAD

**Issue by YoannDupont** [torch/torch7#232]
Greetings,

Examples given for reproductivity sake. I think I found a bug nn.Sigmoid updateGradInput. I was trying to check results of a Sigmoid I was computing, comparing it with Torch's one...

As proven by prof Andrew Ng, Sigmoid'(x) = Sigmoid(x) * (1 - Sigmoid(x))

```lua
require 'nn'

sigmoid = nn.Sigmoid()

function S(x)  return 1 / (1 + math.exp(-x)) end
function dS(x) return 1 * (1 - x)            end -- where x = S(y)

x = torch.Tensor({0.2023, 0.6568, 0.8668, 0.7191, 0.7968}) -- was result of torch.rand(5)
print(x)
-- 0.2023
-- 0.6568
-- 0.8668
-- 0.7191
-- 0.7968
--[torch.DoubleTensor of dimension 5]

y = x:clone()
y:apply(S)
print(y)
-- 0.5504
-- 0.6585
-- 0.7041
-- 0.6724
-- 0.6893
--[torch.DoubleTensor of dimension 5]

sf = sigmoid:forward(x)
print(sf)
-- 0.5504
-- 0.6585
-- 0.7041
-- 0.6724
-- 0.6893
--[torch.DoubleTensor of dimension 5]

z = y:clone()
z:apply(dS)
print(z)
-- 0.2475
-- 0.2249
-- 0.2084
-- 0.2203
-- 0.2142
--[torch.DoubleTensor of dimension 5]

sb = sigmoid:backward(x, sf)
print(sb)
-- 0.1362
-- 0.1481
-- 0.1467
-- 0.1481
-- 0.1476
--[torch.DoubleTensor of dimension 5]
```

The results are different ! Using the last graph at http://kawahara.ca/how-to-compute-the-derivative-of-a-sigmoid-function-fully-worked-example/ I checked dS(0), which returns 0.25:

```lua
x = torch.Tensor({0})
y = x:clone()
y:apply(S)
print(y)
-- 0.5000
--[torch.DoubleTensor of dimension 1]
z = y:clone()
z:apply(dS)
print(z)
-- 0.2500
--[torch.DoubleTensor of dimension 1]
```

And now with nn.Sigmoid:

```lua
sigmoid = nn.Sigmoid()
sf = sigmoid:forward(x)
print(sf)
-- 0.5000
--[torch.DoubleTensor of dimension 1]
sb = sigmoid:backward(x, sf)
print (sb)
-- 0.1250
--[torch.DoubleTensor of dimension 1]
```

Ok, so now we have some proof that Torch is wrong. Here is the C code for nn.Sigmoid.updateGradInput:

```C
static int nn_(Sigmoid_updateGradInput)(lua_State *L)
{
  THTensor *gradOutput = luaT_checkudata(L, 3, torch_Tensor);
  THTensor *output = luaT_getfieldcheckudata(L, 1, "output", torch_Tensor);
  THTensor *gradInput = luaT_getfieldcheckudata(L, 1, "gradInput", torch_Tensor);

  THTensor_(resizeAs)(gradInput, output);
  TH_TENSOR_APPLY3(real, gradInput, real, gradOutput, real, output, \
                   real z = *output_data; \
                   *gradInput_data = *gradOutput_data * (1. - z) * z;)
  return 1;
}
```
See in TH_TENSOR_APPLY3 ?

```C
*gradInput_data = *gradOutput_data * (1. - z) * z;
```

The Sigmoid output is multiplied twice (*gradOutput_data == z). Proof:

```lua
function dS(x) return x * x * (1 - x) end
z = y:clone()
z:apply(dS)
print(z)
-- 0.1250
--[torch.DoubleTensor of dimension 1]
```

The fix should be quite easy I guess :)

Best regards,

**Comment by GeorgOstrovski** [comment]
I believe you are misunderstanding the meaning of the second argument to module:backward. Its second argument is the output gradient (coming from, say, gradient of the error function applied to the output, or the backpropagated gradient from modules stacked on top of module). 

backward effectively implements the chain rule: Say you have a function F(x) =  f(g(x)), where g(x) = sigmoid(x) = 1 / (1 + exp(-x)).  Then by the chain rule, (dF / dx) (z) = (df/dy) (g(z)) * (dg/dx)(x). 
As you said, (dg/dx)(x) = sigmoid(x) (1-sigmoid(x)), where x is the input to your module. However to compute the correct gradient of F, you need to multiply this by (df/dy)(g(z)), which is what the second argument to backward is supposed to be.

Try the following:
```lua
sig = nn.Sigmoid()
x = torch.Tensor{0}
dO = torch.Tensor{1}
y = sig:forward(x)
-- 0.5 = sigmoid(0)
dI = sig:backward(x,dO)
-- 0.25 = (dSigmoid/dx)(0) * 1
```

**Comment by YoannDupont** [comment]
I just knew I was doing something so very wrong ! I mislead myself trying to do the simplest test possible...

Thanks for the explanation, I will hide myself now :)
