### ISSUE TITLE
Install torch in local directory

### ISSUE THREAD

**Issue by arashno** [torch/torch7#233]
Hello all.
I want to install torch7 with MKL and GPU support in my local directory on a cluster environment.
The cluster has MKL and CUDA libraries but they have been installed in a different directory rather than the default one.
How can I install torch, cutorch and cunn using the installed libraries.
Is there any document to help me about my issue?
Thanks

**Comment by soumith** [comment]
hey @arashno , you can hint to cmake with the paths via the environment variable:
CMAKE_LIBRARY_PATH and CMAKE_INCLUDE_PATH

For example:
https://github.com/torch/distro/blob/master/install.sh#L34

Reference:
http://www.cmake.org/Wiki/CMake_Useful_Variables#Environment_Variables
