### ISSUE TITLE
Torch on Cuda 6.5

### ISSUE THREAD

**Issue by ArunAniyan** [torch/torch7#242]
Hi ,

Anyway to install CuTorch with Cuda 6.5

Cheers,
A

**Comment by soumith** [comment]
@ArunAniyan if you want to be a tad more helpful, specify the issue you are having, rather than the vague issue that no one is sure how to answer. We're all on Cuda 7/6.5 and we've installed torch smoothly.

Also, for install issues, use the forum 
https://groups.google.com/forum/#!forum/torch7
