### ISSUE TITLE
torch failure after reinstallation

### ISSUE THREAD

**Issue by uricohen** [torch/torch7#243]
I have run ./install.sh in existing torch installation to solve a different problem and now loading cudnn fails:

    th> require("cudnn")
    /home/users/uri.cohen/torch/install/bin/luajit: symbol lookup error: /home/users/uri.cohen/.luarocks/lib/lua/5.1/libcutorch.so: undefined symbol: THCState_getDeviceMode

Reinstalling related modules didn't solve it:

     luarocks install cutorch
     luarocks install cunn
     luarocks install cudnn

Any ideas which module may take the blame? Thanks!

**Comment by soumith** [comment]
you seem to have a --local installed copy of cutorch (installed with luarocks install --local cutorch).

I suggest removing the ~/.luarocks directory.

**Comment by uricohen** [comment]
Exactly! Thanks.

**Comment by ArghyaPal** [comment]
Hi @soumith I am getting the following error:

`th> require "cunn"
/home/arghya/torch/install/bin/luajit: symbol lookup error: /home/arghya/torch/install/lib/libTHC.so: undefined symbol: _ZNSt13random_device7_M_initERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
`

I did:
1. rm -rf ~/.cache/luarocks.
2. Even a fresh re-installation

So, presently I am trying to install it on a GPU Server. When, I tried with another account (a fresh account), I got the same error.

Is that a path/library linking problem?

Regards,
Arghya
