### ISSUE TITLE
luarocks fails to download

### ISSUE THREAD

**Issue by ganarajpr** [torch/torch7#250]
Error seen on screen.

```
luarocks install nn
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/torch/rocks/master - Failed downloading https://raw.githubusercontent.com/torch/rocks/master/manifest
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master - Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/manifest

Error: No results matching query were found.
```
This is after a fresh install of torch. 
```
luarocks --version
/home/ganaraj/torch/install/bin/luarocks 2.2.0beta1
LuaRocks main command-line interface
```

**Comment by soumith** [comment]
github was probably down, or you seem to not have access to this URL from your machine/server:
https://raw.githubusercontent.com/torch/rocks/master/manifest

**Comment by dendisuhubdy** [comment]
yeah I got this message too

ubuntu@ip-172-31-8-200:~/torch$ luarocks install loadcaffe
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/torch/rocks/master - Failed downloading https://raw.githubusercontent.com/torch/rocks/master/manifest
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master - Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/manifest

Error: No results matching query were found.

**Comment by kobikun** [comment]
my case, there is reason on wget's timeout option of luarocks
so i tried and solve the problem using command below
$ luarocks install nn --timeout=0

**Comment by rzai** [comment]
rzai@rzai00:~/torch$ luarocks install nn --timeout=0
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/torch/rocks/master - Failed downloading https://raw.githubusercontent.com/torch/rocks/master/manifest - /home/rzai/.cache/luarocks/https___raw.githubusercontent.com_torch_rocks_master/manifest
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master - Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/manifest - /home/rzai/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moonrocks-mirror_master/manifest

Error: No results matching query were found.
rzai@rzai00:~/torch$
