### ISSUE TITLE
Link to mailing-list on Contributions page seems broken?

### ISSUE THREAD

**Issue by hughperkins** [torch/torch7#251]
Link to mailing-list on Contributions page seems broken?

https://github.com/torch/torch7/blob/master/CONTRIBUTING.md

Points to: https://github.com/torch/torch7/blob/master/groups.google.com/forum/#!forum/torch7

I googled a bit, and found a mailinglist on sf.net, which I almost subscribed to, but seems to be some kind of medical monitoring software instead :-P

I suppose the url should be http://groups.google.com/forum/#!forum/torch7 ?

**Comment by soumith** [comment]
thanks, fixed now :)
