### ISSUE TITLE
THDiskFile write error

### ISSUE THREAD

**Issue by russellfei** [torch/torch7#256]
Hi, all

Something unexpected occurs at `torch.save`

```
The matrix layout for torch.save
    4
 6150
 8250
[torch.LongStorage of size 3]

Error traceback
.torch/install/bin/luajit: ....torch/install/share/lua/5.1/torch/File.lua:157: write error: wrote 494 blocks instead of 202950000 at /home/russellfei/.torch/pkg/torch/lib/TH/THDiskFile.c:314
```

What's wrong with `THDiskFile`?

Regards,
rus

**Comment by andresy** [comment]
most like you are running out of disk space

**Comment by russellfei** [comment]
Hi, @andresy
I was concerned about that as `th` is running in a virtual machine with 4G RAM, but things doesn't change after I raise RAM amount to 8G.
Also, to avoid virtual disk usage, I perform this operation on mapped volumes outside that virtual machine which is free from space shortage.

I'll change to another machine to test this. =]

**Comment by russellfei** [comment]
@andresy 
I transformed loaded `DoubleTensor` to `IntTensor` and it succeeds.
Quite weird, `IntTensor` is 800M, and according to `Double` is 2x or 4x to `Int`,
maybe I came across the `2G limit` of luajit, is that true?

**Comment by andresy** [comment]
no, the 2G limit applies only to lua objects (and tensors are C objects)

**Comment by russellfei** [comment]
@andresy 
Oh, that's true! 
Then there's a slippery bug inside `DiskFile`, quite curious about the specific pesticide =]
Thankfully, that matrix is `Int` value in itself.

Thanks @andresy

**Comment by TyPetrochko** [comment]
How did you fix this?

**Comment by cjmcmurtrie** [comment]
How did you fix this error? I've run into the same problem on an Ubuntu virtual machine with 60GB ram and 41GB hard drive. My model has 1.6 million parameters - I can't imagine 41GB is not enough to save it.

**Comment by adamlerer** [comment]
Can you post code to reproduce, and the error message you see?

**Comment by cjmcmurtrie** [comment]
I think I found the problem. Storing a table (containing some other tables as well as a torch tensor) threw the error. When I only saved the tensor (not inside a table) it was fine.

**Comment by adamlerer** [comment]
Oh okay. Yes, if you store a table with many (millions of) elements with
luajit, you will run out of lua memory.
