### ISSUE TITLE
sum() missing from `doc/maths.md`?

### ISSUE THREAD

**Issue by hughperkins** [torch/torch7#257]
sumall() missing from `doc/maths.md`?

There's an example that uses it, but never actually seems to be explcitly described?

**Comment by hughperkins** [comment]
Oh, maybe it is called 'sum' in fact, and is in the `Column or row-wise operations  (dimension-wise operations)` section

**Comment by hughperkins** [comment]
Still, I could never find it when I searched.  Maybe I just suck at searching doc, but maybe it could be worth referencing it in the 'matrix-wide' section somehow? At least, linking to the column or row-wise descipriton perhaps?

**Comment by soumith** [comment]
sumall is an overloaded operator on :sum() when you don't specify the dimension.
it is overloaded using cwrap over here:
https://github.com/torch/torch7/blob/master/TensorMath.lua#L431
