### ISSUE TITLE
Missing `size` from the doc?

### ISSUE THREAD

**Issue by hughperkins** [torch/torch7#259]
Missing `size` from the doc?  ie, from https://github.com/torch/torch7/blob/master/doc/maths.md  But maybe it is on a differnet page?

**Comment by soumith** [comment]
it's in tensor.md

**Comment by hughperkins** [comment]
Hmmm, right.

**Comment by hughperkins** [comment]
Oh, wow, theres a ton of methods there that I hadnt seen before :-P

**Comment by hughperkins** [comment]
Like, hmmm, `:t()` :-P

**Comment by soumith** [comment]
i think it's a good idea for you to read the whole docs once. they're not too long. maths.md is the longest and you've covered it pretty well.

**Comment by hughperkins** [comment]
:-)

**Comment by hughperkins** [comment]
I've restructured the readme, to show what's working by 'storage.md', 'tensor.md', and 'maths.md'.  Are there any other fucntions that are fundamental to being able to use cltorch usefullly?

**Comment by soumith** [comment]
The rng functions like :uniform() or :normal() to quickly initialize a
random tensor. They are documented in random.md

**Comment by hughperkins** [comment]
Ok.  Thanks!

**Comment by hughperkins** [comment]
(By the way, note that I'm mostly just targeting the operators used in `nn`, ie https://github.com/hughperkins/cltorch/blob/master/doc/torch/nn-operators.md , just that some things came 'for free', eg to do per-element add, need Apply, which was a huge amount of work, but once Apply worked, then basically abs, sqrt, etc all came 'for free' :-) )

**Comment by soumith** [comment]
It's actually very cool. I saw that your initial project was just clnn, but
in the process, you're building what currently simply does but exist, a
good, performant tensor library for opencl that works for arbitrary
dimensional tensors, and has a powerful set of operators defined. The
existing ones are either limited in dimensionality (like arrayfire which is
restricted to 4d tensors) or limited in the feature set (only half of the
cpu api implemented etc.)

**Comment by hughperkins** [comment]
"you're building what currently simply does but exist, a good, performant tensor library for opencl that works for arbitrary dimensional tensors, and has a powerful set of operators defined"

Haha, for a definition of 'building' meaning 'copying and replacing Cuda with Cl' :-P

Nice encouragement, thanks! :-)

(By the way, seems like the Tensors.md page has a whole bunch of 'freebies' too.  Almost everything in 'Querying size and structure', and 'extracting sub-tensors' 'just works', with hardly any further development, and no further kernels.  There's some kernels for the indexing stuff, but that's a small proportion it seems.)
