### ISSUE TITLE
Tester class: 'expect_eq' syntax?

### ISSUE THREAD

**Issue by hughperkins** [torch/torch7#263]
Googletest framework has methods such as 'expect_eq', which fail the test if they fail, but let the test keep running anyway.  These are quite useful. Possible to add these?

**Comment by soumith** [comment]
There's a slightly more powerful tester class called totem, by google
deepmind. Would that serve your purpose better?

https://github.com/deepmind/torch-totem

**Comment by hughperkins** [comment]
Thanks! Will take a look :-)
