### ISSUE TITLE
add_library cannot create imported target "TH"

### ISSUE THREAD

**Issue by semisight** [torch/torch7#270]
I'm working on integrating torch into another machine learning package (DIGITS). I've been running into an error when trying to install cutorch after making and installing torch:

```
CMake Error at /home/travis/build/semisight/DIGITS/deps/torch/distro/install/share/cmake/torch/TorchExports.cmake:16 (ADD_LIBRARY):
  add_library cannot create imported target "TH" because another target with
  the same name already exists.
```

My code is [here](https://github.com/semisight/DIGITS), with the torch install script [here](https://github.com/semisight/DIGITS/blob/torch-travis/scripts/travis/install-torch.sh), and my travis output is [here](https://travis-ci.org/semisight/DIGITS/builds/68501193). (Note: the travis output is long, you'll have to open the raw log).

Am I misunderstanding how to install these packages? It appears there's some duplication here but I can't figure out where.

**Comment by soumith** [comment]
that's a weird error. the distro script approximately does the same thing to install torch, with the same commands as your script, and that passes just fine:

https://github.com/torch/distro/blob/master/install.sh

**Comment by soumith** [comment]
I'm also not able to replicate the error.

**Comment by LijieTu** [comment]
@semisight I got the same error when I installed cutorch package on a red hat server. Do you now have any idea what goes wrong? Many thanks!

**Comment by hughperkins** [comment]
@LijieTu Perhaps you can double-check that your DIGITS package is not exporting a target called TH?  By the way, what it means by exporting a target is that your CMakeLists.txt, or any of your included CMakeModules/xxx.cmake modules contains a line something like:
```
add_library(TH ....)
add_executable(TH ...)
add_library(TH SHARED IMPORTED)
```
Somehow, there are two such lines for 'TH'.

**Comment by hughperkins** [comment]
Hmmm, seems you dont have a CMakeLists.txt?  Thats odd...

**Comment by hughperkins** [comment]
Anyway, I think you need to build using the standard torch distro manual method, and use that for getting the build working.  Once that's working, you can compare what you're doing when you do it manually with your travis script perhaps?

**Comment by LijieTu** [comment]
@hughperkins Thanks for your reply!
Yes, I used the standard method to install the torch.
I just find that once I use "module add cmake" before installation, the problem could be solved neatly.

**Comment by soumith** [comment]
The contbuild shows that cutorch was balking. @szaguroyko fixed this today in a PR on cutorch: https://github.com/torch/cutorch/pull/196

Apparently this was an issue only on older systems.
