### ISSUE TITLE
Sparse input : Bag of word

### ISSUE THREAD

**Issue by pakdaman** [torch/torch7#273]
Hi,

I am pretty newbie to torch. I have bag of words(BOW) representation and I am looking for a sparse input module that accepts BOW. Does torch support sparse input? I know there is a SparseLinear Module (https://github.com/torch/nn/blob/master/doc/simple.md#nn.SparseLinear) 
but there is two problems with that:

1- there is no sample code how to use it inside a Neural Net(NN)
2- I read in a forum that it is compatible CUDA modules. So I will not be able to run the final code on GPU :(

Also I noticed that there is some spaghetti module (https://github.com/MichaelMathieu/lua---spaghetti) too, but I could not find a sample code of using that inside an NN 

I assume that BOW is the most commonly used representation in NLP and there should be some way that I can present my sparse data to NN in torch!

Thanks,
Mahdi

**Comment by pakdaman** [comment]
OK. I found out what is the problem with my usage of SparseLinear:  The input format for a classification task  with K classes should be a table in which the i'th entry has the following format:
 
data[i] =  
{
  1 : DoubleTensor - size: 57x2    
-- sparse Representation of feature vector as a Double Tensor of (key,value) 

  2 : ByteTensor - size: 1
-- The associated class of the instance 
}

The only point that I was missing was that I should have defined a size() function for the data table since inside the Sparse_linear module the size() function will be called. So one should define:

function data:size() return data_size end
               
where data_size will be the size of train data inside the "data" table

Any way, I have still the problem of what should I do if I am going to use GPU for running my code since it seems SparseLinear is not provided inside cunn.
Any advice ?

Thanks,
Mahdi

**Comment by francisr** [comment]
Instead of using a SparseLinear layer your can use a LookupTable. 
It associates a number with a feature vector, so if you have M vectors, and you want F features for your vectors, the weight tensor inside the lookup table is a toch.Tensor(M, F).
This is equivalent to have a vector of size M with a single non zero value at 1 followed by a matrix multiply of size F x M.

**Comment by pakdaman** [comment]
Thank you though. Please let me know if you had any other idea.

**Comment by soumith** [comment]
the right place for asking such questions is the google groups: 
https://groups.google.com/forum/#!forum/torch7

**Comment by pakdaman** [comment]
Thanks for letting me know.

Mahdi
