### ISSUE TITLE
Failed to install without root permission

### ISSUE THREAD

**Issue by iwinux** [torch/torch7#276]
I'm tring to install torch to a user directory with command `luarocks install --tree contrib --server https://raw.githubusercontent.com/torch/rocks/master torch`, but get the following error:

```
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:48 (FILE):
  file cannot create directory: /usr/lib/luajit/share/cmake/torch.
  Maybe need administrative privileges.
```

How to fix it?

**Comment by soumith** [comment]
for such issues, use our google groups: https://groups.google.com/forum/#!forum/torch7
This issue tracker is for bugs and features of the core torch7 library.
