### ISSUE TITLE
Seg fault when running a deeper neural net

### ISSUE THREAD

**Issue by chwangaa** [torch/torch7#279]
Hey guys

I am following some torch tutorials

When running a shallow net (linear model) it is all fine. But when training a convolutional neural network, the program crashes with the error

```
Program is terminated. Because you tried to allocate too many memory regions
Segmentation Fault
```

Any idea how this can be fixed please?

Thank you

**Comment by soumith** [comment]
this is not a bug. You are probably running out of memory.
