### ISSUE TITLE
how to torch modules/plugins link with lua symbols?

### ISSUE THREAD

**Issue by hughperkins** [torch/torch7#284]
how to torch modules/plugins link with lua symbols?

eg, currently my module seems to contain its own lua symbols, but I'm guessing that's not quite right?

```
user@pear:~/git/cltorch$ grep newtable EasyCL/thirdparty/lua-5.1.5/src/*.h
EasyCL/thirdparty/lua-5.1.5/src/lua.h:#define lua_newtable(L)       lua_createtable(L, 0, 0)
user@pear:~/git/cltorch$ nm ~/torch/install/lib/libluajit.so | grep createtable
0000000000068290 T lua_createtable
user@pear:~/git/cltorch$ nm ~/torch/install/lib/libEasyCL.so | grep createtable
000000000002bff0 T lua_createtable
```

**Comment by hughperkins** [comment]
Ok, figured it out I think. It wasnt buliding the so that needed lua, it was the unittests, so simply removing lua libraries builds ok in fact, and doesnt include defined symbols.

**Comment by hughperkins** [comment]
Ok, I still have this issue.  I thought I'd solved it by simply not linking to any lua-ish thing at all, and that works ok, on 64-bit ubuntu.  But doesnt seem to work on mac, eg https://github.com/hughperkins/cltorch/issues/6#issuecomment-118452104 there are undefined symbols like:

```
Building CXX object CMakeFiles/EasyCL.dir/templates/TemplatedKernel.cpp.o
...
Undefined symbols for architecture x86_64:
"_luaL_loadstring", referenced from:
LuaTemplater::LuaTemplater() in LuaTemplater.cpp.o
"_luaL_newstate", referenced from:
LuaTemplater::LuaTemplater() in LuaTemplater.cpp.o
"_luaL_openlibs", referenced from:
LuaTemplater::LuaTemplater() in LuaTemplater.cpp.o
"_lua_close", referenced from:
LuaTemplater::~LuaTemplater() in LuaTemplater.cpp.o
LuaTemplater::~LuaTemplater() in LuaTemplater.cpp.o
```
Lacking a Mac, I have no obvious way of reproducing the problem.  How does this work in general for Torch modules?  Link with libluatT.so?  with libluajit.so?  something else?  create some special define whilst building? ... ?

**Comment by hughperkins** [comment]
Created a toy module at https://github.com/hughperkins/prototyping-lualink  .  Does this look somewhat correct?  Anything I'm missing to ensure this is cross-platform / builds ok on a mac?

CMakeLists.txt
```
cmake_minimum_required(VERSION 2.8)
include_directories(/home/user/torch/install/include)
add_library(mylib SHARED mylib.cpp)
```

Resulting library:
```
user@pear:~/git/machinelearning/prototyping/cpp/prototyping-lualink$ nm build/libmylib.so | grep lua
                 U luaL_register
0000000000000a00 T luaopen_mylib
00000000000009c5 t _ZL14mylib_sayHelloP9lua_State
```
=> seems ok on my own system?

**Comment by hughperkins** [comment]
Ok, found some doc on this here: http://lua-users.org/wiki/BuildingModules

=> closing

**Comment by soumith** [comment]
From my understanding, you never link against a specific lua library. It is pre-loaded by the Lua interpreter (or the LuaJIT interpreter).
