### ISSUE TITLE
Problem with loading cunn

### ISSUE THREAD

**Issue by yaolubrain** [torch/torch7#288]
I follow the install guide in
https://github.com/facebook/fbcunn/blob/master/INSTALL.md

After typing 
./install.sh 
in the torch repo folder, torch and its libraries look successfully installed.

But I can't load cunn. If we type
th> require 'cunn'
true

I also tried 
luarocks install cunn
Again, it was successully built and installed but I just can't load it.

Do you know what the problem is?

The output log during install:

Scanning dependencies of target cunn
Linking CXX shared module libcunn.so
[100%] Built target cunn
Install the project...
-- Install configuration: "Release"
-- Installing: /home/yao/torch/install/lib/luarocks/rocks/cunn/scm-1/lib/libcunn.so
-- Set runtime path of "/home/yao/torch/install/lib/luarocks/rocks/cunn/scm-1/lib/libcunn.so" to "$ORIGIN/../lib:/home/yao/torch/install/lib:/usr/local/cuda-7.0/lib64:/opt/OpenBLAS/lib"
-- Installing: /home/yao/torch/install/lib/luarocks/rocks/cunn/scm-1/lua/cunn/benchmark.lua
-- Installing: /home/yao/torch/install/lib/luarocks/rocks/cunn/scm-1/lua/cunn/init.lua
-- Installing: /home/yao/torch/install/lib/luarocks/rocks/cunn/scm-1/lua/cunn/DataParallelTable.lua
-- Installing: /home/yao/torch/install/lib/luarocks/rocks/cunn/scm-1/lua/cunn/test_DataParallelTable.lua
-- Installing: /home/yao/torch/install/lib/luarocks/rocks/cunn/scm-1/lua/cunn/test.lua
cd build
Updating manifest for /home/yao/torch/install/lib/luarocks/rocks
cunn scm-1 is now built and installed in /home/yao/torch/install/ (license: BSD)

**Comment by dominikgrewe** [comment]
What's the error you're getting and when do you get it? When calling `require 'cunn'`?

**Comment by yaolubrain** [comment]
The problem is my poor understanding of Torch.

I thought 
require 'cunn' 
would return something and we use it as
m = cunn.SpatialConvolutionMM(1,1,3,3)

Clearly the designers of Torch are more clever than me :)

**Comment by dominikgrewe** [comment]
cunn actually just adds CUDA implementations for the nn modules. So there's no `cunn.*` but instead you do things like this:

```lua
require 'nn'
require 'cunn'
m = nn.SpatialConvolutionMM(1, 1, 3, 3)
m = m:cuda()  -- Convert module to a CUDA module.
```

Hope that helps.

**Comment by yaolubrain** [comment]
Thanks dominik! But what about fbnn. 

require 'nn'
require 'fbnn'

I got 

/home/yao/torch/install/share/lua/5.1/trepl/init.lua:363: /home/yao/torch/install/share/lua/5.1/trepl/init.lua:363: module 'fb.util' not found:No LuaRocks module found for fb.util
        no field package.preload['fb.util']
        no file '/home/yao/.luarocks/share/lua/5.1/fb/util.lua'
        no file '/home/yao/.luarocks/share/lua/5.1/fb/util/init.lua'
        no file '/home/yao/torch/install/share/lua/5.1/fb/util.lua'
        no file '/home/yao/torch/install/share/lua/5.1/fb/util/init.lua'
        no file './fb/util.lua'
        no file '/home/yao/torch/install/share/luajit-2.1.0-alpha/fb/util.lua'
        no file '/usr/local/share/lua/5.1/fb/util.lua'
        no file '/usr/local/share/lua/5.1/fb/util/init.lua'
        no file '/home/yao/.luarocks/lib/lua/5.1/fb/util.so'
        no file '/home/yao/torch/install/lib/lua/5.1/fb/util.so'
        no file './fb/util.so'
        no file '/usr/local/lib/lua/5.1/fb/util.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/home/yao/.luarocks/lib/lua/5.1/fb.so'
        no file '/home/yao/torch/install/lib/lua/5.1/fb.so'
        no file './fb.so'
        no file '/usr/local/lib/lua/5.1/fb.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'error'
        /home/yao/torch/install/share/lua/5.1/trepl/init.lua:363: in function 'require'
        [string "_RESULT={require 'fbnn'}"]:1: in main chunk
        [C]: in function 'xpcall'
        /home/yao/torch/install/share/lua/5.1/trepl/init.lua:630: in function 'repl'
        .../yao/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
        [C]: at 0x00406670

**Comment by yaolubrain** [comment]
Thanks a lot, Dominik!
