### ISSUE TITLE
compile to dll

### ISSUE THREAD

**Issue by YitzhakSp** [torch/torch7#293]
I have a general question. Is it possible to compile torch to a dll-file to use it in an application? And if it is possible, how ?

**Comment by hughperkins** [comment]
Possible... yes.  Easy... depends on what you mean really.  By default, torch comprises multiples dlls, and a bunch of lua scripts.  If you requirement is a single dll, that 'just works', I guess one option could be to make it unpack itself into the home directory somewhere.  There is precedent for this kind of dll.  For example, in my jeigen project, I pack various sos and dlls and so on into a single jar file, and then unpack them when the jar file is loaded:
- jeigen https://github.com/hughperkins/jeigen
- code to unpack the jar at runtime https://github.com/hughperkins/jeigen/blob/master/src/java/jeigen/JeigenJna.java#L43

**Comment by YitzhakSp** [comment]
Hi Hugh, thanks for the advice. Actually I believe I was thinking about something different. I have a lua program that uses torch. I would like to transform it into an executable or a library-file. it maybe a dll, or an exe-file or something else. is there a way to do that?

**Comment by hughperkins** [comment]
It's certainly possible technically, in the worst case, create a small c program which:
- includes your script inside
- includes the lua engine
- runs the script using the engine

Actually... thats how my opencl kernel templater works in fact, and it compiles to a dll
- [EasyCL](https://github.com/hughperkins/EasyCL)
- [kernel templater](https://github.com/hughperkins/EasyCL/blob/master/templates/LuaTemplater.cpp#L72)
- [embedded lua script](https://github.com/hughperkins/EasyCL/blob/master/templates/LuaTemplater.cpp#L91)

If your question is 'are there any tools that will create such an exe for me?', sorry I dont know.

**Comment by SimTheVoid** [comment]
I have compiled torch (with torch/nn and something other parts) into DLLs without any troubles.

**Comment by YitzhakSp** [comment]
thanks for the advice !  Currently I am solving the problem by inserting the lua-script into a C program. However I would love to return to you if I need to go a different way.

**Comment by YitzhakSp** [comment]
At this point I am able to insert a lua-script into a C program. However the program does not work if the lua program includes files via 'require'. In this case the C program compiles but does not run properly. any ideas how to fix it?

**Comment by hughperkins** [comment]
Per SimTheVoid above:
- invoke luaopen_### by yourself for each required library

I originally parsed/interpreted this to mean, for each of your own libraries, but in retrospect, maybe he means for any libraries you are `require`ing?  By the way, once a library has been `require`d once, any additional calls to `require` are essentially silently ignored, so you just need to load each library once, somehow, I think.

**Comment by hughperkins** [comment]
Per SimTheVoid above:
- invoke luaopen_### by yourself for each required library

I originally parsed/interpreted this to mean, for each of your own libraries, but in retrospect, maybe he means for any libraries you are `require`ing?  By the way, once a library has been `require`d once, any additional calls to `require` are essentially silently ignored, so you just need to load each library once, somehow, I think.

**Comment by YitzhakSp** [comment]
Sorry I do not understand. how exactly shall I do this? shall I put '<luaopen('torch')> ' kwa

**Comment by hughperkins** [comment]
To be honest, I dont really know.  Better wait for SimTheVoid to reply.

**Comment by SimTheVoid** [comment]
@hughperkins 
It is clearly defined behaviour of 'require' function.
You can either load all binary libraries by filling 'package.preload' table (as I did) or you can write your own custom loader and put it into 'package.loaders' table.

As an example you can store all your compiled '.lua' files into c-arrays and make a kind of map.

**Comment by SimTheVoid** [comment]
@YitzhakSp 
> it seems that in some mysterious way it includes a whole module
It is not mysterious way at all.You can type `print(package.path)` and you will see how it works.

**Comment by YitzhakSp** [comment]
First of all thanks to SimTheVoid for the detailed explanations. Now, I feel like this explanation is still to complicated for me. I am really not an expert in lua so I am looking for a simple way to solve this problem.
To be more concrete I have `require 'torch'` in my lua file. what exactly shall I do (the most straightforward way) in order that this file can be inserted in a C program?

**Comment by SimTheVoid** [comment]
You have to modify your copy of torch package because it depends on 'paths' and trying to load lua files from your drive. So you should remove all that dependincies and use some your own version of `dofile` for them. 
Look at 'torch/init.lua:37' and 'torch/init.lua:111'

To preload your modified files one should pcall 'init.lua' and place any result into `package.loaded`
Like that:
```
lua_getfield(L, LUA_REGISTRYINDEX, "_LOADED");
luaL_loadstring(L, bufferWithInitLua);
lua_pushstring(L,"torch");
lua_pcall(L,1,1,0); //TODO: check for error
lua_setfield(L, -2, "torch");
```

**Before** you pcall that files, you should register 'libtorch' into `package.loaded`
```
lua_getfield(L, LUA_REGISTRYINDEX, "_LOADED");
lua_pushcfunction(L, &luaopen_libtorch);
lua_pushstring(L,"libtorch");
lua_pcall(L,1,1,0); //TODO: check for error
lua_setfield(L, -2, "libtorch");
```

**Comment by YitzhakSp** [comment]
SimTheVoid, thanks again for the detailed explanation. I have some difficulties with it, but at this point I feel that I can not continue to use your time without payment. Probably our company will hire an expert to deal with this issue (how to import the lua-program into an application). I hope they will be able to use the advice you have given until now.
