### ISSUE TITLE
wired gradient of CosineEmbeddingCriterion:backward

### ISSUE THREAD

**Issue by xyzhou-puck** [torch/torch7#298]
Hi guys,

Recently I have been working with CosineEmbeddingCriterion, it worked good when the input is a single instance(which is a 1-d tensor), however when I try to make the input as a mini-batch (input = torch.Tensor(batch_size, feature_size)), then the gradient gotten by CosineEmbeddingCriterion:backward seems wrong, I have tried some simple experiment and the result told me that the gradient gotten by mini-batch is exactly the negative of what it should be, could some one prove it or make a clean explanation?

Thanks,
Xiangyang

**Comment by fmassa** [comment]
`CosineEmbeedingCriterion` does not support batch mode for the moment, as well as`CosineDistance`.
There is a PR for `CosineDistance` pending merge https://github.com/torch/nn/pull/300 , I'll prepare one for `CosineEmbeedingCriterion` when it gets merged.

**Comment by xyzhou-puck** [comment]
That sounds fantastic, thanks very much and I will be looking forward to it. :)

**Comment by soumith** [comment]
closing the issue here. Opened it correctly under torch/nn https://github.com/torch/nn/issues/352
