### ISSUE TITLE
Can not install image package: Getting Connection timed out for couple of hours

### ISSUE THREAD

**Issue by dasabir** [torch/torch7#299]
I was following the 'Getting statrted with torch' tutorial (http://torch.ch/docs/getting-started.html) and torch got installed fine. When I was trying to install the 'image' package by issuing the command - luarocks install list - I'm getting a 'Connection timed out' error (Screenshot attached). Please help. I have tried the solution approach in issue #169 , it is not working for me.
![screenshot_image](https://cloud.githubusercontent.com/assets/3665715/8740164/56764fe0-2bfa-11e5-97fe-db3b709960a2.png)

Many thanks,
Abir

**Comment by soumith** [comment]
you seem to have no connection to github.com. I dont see how we can help there.

**Comment by dasabir** [comment]
Hi soumith,
Thanks for your reply. I tried to clone the image repo by issuing the command - git clone https://github.com/torch/image.git . It is getting cloned (screenshot attached). So seems that connecting to git is not a problem. I don't know if any firewall is causing any problem when it is installing from the rockspec. Anyway, can you help me to install the package from the cloned directory?
![screenshot_image2](https://cloud.githubusercontent.com/assets/3665715/8740388/95929406-2bfd-11e5-9354-2fa6ce67dd88.png)

Thanks again,
Abir

**Comment by soumith** [comment]
could you please use https://groups.google.com/forum/#!topic/torch7 for such topics, I will reply there. thanks.

**Comment by xiaofangECL** [comment]
thanks, it solves my problem also
