### ISSUE TITLE
Gather is Missing

### ISSUE THREAD

**Issue by shawnjhenry** [torch/torch7#301]
Hi,

I just updated my version of torch and the gather function no longer exists.  Specifically I get the error message "attempt to call method 'gather' (a nil value)".  Any idea how that could have happened?  Update: the gather function is definitely missing from TensorMath.lua (as is scatter).  Is this intentional?

Thanks,
Shawn

**Comment by soumith** [comment]
hey Shawn, I find both of them present in the trunk of TensorMath.lua
https://github.com/torch/torch7/blob/master/TensorMath.lua

**Comment by shawnjhenry** [comment]
I just reinstalled torch again, this time with luarocks.  Now it's there.  Weird.  Thanks!
