### ISSUE TITLE
torch/luarocks failing to fetch manifests

### ISSUE THREAD

**Issue by Dwood15** [torch/torch7#303]
Example Input: luarocks install nn

Output: 

Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/torch/rocks/master - Failed downloading https://raw.githubusercontent.com/torch/rocks/master/manifest
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master - Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/manifest

Version: LuaRocks 2.2.0beta1

**Comment by paulheideman** [comment]
```./install.sh``` failing for me with same warnings.

Is there a workaround?

**Comment by soumith** [comment]
@paulheideman can you actually download this file from the same machine?

https://raw.githubusercontent.com/torch/rocks/master/manifest

can you try:  
sudo rm -rf ~/.luarocks

**Comment by paulheideman** [comment]
@soumith I worked it out eventually, but very close to what you suggested.

```sudo rm -rf ~/.cache/luarocks```

Thanks!

**Comment by xiaofangECL** [comment]
sudo rm -rf ~/.cache/luarocks
it solves my issue also

**Comment by shravankumar147** [comment]
luarocks install cutorch
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/torch/rocks/master - Failed downloading https://raw.githubusercontent.com/torch/rocks/master/manifest - /home/shravan/.cache/luarocks/https___raw.githubusercontent.com_torch_rocks_master/manifest
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master - Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/manifest - /home/shravan/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moonrocks-mirror_master/manifest

Error: No results matching query were found.

I've tried above solutions but not worked for me.

**Comment by MunenderVarshney** [comment]
I  have installed Torch from scratch and then tried installation of packages using luarocks and got following results.
----------------------------------------------------------------------------------------------------------------------------
luarocks install image
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/torch/rocks/master - Failed downloading https://raw.githubusercontent.com/torch/rocks/master/manifest - /home/munender/.cache/luarocks/https___raw.githubusercontent.com_torch_rocks_master/manifest
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master - Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/manifest - /home/munender/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moonrocks-mirror_master/manifest

Error: No results matching query were found.
---------------------------------------------------------------------------------------------------------------------------------
I have tried the above solutions by deleting the cache using "sudo rm -rf ~/.cache/luarocks" command but it doesn't work

**Comment by Lakung** [comment]
thanks, it solved my problem perfectly

**Comment by changhongyan123** [comment]
sudo rm -rf ~/.cache/luarocks

it solves my problem.
Thanks .

**Comment by guoyang007** [comment]
@MunenderVarshney ,  so how do you solve this problem at last  after trying "sudo rm -rf ~/.cache/luarocks" but no effect?

**Comment by HiZhaoxiaoyang** [comment]
sudo rm -rf ~/.cache/luarocks
and 
sudo luarocks install loadcaffe

thx, finally it works.

**Comment by icamys** [comment]
Got same error when I was trying to search for any rock. From verbose mode found out that I was missing `curl` package.

**Comment by jackschmidt** [comment]
luarocks install --verbose # showed that on mac, it wanted wget installed

**Comment by DHXxuekun** [comment]
Example Input: luarocks install nn

Output:

x@x-Inspiron-5420:~/torch$ sudo rm -rf ~/.cache/luarocks
[sudo] password for x: 
x@x-Inspiron-5420:~/torch$ luarocks install mattorch
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/torch/rocks/master - Failed downloading https://raw.githubusercontent.com/torch/rocks/master/manifest - /home/x/.cache/luarocks/https___raw.githubusercontent.com_torch_rocks_master/manifest
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master - Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/manifest - /home/x/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moonrocks-mirror_master/manifest

Error: No results matching query were found.
x@x-Inspiron-5420:~/torch$ 

I've tried above solutions including  sudo rm -rf ~/.cache/luarocks but not worked for me.
so how to solve this problem.

**Comment by oriondream** [comment]
You may need to specify the rocks server:
    `sudo luarocks install --server=http://luarocks.org nn`

**Comment by DHXxuekun** [comment]
Thank you very much for your reply, but it still doesn't work.

x@x-Inspiron-5420:~$ sudo luarocks install --server=http://luarocks.org nn
[sudo] password for x: 
sudo: luarocks: command not found

Is there any other way?

**Comment by DHXxuekun** [comment]
Thank you very much for your reply, but it still doesn't work. And I just want to "luarocks install mattorch", is there any other way?

x@x-Inspiron-5420:~$ sudo luarocks install --server=http://luarocks.org nn
[sudo] password for x:
sudo: luarocks: command not found

Is there any other way?

**Comment by tastyminerals** [comment]
@DHXxuekun you should run luarocks that come with Torch. 

```
source ~/torch/install/bin/torch-activate
luarocks install nn
```

**Comment by DHXxuekun** [comment]
@ tastyminerals
Thank you very much, you solved a problem for me. However, the following problems occurred. After I checked the data, I used the method provided on the Internet, but I still couldn't solve it.

xuekun@xuekun-Inspiron-5420:~$ luarocks install mattorch
Installing https://raw.githubusercontent.com/torch/rocks/master/mattorch-1.0-0.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/mattorch-1.0-0.rockspec... switching to 'build' mode
Cloning into 'lua---mattorch'...
remote: Counting objects: 19, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 19 (delta 0), reused 8 (delta 0), pack-reused 0
Receiving objects: 100% (19/19), 11.32 KiB | 0 bytes/s, done.
Checking connectivity... done.
Note: checking out 'c3640f86dc23c9cac836752576f6a3594d9fc4e3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

git checkout -b new_branch_name

cmake -E make_directory build;
cd build;
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/xuekun/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/xuekun/torch/install/lib/luarocks/rocks/mattorch/1.0-0";
make

-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /home/xuekun/torch/install
-- ** WARNING no MATLAB_ROOT setting to /opt/matlab
-- ** you can set the correct MATLAB_ROOT in your environment
-- ** eg. bash: export MATLAB_ROOT=/home/john/matlab
-- Using Matlab in: /opt/matlab
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
MATLAB_INCLUDE_DIR (missing: MATLAB_MEX_LIBRARY MATLAB_MAT_LIBRARY
MATLAB_ENG_LIBRARY MATLAB_MX_LIBRARY)
Call Stack (most recent call first):
/usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
FindMatlab.cmake:123 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
CMakeLists.txt:11 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_mattorch-1.0-0-117/lua---mattorch/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found. Stop.

Error: Build error: Failed building.

I uesd this method, but it didn't work.

git clone https://github.com/clementfarabet/lua---mattorch.git
cd lua---mattorch
mkdir build
cd build
cmake -DMATLAB_ROOT=/Applications/MATLAB_R2014a.app/ ..
cd ..
luarocks make

CMake Error: The source directory "/home/xuekun/lua---mattorch/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

I don't know what to do, is there any other solution?

**Comment by DHXxuekun** [comment]
@ tastyminerals
Thank you very much, you solved a problem for me. However, the following problems occurred. After I checked the data, I used the method provided on the Internet, but I still couldn't solve it.

xuekun@xuekun-Inspiron-5420:~$ source ~/torch/install/bin/torch-activate
xuekun@xuekun-Inspiron-5420:~$ luarocks install mattorch
Installing https://raw.githubusercontent.com/torch/rocks/master/mattorch-1.0-0.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/mattorch-1.0-0.rockspec... switching to 'build' mode
Cloning into 'lua---mattorch'...
remote: Counting objects: 19, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 19 (delta 0), reused 8 (delta 0), pack-reused 0
Receiving objects: 100% (19/19), 11.32 KiB | 0 bytes/s, done.
Checking connectivity... done.
Note: checking out 'c3640f86dc23c9cac836752576f6a3594d9fc4e3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

git checkout -b new_branch_name

cmake -E make_directory build;
cd build;
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/xuekun/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/xuekun/torch/install/lib/luarocks/rocks/mattorch/1.0-0";
make

-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /home/xuekun/torch/install
-- ** WARNING no MATLAB_ROOT setting to /opt/matlab
-- ** you can set the correct MATLAB_ROOT in your environment
-- ** eg. bash: export MATLAB_ROOT=/home/john/matlab
-- Using Matlab in: /opt/matlab
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
MATLAB_INCLUDE_DIR (missing: MATLAB_MEX_LIBRARY MATLAB_MAT_LIBRARY
MATLAB_ENG_LIBRARY MATLAB_MX_LIBRARY)
Call Stack (most recent call first):
/usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
FindMatlab.cmake:123 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
CMakeLists.txt:11 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_mattorch-1.0-0-117/lua---mattorch/build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found. Stop.

Error: Build error: Failed building.

I uesd this method, but it didn't work.

git clone https://github.com/clementfarabet/lua---mattorch.git
cd lua---mattorch
mkdir build
cd build
cmake -DMATLAB_ROOT=/Applications/MATLAB_R2014a.app/ ..
cd ..
luarocks make

CMake Error: The source directory "/home/xuekun/lua---mattorch/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

I don't know what to do, is there any other solution?

**Comment by tastyminerals** [comment]
This is not Torch. This is an interface between Torch and Matlab and one which is >5 years old and it is not maintained anymore.

**Comment by DHXxuekun** [comment]
I tried many ways and eventually found a way to suit me.
cmake -DMATLAB_ROOT=/usr/local/MATLAB/R2015b/ ..
My problem has been solved. Finally, thank you very much. I learned a lot of knowledge!

**Comment by chengxiqiao** [comment]
i met the problem"Error: No results matching query were found" too, but i don't have the right to sudo, please help me

**Comment by Harryjun** [comment]
@chengxiqiao @DHXxuekun 

goto https://github.com/torch search your package and gitclone,
then install local
such as install tds
`
git clone https://github.com/torch/tds
luarocks install tds/rocks/tds-scm-1.rockspec
`
Hope it can help you!
