### ISSUE TITLE
Bug in nn.Sequential.remove

### ISSUE THREAD

**Issue by avnermay** [torch/torch7#304]
if a Sequential container only contains 1 module, the current "remove" code throws an exception at the line I have starred below.

function Sequential:remove(index)
   index = index or #self.modules
   if index > #self.modules or index < 1 then
      error"index out of range"
   end
   table.remove(self.modules, index)
****   self.output = self.modules[#self.modules].output ****
   self.gradInput = self.modules[1].gradInput
end

**Comment by soumith** [comment]
thanks a lot for the bug report, but can you please open it under the nn repository please?

https://github.com/torch/nn

**Comment by avnermay** [comment]
Done.  Next time I'll know to file it under the correct repo.
