### ISSUE TITLE
Torch broken on OS X (missing library -lrt), likely due to recent commit

### ISSUE THREAD

**Issue by CMPXCHG8B** [torch/torch7#311]
Greetings to all!

I'm currently trying to build Torch on a Macintosh system running OS X 10.8.5 and Xcode 5.1.1. Everything seems to work up until I try to install Torch with the following command:

    `luarocks install torch`

At which point the build craps out with an error from ld about no library being found for -lrt on libTH.dylib. I'm a bit puzzled by this because I could have sworn rt wasn't available on OS X (and never has been).

I can see that the commit cd436eb6a61ab90266f510608e91868ba9311b50 recently added this option to the CMakeLists.txt file under lib/TH, specifically the lines:

    +IF (${UNIX})
    +  TARGET_LINK_LIBRARIES(TH rt)
    +ENDIF(${UNIX})

Appear to be responsible for the failure. What can I do (if anything) to work around this issue? Is there some way to checkout an earlier version of Torch using luarocks prior to these changes?

Cheers,
-CMPX

**Comment by szagoruyko** [comment]
confirm this too, OS X build is broken

**Comment by soumith** [comment]
thanks a lot for reporting this. fixed in trunk now via https://github.com/torch/torch7/commit/3e736cabc5baea2e891a48899d3db9946437f04f

Our contbuilds are only hooked up for linux, so this was hard to detect. 

cc: @koraykv

**Comment by koraykv** [comment]
ahh, sorry about that!

**Comment by hughperkins** [comment]
Mac doesnt exactly make it easy.  Cant just run up an OSX instance on AWS.
