### ISSUE TITLE
Installation and/or build failure with various methods

### ISSUE THREAD

**Issue by e0i** [torch/torch7#327]
**Summary:** *I have been trying various methods to install torch all with failure. Details below.*

Hi.
I was at first on a `Fedora 22 Server 64-bit` when I first tried to build. Then I switched to a fresh new `Ubuntu 15.04 Server 64-bit` and got the *exact* same errors. Extra output is truncated to only show the lines that contain error messages.

# Build
First I have tried building Torch by following the official "Getting Started" [guidelines](http://torch.ch/docs/getting-started.html#_).  Here is the failure I got while building dependencies:
```bash
$ curl -s https://raw.githubusercontent.com/torch/ezinstall/master/install-deps | bash

...

../Makefile.tail:40: recipe for target 'libs' failed
make[1]: *** [libs] Error 1
make[1]: Leaving directory '/tmp/OpenBLAS/kernel'
Makefile:141: recipe for target 'libs' failed
make: *** [libs] Error 1
Error. OpenBLAS could not be compiled
```
After looking it up and following various solutions that didn't work, I finally decided to *skip* OpenBLAS installation by modifying the bash script `install-deps`. Because I remember somewhere it said that OpenBLAS was actually somehow optional. So I got,
```bash

...

==> Torch7's dependencies have been installed
```

Then I proceeded by executing the `./install.sh` script inside the `torch` directory. And I got,

```bash

...

[  6%] Building C object lib/TH/CMakeFiles/TH.dir/THTensor.c.o
cc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
lib/TH/CMakeFiles/TH.dir/build.make:123: recipe for target 'lib/TH/CMakeFiles/TH.dir/THTensor.c.o' failed
make[2]: *** [lib/TH/CMakeFiles/TH.dir/THTensor.c.o] Error 4
CMakeFiles/Makefile2:228: recipe for target 'lib/TH/CMakeFiles/TH.dir/all' failed
make[1]: *** [lib/TH/CMakeFiles/TH.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2

Error: Build error: Failed building.
```
Every time it fails at `THTensor.c.o`, both in Ubuntu and Fedora. 

I have tried various workarounds like using an existing rockspec inside the `torch` directory via `luarocks` for installation. Unfortunately I don't have the outputs and don't remember the exact details. But at one point there was an issue of failing to install `cwrap` and `paths`. Then I had to use the luarocks binary *inside* the `torch` directory with an alternative  server to install them. 

# Docker
After failing to build torch for myself, I thought I would turn to existing Docker solutions. Here are the error outputs I got from each container I found. 

- A docker image as [suggested](https://github.com/torch/torch7/wiki/Cheatsheet#docker-images) by installation cheatsheet in the official wiki:
```bash
$ docker run kaixhin/cuda-torch
 
...

th> Do you really want to exit ([y]/n)? /root/torch/install/bin/luajit: /root/torch/install/share/lua/
5.1/trepl/init.lua:567: attempt to index local 'line' (a nil value)
stack traceback:
        /root/torch/install/share/lua/5.1/trepl/init.lua:567: in function 'repl'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
        [C]: at 0x00406670
```

- A docker container I found in the repositories:
```bash
$ docker run jbenjos/torch7

...

Do you really want to exit ([y]/n)? /usr/local/bin/luajit: /usr/local/share/lua/5.1/trepl/readline.lua
:104: attempt to index local 'line' (a nil value)
stack traceback:
        /usr/local/share/lua/5.1/trepl/readline.lua:104: in function 'shell'
        /usr/local/share/lua/5.1/trepl/init.lua:478: in function 'repl'
        /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:183: in main chunk
        [C]: at 0x004061d0
```
- An example container with a package that uses torch:
```bash
$ docker run mbartoli/char-rnn
$
``` 
The container exits witth error code: `0`.

The erros may seem trivial. But the thing is that as a new user, I have failed installation inside fairly up-to-date environments by following the official documents. I hope this feedback helps.

Thanks in advance.

**Comment by hughperkins** [comment]
Hi e0i, as far as your goal of installing Torch, I think that the 'mainstream' target os right now within torch community might be ubuntu 14.04 64-bit, and probably Mac OS X too plausibly.  15.04 is probably somewhat 'bleeding edge'.

**Comment by e0i** [comment]
Hello. Thanks for the quick reply. Following your comment, I have installed a plain new `Ubuntu 14.04 Server 64-bit` and tried to install Torch by following the Getting Started guide. Once again I got the same error at the very start:

```bash

...

ar: sgemm_kernel.o: No such file or directory
make[1]: *** [libs] Error 1
make[1]: Leaving directory `/tmp/OpenBLAS/kernel'
make: *** [libs] Error 1
Error. OpenBLAS could not be compiled
```

**Comment by soumith** [comment]
@e0i OpenBLAS seems to be failing install. I am tempted to make OpenBLAS installs optional, because they seem to be recently failing on a few machines. How about if you apply your "optional openblas" patch and run the installer on the Ubuntu 14.04 machine? It should work just fine (our contbuild on travis-ci precisely tests this).

**Comment by e0i** [comment]
I skipped OpenBLAS installation and dependencies got installed as expected. 

But unfortunately I got *exactly* the same set of errors in the installation process as before. Even with a fresh installation of Ubuntu 14. 

```bash

...

[  8%] Building C object lib/TH/CMakeFiles/TH.dir/THTensor.c.o
cc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [lib/TH/CMakeFiles/TH.dir/THTensor.c.o] Error 4
make[1]: *** [lib/TH/CMakeFiles/TH.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.
```
I think there might be something overlooked in the installation scripts. I have tried my best to debug the problem and install / compile necessary packages individually. I couldn't pull it off.

I find it necessary to point out that it is a very bad first impression for *any* user to not being able to install Torch by using more or less "default", widely used environments like Fedora and Ubuntu. Even Docker. Making Torch easy to install without any problems could be a big win.

**Comment by szagoruyko** [comment]
are you using a virtual machine? how much RAM do you have? post more info on your machine

**Comment by soumith** [comment]
> I find it necessary to point out that it is a very bad first impression for any user to not be able to install Torch by using more or less "default", widely used environments like Fedora and Ubuntu. Even Docker. Making Torch easy to install without any problems could be a big win.

Thanks a lot for your feedback. 
To pull up some statistics, Torch averages about 250 installs per day, 150 of them being unique installs. We get < 1 "install problems" issues everyday, combining github issues, the mailing list and stackoverflow. At a 0.66% failure rate, we think we've covered most users. In fact, most install failures come from non-standard setups or new OSes. We also have continuous builds checking the stability of the torch distro across the core packages on Ubuntu 12.04 and 14.04. We are planning to add 15.04 and OSX soon.

Apart from that, we are putting quite some effort into nightly binary installs, where torch simply can be downloaded and run. This has been hard, but with nvidia's help, we created a .deb package that we are testing.

**Comment by soumith** [comment]
Now, your particular error is very unique. It looks like gcc itself is throwing an internal compiler error (something that has never happened to any of our users from my memory). A gcc compiler error across two separate OSes of yours, that we cant reproduce in the contbuilds or any of our machines usually means that you are running on hardware that gcc is not happy about.
My first suspicion is that you dont have enough memory (are you  < 1GB?).

Also, about the docker containers, you are running torch inside docker, but without an open stdin. That means that you are starting torch, but your terminal is providing no input to docker.

**Comment by AntonisKoutounids** [comment]
I have exactly the same error. I can not install torch
./Makefile.tail:40: recipe for target 'libs' failed
make[1]: *** [libs] Error 1
make[1]: Leaving directory '/tmp/OpenBLAS/kernel'
Makefile:133: recipe for target 'libs' failed
make: *** [libs] Error 1
Error. OpenBLAS could not be compiled

I tried some solutions but none seems to work
