### ISSUE TITLE
Questions with image.display

### ISSUE THREAD

**Issue by xcyan** [torch/torch7#333]
Hi,

Anyone has idea of how to hold the window while plotting?
For example, if I run "image.display(image.lena())" for several times, it actually plots several windows.
I was wondering whether it is possible to hold the window (a single one) while doing plotting. Thanks very much!

Best,

**Comment by soumith** [comment]
look at the documentation for image.display, located here: https://github.com/torch/image it returns a window handle.
Also, this is the wrong repo for this issue.
