### ISSUE TITLE
Missing link in Developer Documentation

### ISSUE THREAD

**Issue by tonyyang1993** [torch/torch7#344]
At [Developer Documentation](http://torch.ch/docs/developer-docs.html), the docs end up with two hanging examples (1. Writing modules at the Lua level: Implementing Dropout Activation Units. 2. Writing modules at the C or CUDA level).

Does anyone know where should I refer to these two examples? Or the docs is simply incomplete. Google the name doesn't give desired answer.

Thanks!

**Comment by soumith** [comment]
@tonyyang1993 sorry, that is still being written an incomplete.

**Comment by soumith** [comment]
I've written a first draft of developer documentation that should get you going. feel free to improve it by sending in a pull request.

**Comment by tonyyang1993** [comment]
Thank you very much @soumith.
