### ISSUE TITLE
What does "local" really do?

### ISSUE THREAD

**Issue by johnny5550822** [torch/torch7#346]
I have seen something like this:

```
 local model = nn.Sequential()
 local feval = function(x)
   model:forward(SOMETHING)
 end
```

So is this mean the function can use "model" even if it is not part of the input? So, "local" mean everything(variables) within a .lua can be assessed by a function?

**Comment by soumith** [comment]
direct these questions to google groups: groups.google.com/forum/#!forum/torch7
