### ISSUE TITLE
Seems like `th` suppresses diagnostic error information?

### ISSUE THREAD

**Issue by hughperkins** [torch/torch7#348]
Seems like `th` suppresses diagnostic error information?  So, we often have to ask people to run things like luajit or lua instead, to get more details on their error.  Any reason why th couldnt produce this information natively?

**Comment by soumith** [comment]
we should setup an xpcall there, instead of a pcall. that would fix it. it is indeed annoying to have to go back and forth with users to tell them to execute their stuff under "luajit -l [libname]" a second time.
https://github.com/torch/trepl/blob/master/th#L35-L38

**Comment by hughperkins** [comment]
This probably still needs to be done right?  Although I just use `luajit` almost systematically, partially for this reason, but might be good to fix sometime?  I dont have bandwidth to do this though, and just use `luajit` personally, to avoid the issue :-)

**Comment by soumith** [comment]
fixed via https://github.com/torch/trepl/pull/40

**Comment by hughperkins** [comment]
Haha cool, I never tried `th` for several months, and never noticed this :-D
