### ISSUE TITLE
mse criterion returns negative values when running in parallel on the same gpu

### ISSUE THREAD

**Issue by ItzikMalkiel** [torch/torch7#352]
I'm using nn.MSECriterion and I've noticed that the following code results with negative value in very rare cases:
local err = criterion:forward(output, targets)

It happened to me in very rare cases (3-4 times in the last year) - in all cases I trained two networks at the same time over the same gpu. 
Note that it happened after thousands of epochs and it is very hard to reproduce.

If someone knows why it can happen or how to fix/avoid it - please let me know. 

Thanks in advance,
Itzik.

**Comment by soumith** [comment]
open issue under our cuda nn repository https://github.com/torch/cunn
