### ISSUE TITLE
Build error with isnan() on FreeBSD

### ISSUE THREAD

**Issue by jbeich** [torch/torch7#355]
`TH_TENSOR_*APPLY*` macros don't like `isnan()` implementation on FreeBSD 10 or later. It's due to [`<math.h>`](https://github.com/freebsd/freebsd/commits/master/lib/msun/src/math.h) cleanup done by David Chisnall (theraven) in 2013.

clang 3.7.0
```
In file included from lib/TH/THTensor.c:19:
In file included from generic/THTensorMath.c:2:
lib/TH/generic/THTensorMath.c:303:31: error: controlling expression type 'unsigned char' not compatible with any generic association type
                    if (isnan(value))
                              ^~~~~
/usr/include/math.h:114:19: note: expanded from macro 'isnan'
        __fp_type_select(x, __inline_isnanf, __inline_isnan, __inline_isnanl)
                         ^
/usr/include/math.h:82:49: note: expanded from macro '__fp_type_select'
#define __fp_type_select(x, f, d, ld) _Generic((x),                     \
                                                ^
lib/TH/THTensorApply.h:396:7: note: expanded from macro 'TH_TENSOR_APPLY'
      CODE \
      ^
```

gcc 5.2.0
```
In file included from lib/TH/THTensor.h:5:0,
                 from lib/TH/THTensor.c:2:
lib/TH/generic/THTensorMath.c: In function 'THByteTensor_minall':
lib/TH/generic/THTensorMath.c:303:25: error: void value not ignored as it ought to be
                     if (isnan(value))
                         ^
lib/TH/THTensorApply.h:396:7: note: in definition of macro 'TH_TENSOR_APPLY'
       CODE \
       ^
```

**Comment by jbeich** [comment]
@DimitryAndric, can you help with debugging (which side to blame)? 95586d5 is a workaround. To reproduce apply bc3401c (unrelated) then skip Lua stuff by:
```
$ cd lib/TH
$ cmake .
$ gmake
```

**Comment by DimitryAndric** [comment]
This looks like a problem in the THTensorMath.c file.  It calls isnan() with an unsigned char argument, but isnan() only operates on floating point values:

    In file included from generic/THTensorMath.c:2:
    /share/dim/src/torch7/lib/TH/generic/THTensorMath.c:335:31: error: controlling expression type 'unsigned char' not compatible with any generic association type
                        if (isnan(value))
                                  ^~~~~

The `value` variable is of type `real`, and that type seems to vary over a lot of types, some of which are floating, and others are not.  If you want to call isnan(), you have to supply a floating point argument, for example by casting it to the appropriate floating point type.

**Comment by hughperkins** [comment]
Maybe could `#ifdef` this?  Like `#if real == float || real == double`?  (My macros are a bit rusty, so exact syntax might need some work).

**Comment by DimitryAndric** [comment]
Yes, this could be used, e.g.:
````
#if defined(TH_REAL_IS_FLOAT) || defined(TH_REAL_IS_DOUBLE)
#define TH_ISNAN(x) isnan(x)
#else
#define TH_ISNAN(x) false
#endif
```

**Comment by hughperkins** [comment]
I was thinking more of #ifdeffing the places where it's used, like:
```
#if defined(TH_REAL_IS_FLOAT) || defined(TH_REAL_IS_DOUBLE)
                    if (isnan(value))
                      break;
#endif
```
Both ok for me though.

**Comment by zweifel** [comment]
Same problem here on Arch Linux.
The error through out was: non-floating-point argument in call to function '__builtin_isnan'
So it was a bit hard to find this bug.

I compiled here casting the 4 entries to float: 
`isnan((float) value).`

This little hack may not be elegant, but it solves the problem reasonably well.
If real is double, casting it to float should not be a problem even if it is nan. Moreover, in case real is an unsigned char, then that is already a mistake per se cause isnan() needs floating point type.

**Comment by archdria** [comment]
Just in case somebody is interested, here's a quick way to fix it. Just run the following command in the torch directory
find pkg/torch/ -type f -exec sed -i 's/isnan(/isnan((double)/' {} +
