### ISSUE TITLE
Failed installing dependency Error fetching file: Failed downloading

### ISSUE THREAD

**Issue by sounansu** [torch/torch7#357]
I am tring to install Torch7 on ubuntu14.04.3 LTS
But 'Missing depndencies for trepl' prevent to install torch7.

Error messages are
-------------------------------------------------------------------------------------------------------------------------------- 
$cd toch
$./install.sh

(meny messages)

Missing dependencies for trepl:
penlight >= 1.1.0

Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/penlight-1.3.2-2.rockspec... switching to 'build' mode

Error: Failed installing dependency: https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/penlight-1.3.2-2.rockspec - Error fetching file: Failed downloading http://stevedonovan.github.io/files/penlight-1.3.2-core.zip
------------------------------------------------------------------------------------------------------------------------------
2 month ago, I could install Torch7 by 'http://torch.ch/docs/getting-started.html#_'.
(Last month , HDD crushed! :-<)

**Comment by soumith** [comment]
use https://groups.google.com/forum/#!forum/torch7 for your install questions.
