### ISSUE TITLE
Inplace subtraction only via a:add(-1, b)?

### ISSUE THREAD

**Issue by andreaskoepf** [torch/torch7#362]
A remark to one of the most basic tensor operations:
If you want to compute the difference between two tensors *inplace* and you list the tensor members everything looks fine since there are add(), mul(), div() (all offering an optional inplace-semantic) and a method called sub() .. unfortunately sub() stands for extracting sub-tensors and not for computing the difference. The only method I found for computing the difference inplace seems to be [[res] torch.add([res,] tensor1, value, tensor2)](https://github.com/torch/torch7/blob/master/doc/maths.md#res-torchaddres-tensor1-value-tensor2) when used with -1 as factor.

Have I missed something?
Could this be added to the [math documentation](https://github.com/torch/torch7/blob/master/doc/maths.md)?
Are there any speed penalties for the -1 multiplication?
Have you considered adding a dedicated subtraction function, e.g. called subt() or subtract()?

**Comment by hughperkins** [comment]
Hi Andreas,

I agree, I think these are needed.  In cltorch, I added two new operations:
```
c:csub(d) -- subtracts d from c, element-wise
          -- similar to 'c - d'
          -- but stores results into c
a:neg()   -- similar to '- a'
          -- but stores results into a
```

I should put these on the front-page readme actually, under 'original, not in cutorch'.  They are however documented in said-named section at:

https://github.com/hughperkins/cltorch/blob/master/doc/ImplementedDetails.md

**Comment by hughperkins** [comment]
(Note: I've added these to cltorch readme now: https://github.com/hughperkins/cltorch#csub-neg )

**Comment by soumith** [comment]
> Have I missed something?
No, you are correct.

> Could this be added to the math documentation?
Yes

> Are there any speed penalties for the -1 multiplication?
Nope. The operation is bandwidth bound.

> Have you considered adding a dedicated subtraction function, e.g. called subt() or subtract()?

Yes. I think we can add it. Never got around to it.

**Comment by soumith** [comment]
If someone sends in a PR for this, happy to accept.

**Comment by hughperkins** [comment]
Note: we also need `:sub(123)`.  So the operations are:
```
a = randn(3,2)
b = randn(3,2)
a:csub(b)
a:sub(123)
a:neg()
```

**Comment by hughperkins** [comment]
Cool :-)
