### ISSUE TITLE
no broadcasting in torch?

### ISSUE THREAD

**Issue by yangky11** [torch/torch7#365]
Hi all,

Is there any mechanism in Torch similar to [broadcasting in numpy](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)?

The problem is that I have a NxD matrix X and a vector y of length N. I would like to add each element in y to corresponding row of X. If it were numpy, then the code would be:  

```
X + y[:, numpy.newaxis]
```
Is there an elegant way to do it in torch?

Thanks.

**Comment by nicholas-leonard** [comment]
@yangky11 
```lua
X = torch.randn(3,4)
y = torch.randn(4)
z = X + y:view(1,4):expandAs(X)
```
