### ISSUE TITLE
the issue of copying torch.CudaTensor

### ISSUE THREAD

**Issue by marvin521** [torch/torch7#370]
<addr> 
  combinOutput=torch.Tensor(channel,outputR,outputC):float():zero()
  if isGPU >= 0 then
     combinOutput:cuda()
  end
  local startRow=1
  local startCol=1
  for i=1,numRegions do
      combinOutput[{{1,channel},{startRow,(startRow+regionsTab[i]:size(rowIdx)-1)},{startCol,(startCol+regionsTab[i]:size(colIdx)-1)}}]=regionsTab[i]:clone()
   -- else code................
  end
<addr>

I have a problem when I copy/clone a tensor to another tensor. It is no problem to execute the above codes on CPU mode. But there comes the problem (shown in bellow) when the codes are executed on GPU mode.  On GPU mode, regionsTab[i] is a torch.CudaTensor and combinOutput is also a torch.CudaTensor. why can't I copy one tensor to another one?

the error message:
  <addr> 
qlua: bad argument #3 to '?' (torch.*Tensor expected, got userdata)
stack traceback:
	[C]: at 0x7ffaa2ee6960
	[C]: at 0x7ffa82c99940
	[C]: in function '__newindex'
<addr>

**Comment by GeorgOstrovski** [comment]
`x:cuda()` doesn't change the type of `x` in-place, it returns a new cuda tensor without affecting `x`.

You need to replace the line `combinOutput:cuda()` by `combinOutput = combinOutput:cuda()` to make your code work.

**Comment by marvin521** [comment]
@GeorgOstrovski, Thanks for your reply, it works..   ^.^
