### ISSUE TITLE
Which tool for Torch7

### ISSUE THREAD

**Issue by xiaojidan** [torch/torch7#371]
Hi all,
I want to know which tool you use for Torch7 in your project?

**Comment by fmassa** [comment]
Hi,
So, the best places to ask this kind of question is in the [google forums](https://groups.google.com/forum/#!forum/torch7) or the [gitter](https://gitter.im/torch/torch7).
Anyway, I use vim and gdb for debugging, but there are other friendlier alternatives. I can point it out in the google groups other resources if you open a post there.

**Comment by xiaojidan** [comment]
Thanks a  lot @fmassa
