### ISSUE TITLE
Including cutorch results in a malformed mach-o image error

### ISSUE THREAD

**Issue by minqi** [torch/torch7#379]
When I try including cutorch in a project, I receive this error:

    luajit: error loading module 'libcutorch' from file '/Users/minqi/torch/install/lib/lua/5.1/libcutorch.so':
	dlopen(/Users/minqi/torch/install/lib/lua/5.1/libcutorch.so, 6): no suitable image found.  Did find:
	/Users/minqi/torch/install/lib/lua/5.1/libcutorch.so: malformed mach-o image: load command #19    length (0) too small in /Users/minqi/torch/install/lib/lua/5.1/libcutorch.so
    stack traceback:
	    [C]: at 0x010d1a66e0
	    [C]: at 0x010d1a5d00
	    [C]: at 0x010d177780

I am running OS X Yosemite 10.10.5. My CMake is the latest version, 3.3.2, and I'm using CUDA 7.5.

**Comment by soumith** [comment]
if it's a cutorch problem, please open an issue here: https://github.com/torch/cutorch
Thanks.
