### ISSUE TITLE
Cannot compile torch7 master branch in Mac OS X EI Capiton

### ISSUE THREAD

**Issue by linkerlin** [torch/torch7#412]
Updating manifest for /Users/linkerlin/torch/install/lib/luarocks/rocks
sundown scm-1 is now built and installed in /Users/linkerlin/torch/install/ (license: BSD)

Updating manifest for /Users/linkerlin/torch/install/lib/luarocks/rocks
cwrap scm-1 is now built and installed in /Users/linkerlin/torch/install/ (license: BSD)

Warning: unmatched variable LUALIB
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DLUALIB= -DLUA_INCDIR="/Users/linkerlin/torch/install/include" -DLUA_LIBDIR="/Users/linkerlin/torch/install/lib" -DLUADIR="/Users/linkerlin/torch/install/lib/luarocks/rocks/paths/scm-1/lua" -DLIBDIR="/Users/linkerlin/torch/install/lib/luarocks/rocks/paths/scm-1/lib" -DCMAKE_INSTALL_PREFIX="/Users/linkerlin/torch/install/lib/luarocks/rocks/paths/scm-1" && make

System is unknown to cmake, create:
Platform/[proxychains] DLL init: proxychains-ng 4.10-git-10-g2237749
[proxychains] DLL init: proxychains-ng 4.10-git-10-g2237749
Darwin to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
Your CMakeCache.txt file was copied to CopyOfCMakeCache.txt. Please send that file to cmake@www.cmake.org.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/linkerlin/torch/pkg/paths/build
[ 50%] Linking C shared module libpaths.so
Undefined symbols for architecture x86_64:
  "_luaL_checklstring", referenced from:
      _lua_filep in paths.c.obj
      _lua_dirp in paths.c.obj
      _lua_basename in paths.c.obj
      _lua_dirname in paths.c.obj
      _lua_extname in paths.c.obj
      _lua_concatfname in paths.c.obj
      _lua_dir in paths.c.obj
      ...
  "_luaL_error", referenced from:
      _lua_getregistryvalue in paths.c.obj
      _path_require in paths.c.obj
  "_luaL_gsub", referenced from:
      _path_require in paths.c.obj
  "_luaL_optlstring", referenced from:
      _lua_basename in paths.c.obj
  "_luaL_register", referenced from:
      _luaopen_libpaths in paths.c.obj
  "_lua_call", referenced from:
      _lua_mkdir in paths.c.obj
      _path_require in paths.c.obj
  "_lua_concat", referenced from:
      _path_require in paths.c.obj
  "_lua_createtable", referenced from:
      _luaopen_libpaths in paths.c.obj
      _lua_dir in paths.c.obj
      _lua_tmpname in paths.c.obj
  "_lua_error", referenced from:
      _path_require in paths.c.obj
  "_lua_getfield", referenced from:
      _path_require in paths.c.obj
  "_lua_gettop", referenced from:
      _lua_concatfname in paths.c.obj
  "_lua_isuserdata", referenced from:
      _lua_tmpname in paths.c.obj
      _gc_tmpname in paths.c.obj
  "_lua_newuserdata", referenced from:
      _lua_tmpname in paths.c.obj
  "_lua_pushboolean", referenced from:
      _lua_filep in paths.c.obj
      _lua_dirp in paths.c.obj
      _lua_mkdir in paths.c.obj
      _lua_rmdir in paths.c.obj
      _path_require in paths.c.obj
  "_lua_pushcclosure", referenced from:
      _lua_tmpname in paths.c.obj
      _lua_mkdir in paths.c.obj
      _path_require in paths.c.obj
  "_lua_pushfstring", referenced from:
      _lua_mkdir in paths.c.obj
      _lua_rmdir in paths.c.obj
      _path_require in paths.c.obj
  "_lua_pushinteger", referenced from:
      _lua_mkdir in paths.c.obj
      _lua_rmdir in paths.c.obj
  "_lua_pushlightuserdata", referenced from:
      _lua_tmpname in paths.c.obj
  "_lua_pushlstring", referenced from:
      _lua_basename in paths.c.obj
      _lua_dirname in paths.c.obj
      _lua_cwd in paths.c.obj
      _lua_concatfname in paths.c.obj
      _lua_dir in paths.c.obj
      _path_require in paths.c.obj
  "_lua_pushnil", referenced from:
      _lua_execdir in paths.c.obj
      _lua_dir in paths.c.obj
      _lua_tmpname in paths.c.obj
      _lua_mkdir in paths.c.obj
      _lua_rmdir in paths.c.obj
  "_lua_pushstring", referenced from:
      _lua_dirname in paths.c.obj
      _lua_extname in paths.c.obj
      _lua_cwd in paths.c.obj
      _lua_tmpname in paths.c.obj
      _lua_uname in paths.c.obj
      _path_require in paths.c.obj
  "_lua_pushvalue", referenced from:
      _luaopen_libpaths in paths.c.obj
      _lua_mkdir in paths.c.obj
  "_lua_rawget", referenced from:
      _lua_tmpname in paths.c.obj
  "_lua_rawset", referenced from:
      _lua_tmpname in paths.c.obj
  "_lua_rawseti", referenced from:
      _lua_dir in paths.c.obj
  "_lua_remove", referenced from:
      _lua_concatfname in paths.c.obj
      _path_require in paths.c.obj
  "_lua_replace", referenced from:
      _path_require in paths.c.obj
  "_lua_setfield", referenced from:
      _luaopen_libpaths in paths.c.obj
      _lua_tmpname in paths.c.obj
      _path_require in paths.c.obj
  "_lua_setmetatable", referenced from:
      _lua_tmpname in paths.c.obj
  "_lua_settop", referenced from:
      _lua_tmpname in paths.c.obj
      _path_require in paths.c.obj
  "_lua_toboolean", referenced from:
      _path_require in paths.c.obj
  "_lua_tolstring", referenced from:
      _lua_concatfname in paths.c.obj
      _path_require in paths.c.obj
  "_lua_touserdata", referenced from:
      _lua_tmpname in paths.c.obj
      _gc_tmpname in paths.c.obj
  "_lua_type", referenced from:
      _path_require in paths.c.obj
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libpaths.so] Error 1
make[1]: *** [CMakeFiles/paths.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.

**Comment by soumith** [comment]
please open these threads in our google groups:
https://groups.google.com/forum/#!forum/torch7

or under distro:
https://github.com/torch/distro
