### ISSUE TITLE
Cannot build torch7 in Ubuntu 32bit 15.04

### ISSUE THREAD

**Issue by linkerlin** [torch/torch7#413]
~/torch/install$ cat install.log 
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Found readline library
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Looking for dlopen
-- Looking for dlopen - found
-- Looking for sin in m
-- Looking for sin in m - found
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test LJ_TARGET_X64
-- Performing Test LJ_TARGET_X64 - Failed
-- Performing Test LJ_TARGET_X86
-- Performing Test LJ_TARGET_X86 - Success
-- LuaJIT Target: x86
-- LuaJIT target x86
-- Performing Test LJ_ARCH_BITS_64
-- Performing Test LJ_ARCH_BITS_64 - Failed
-- Performing Test LJ_HASJIT_1
-- Performing Test LJ_HASJIT_1 - Success
-- Performing Test LJ_HASFFI_1
-- Performing Test LJ_HASFFI_1 - Success
-- Performing Test LJ_DUALNUM_1
-- Performing Test LJ_DUALNUM_1 - Failed
-- Performing Test LJ_ARCH_HASFPU_1
-- Performing Test LJ_ARCH_HASFPU_1 - Success
-- Performing Test LJ_ABI_SOFTFP_1
-- Performing Test LJ_ABI_SOFTFP_1 - Failed
-- Performing Test __SSE2___1
-- Performing Test __SSE2___1 - Failed
-- Looking for sin in m
-- Looking for sin in m - found
-- Found Wget: /usr/bin/wget  
-- Found MD5: /usr/bin/md5sum  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/linker/torch/build
Scanning dependencies of target minilua
[  3%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/minilua.dir/src/host/minilua.c.o
Linking C executable minilua
[  3%] Built target minilua
[  7%] Generating buildvm_arch.h
Scanning dependencies of target buildvm
[ 11%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/buildvm.dir/src/host/buildvm.c.o
[ 15%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/buildvm.dir/src/host/buildvm_asm.c.o
[ 19%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/buildvm.dir/src/host/buildvm_peobj.c.o
[ 23%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/buildvm.dir/src/host/buildvm_lib.c.o
[ 26%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/buildvm.dir/src/host/buildvm_fold.c.o
Linking C executable buildvm
[ 26%] Built target buildvm
[ 30%] Generating vmdef.lua
[ 34%] Generating lj_vm.s
[ 38%] Generating lj_ffdef.h
[ 42%] Generating lj_bcdef.h
[ 46%] Generating lj_libdef.h
[ 50%] Generating lj_recdef.h
[ 53%] Generating lj_folddef.h
Scanning dependencies of target libluajit
[ 57%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/libluajit.dir/src/ljamalg.c.o
[ 61%] Building ASM object exe/luajit-rocks/luajit-2.1/CMakeFiles/libluajit.dir/lj_vm.s.o
Linking C shared library libluajit.so
[ 61%] Built target libluajit
Scanning dependencies of target luajit
[ 65%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/src/luajit.c.o
[ 69%] Building C object exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/src/ljamalg.c.o
[ 73%] Building ASM object exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/lj_vm.s.o
Linking C executable luajit
exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/build.make:220: recipe for target 'exe/luajit-rocks/luajit-2.1/luajit' failed
CMakeFiles/Makefile2:184: recipe for target 'exe/luajit-rocks/luajit-2.1/CMakeFiles/luajit.dir/all' failed
Makefile:117: recipe for target 'all' failed

**Comment by soumith** [comment]
please open these threads in our google groups:
https://groups.google.com/forum/#!forum/torch7

or under distro:
https://github.com/torch/distro
