### ISSUE TITLE
Cannot convert from DoubleTensor to LongTensor

### ISSUE THREAD

**Issue by dewoller** [torch/torch7#414]
I can copy a tensor using the idiom from the documentation:
``` lua
x=torch.rand(4,4) * 10
y = torch.Tensor(x:size()):copy(x)
```

I can convert data storage type, using any of the following idiom (starting from a Double tensor)
``` lua
x=torch.rand(4,4) * 10
yDouble = torch.DoubleTensor(x:size()):copy(x)
yChar = torch.CharTensor(x:size()):copy(x)
yByte = torch.ByteTensor(x:size()):copy(x)
yFloat = torch.FloatTensor(x:size()):copy(x)
```
The following gives me an error:
```lua
yLong = torch.LongTensor(x:size()):copy(x)
```
``` 
/store/torch/bin/luajit: error.lua:7: inconsistent tensor size at /tmp/luarocks_torch-scm-1-2563/torch7/lib/TH/generic/THTensorCopy.c:22
stack traceback:
	[C]: in function 'copy'
	error.lua:7: in main chunk
	[C]: in function 'dofile'
	/store/torch/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
	[C]: at 0x00406260
```
I should be able to convert from DoubleTensor to LongTensor

**Comment by albanD** [comment]
Your problem is that `x:size()` is a LongTensor.
Thus the command `torch.LongTensor(x:size())` will create a new LongTensor that is a copy of `x:size()` (and not a LongTensor whose size is the same as x).
What you want is:
```lua
yLong = torch.LongTensor():resize(x:size()):copy(x)
```

**Comment by fmassa** [comment]
As @albanD mentioned, there are actually several constructors for `torch.Tensor`.
Have a look at https://github.com/torch/torch7/blob/master/doc/tensor.md#torchtensorsizes-strides and https://github.com/torch/torch7/blob/master/doc/tensor.md#torchtensorstorage-storageoffset-sizes-strides
