### ISSUE TITLE
torch.multinomial precision issues

### ISSUE THREAD

**Issue by DavidGrangier** [torch/torch7#418]
torch multinomial has precision issues. When the probabilities are given as float, then torch.multinomial(res, p, n, true) does not sample rare events.

The following example should result in ~100,000 samples within 50,001-100,000 range.
With p stored in double, it does. With p stored in float it result in 0 sample within that range.

do
  p = torch.FloatTensor(100*1000):fill(1)
  p:narrow(1, 50*1000 + 1, 50*1000):fill(1e-3)
  p:div(p:sum())
  N = 100*1000

  n = 0
  c = torch.LongTensor(p:nElement()):zero()
  c_ptr = c:data() - 1
  tmp = torch.LongTensor()
  for i = 1, 1000 do
    p.multinomial(tmp, p, N, true);
    n = n + N
    tmp:apply(function(i) c_ptr[i] = c_ptr[i] + 1 end)
  end

  actual = c:narrow(1, 50001, 50000):sum()
  expected = n*p:narrow(1, 50001, 50000):sum()
  print(actual, expected)
end

**Comment by noa** [comment]
My solution was to implement versions of torch.multinomial and cutorch.multinomial that work in log-space. If there's any interest I can clean these up as a PR.

**Comment by nicholas-leonard** [comment]
Yes, please send a PR!

**Comment by andresy** [comment]
computing he cumulative distrib in double instead of float would solve the issue.
