### ISSUE TITLE
PATH manipulation in install script

### ISSUE THREAD

**Issue by Phyks** [torch/torch7#419]
Hi,

The install script currently prepends torch install directory to the `$PATH` variable, in our `.bashrc`/`.zshrc`. However, I think it should not prepend but append.

Indeed, `$PATH` is parsed from left to right, and the directory on the left has then the highest priority. For a local install, the install directory is easily accessible (by the user, and by malicious scripts / users), which can put their some executables with the same names as common ones (say `cd` or even worse `ssh`) and the original ones will be hidden, which results in a security risk.

Moreover, for ZSH, I think that the `$PATH` definition should go to `.zshenv` and not `.zshrc` (at least, the prepending did not work on my setup because my `$PATH` definition is in `.zshenv` and there is no such things in `.zshrc` so the lines were not added correctly).

Thanks

**Comment by soumith** [comment]
we prepend because we want to take precedence over any system-installed luarocks. We ship our own luarocks utility

**Comment by soumith** [comment]
the ZSH stuff probably has to be fixed. Would you send in a patch? I dont use ZSH

**Comment by Phyks** [comment]
@soumith I can have a look for a ZSH patch.

For the precedence, I understand your point, but for me this results in a big security risk on most systems. Maybe a compromise would be to check that `luarocks` is installed and prepend / append depending on this (although I agree the Torch installation may break in the future due to this).

Else, maybe hilighting the security risk in automatically prepending to the `$PATH` in the install risk would be a good thing, I think.

Finally, I am quite new to Lua and Torch and do not know much of this, but isn't it possible to use some kind of `virtualenv`-like behavior? (by tweaking the `$LUA_PATH` or something like this, I guess)

**Comment by soumith** [comment]
virtualenv like behavior can indeed be done by setting the LUA_PATH and LUA_CPATH variables.

Also, let's continue the conversation in the correct repo here: https://github.com/torch/distro/issues

**Comment by Phyks** [comment]
Sorry for the issue posted in the wrong repo =(
