### ISSUE TITLE
not enough memory  on Ubuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by taras-sereda** [torch/torch7#423]
I've tried to create huge Tensor of size:
a = torch.Tensor(50000, 3 ,224 ,224)

On my laptop Mac Os - no problems with such Tensor size.

but on Ubuntu 14.04.2 LTS which I use on Amazon EC2 I have the following error:
$ Torch: not enough memory: you tried to allocate 56GB. Buy new RAM! at /home/ubuntu/torch/pkg/torch/lib/TH/THGeneral.c:222
stack traceback:
	[C]: at 0x7fed838b2680
	[C]: in function 'Tensor'
	[string "a = torch.Tensor(50000, 3 ,224 ,224)"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/ubuntu/torch/install/share/lua/5.1/trepl/init.lua:648: in function 'repl'
	...untu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
	[C]: at 0x00406670

Are there any branches where this issue fixed? Or can somebody provide a sultion on how to fix this problem. 
Regards. Taras

**Comment by fmassa** [comment]
Indeed, this huge tensor requires around 60GB of RAM memory.
What might be happening is that, as the tensor is not initialized, in Mac OS, maybe the memory is not really allocated.
Try in your Mac OS doing
```lua
a = torch.Tensor(50000,3,224,224):zero()
```
but beware that your computer might freeze of out of memory, and start swapping with CPU.

**Comment by taras-sereda** [comment]
Yes, when I've tried to allocate tensor and fill it with zeros - it freezed  on Mac Os.
Here I'll use smaller tensor dimensions.but the interesting point is, that even
``` 
a = torch.Tensor(10,10):

**Comment by fmassa** [comment]
hum... interesting....
Could you try doing something like
```lua
a = torch.Tensor(10,10):fill(1)
b = torch.Tensor(10,10)
torch.eq(a,b)
```
I don't have a MacOS to check, but maybe what you are seeing are some optimizations of the memory allocation in MacOS, which is trying to be smart. Check this issue as well https://github.com/torch/torch7/issues/229

**Comment by taras-sereda** [comment]
I've tried on MacOS. They are different.
Thanks for the reference. Looking through it now.
```
th> a = torch.Tensor(10,10):fill(1)
                                                                      [0.0001s]	
th> b = torch.Tensor(10,10)
                                                                      [0.0000s]	
th> torch.eq(a,b)
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
[torch.ByteTensor of size 10x10]
```

**Comment by fmassa** [comment]
@taras-sereda I don't think it's an issue in torch itself, its just a difference in behaviour between OSX and Ubuntu's `malloc`.

**Comment by taras-sereda** [comment]
@fmassa  probably you are right. Thanks for your help!
I'm closing the issue then.
