### ISSUE TITLE
Torch nn slower after git update

### ISSUE THREAD

**Issue by vbalnt** [torch/torch7#430]
Hi, 

I did an update by `git pull origin master` and run my usual experiments, and it seems that now
torch is around 10 times slower in terms of a simple CNN optimization problem with batches. 

I also noticed that the GPU card is not in full usage. 

Did anyone experience a similar problem at some point?

**Comment by soumith** [comment]
Open an issue here: https://github.com/torch/cunn/issues with a small script to help reproduce the issue. Also give some details on what GPU you are using, and what numbers you saw before/after.
