### ISSUE TITLE
luaT build error!

### ISSUE THREAD

**Issue by subodhp** [torch/torch7#435]
Hello Team,

I am a newbie to ML and subsequently to torch. 
Trouble is compiling torch7 from scratch. 
In the torch7-master, directory after successful execution of cmake, the make is giving error at the luaT.
The luaT at /lib directory is not doing a successful cmake. The TH is building fine.

The error I am getting is,

CMake Error at CMakeLists.txt:23 (INSTALL):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "luaT".

This might be a minor change. 

Looking forward for assistance.

Thanks,
Subodh

**Comment by soumith** [comment]
Hey Subodh,

Happy to help you further on the google groups for your install issue:
https://groups.google.com/forum/#!forum/torch7

Looking forward to your post there.
--
S
