### ISSUE TITLE
problem with local function declaration

### ISSUE THREAD

**Issue by LukeOeding** [torch/torch7#437]
I'm new to torch and I'm having trouble running through the tutorial
[http://tylerneylon.com/a/learn-lua/]. I think this issue is with local functions. If I write the function as local I get an error.  If I remove the "local" declaration, it works fine.  Any ideas what might be happening here?

      ______             __   |  Torch7                                         
     /_  __/__  ________/ /   |  Scientific computing for Lua. 
      / / / _ \/ __/ __/ _ \  |  Type ? for help                                
     /_/  \___/_/  \__/_//_/  |  https://github.com/torch         
                              |  http://torch.ch                  
	
    th> local function g(x) return math.sin(x) end
                                                                          [0.0000s]	
    th> g(1)
    [string "_RESULT={g(1)}"]:1: attempt to call global 'g' (a nil value)
    stack traceback:
    	[string "_RESULT={g(1)}"]:1: in main chunk
    	[C]: in function 'xpcall'
    	/Users/oeding/torch/install/share/lua/5.1/trepl/init.lua:630: in function 'repl'
    	...ding/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:187: in main chunk
    	[C]: at 0x010f3d82d0	
                                                                          [0.0002s]	
    th> function g(x) return math.sin(x) end
                                                                          [0.0000s]	
    th> g(1)
    0.8414709848079	
                                                                          [0.0000s]

**Comment by soumith** [comment]
hey Luke,

The issue tracker is used for bugs and issues wrt development.

Can you post your questions in the google groups where we help out with user support.
https://groups.google.com/forum/#!forum/torch7

**Comment by LukeOeding** [comment]
Hi Soumith,
Sorry for misplacing the comment, and thanks for the direction.

Luke
