### ISSUE TITLE
Tensor constructor for IntTensor, etc

### ISSUE THREAD

**Issue by eulerreich** [torch/torch7#441]
When I do

```lua
local a = torch.IntTensor(3, 4)
print(torch.Tensor(a))
```
I get an error

```lua
bad argument #1 to '?' (expecting number or Tensor or Storage at /tmp/luarocks_torch-scm-1-2006/torch7/generic/Tensor.c:1092)
stack traceback:
	[C]: at 0x7f95f6bef560
	[C]: in function 'Tensor'
	[string "local a = torch.IntTensor(3, 4)..."]:2: in main chunk
	[C]: in function 'xpcall'
	/home/greg/torch/install/share/lua/5.1/itorch/main.lua:179: in function </home/greg/torch/install/share/lua/5.1/itorch/main.lua:143>
	/home/greg/torch/install/share/lua/5.1/lzmq/poller.lua:75: in function 'poll'
	/home/greg/torch/install/share/lua/5.1/lzmq/impl/loop.lua:307: in function 'poll'
	/home/greg/torch/install/share/lua/5.1/lzmq/impl/loop.lua:325: in function 'sleep_ex'
	/home/greg/torch/install/share/lua/5.1/lzmq/impl/loop.lua:370: in function 'start'
	/home/greg/torch/install/share/lua/5.1/itorch/main.lua:350: in main chunk
	[C]: in function 'require'
	[string "arg={'/run/user/1000/jupyter/kernel-3ec1dfcb-..."]:1: in main chunk
```

Same thing with ByteTensor, etc

**Comment by albanD** [comment]
I am not sure what you are trying to do

* If you want to create a clone of `a` then you should use `torch.IntTensor(a)` because by default `torch.Tensor` is a `torch.DoubleTensor`
* If you want to create a `torch.Tensor` of size (3, 4) then two things:
    * `torch.IntTensor(3, 4)` will create a Tensor of size (3, 4) with unitialized memory, if you want it to contains the number 3 and 4 you should do `torch.IntTensor({3, 4})`
    * To construct a tensor from a tensor containing its size, the second one must be a `torch.LongStorage` see the doc [here](https://github.com/torch/torch7/blob/master/doc/tensor.md#torchtensorsizes-strides)

So in the second case, the code will be:
```lua
local a = torch.LongStorage({3, 4})
print(torch.Tensor(a))
```
And if your script gives you an `IntTensor` and you want to create a `torch.Tensor` from it:
```lua
local a = torch.IntTensor({3, 4})
local size = a:long():storage() -- convert to a LongStorage
print(torch.Tensor(size))
```

**Comment by eulerreich** [comment]
OK I see. In my case I wanted to split the tensor up into 2 tensors, one with the even-numbered elements and other odd, so I had to use the torch.Tensor constructor with stride. I simplified the code to give the example here.

I assumed torch.Tensor is a generic constructor; so it's specific to Double?

In any case, I think the error message should be clearer, since I did pass in a Tensor (just not Double).

**Comment by albanD** [comment]
`torch.Tensor` points to what is given by the [`torch.setdefaulttensortype](https://github.com/torch/torch7/blob/a0b2db6f0d0a0657ddf1f4608d973138a58830ad/doc/utility.md#torchsetdefaulttensortypetypename) function. The default if you don't call this function is `torch.DoubleTensor`

I will see if we can improve this error message, thanks for the feedback.
