### ISSUE TITLE
MultiGPU and DataParallel in torch(without fbcunn)

### ISSUE THREAD

**Issue by lglhuada** [torch/torch7#449]
Hi I am very new to torch. 
![torch_multigpu](https://cloud.githubusercontent.com/assets/5636133/11029471/246954a8-8702-11e5-8665-ff81e97fa523.png)
As I read from https://github.com/torch/cutorch/issues/42 , the multi-gpu solution is not real data parallel computation, right? Actually the forward, backward can be done in different gpus. I read the imagenet-Multigpu example, how did you copy data cross gpus in the trainBatch function?

**Comment by soumith** [comment]
please use our forums https://groups.google.com/forum/#!forum/torch7 for support.

**Comment by lglhuada** [comment]
hi soumith, thanks for your information. Do you have any ideas to my questions( fbcunn is not available)? Thanks in advance.
