### ISSUE TITLE
Replicating the essence of TensorFlow

### ISSUE THREAD

**Issue by andreaskoepf** [torch/torch7#452]
What is the essence of tf [[1]](https://github.com/tensorflow/tensorflow), [[2]](http://download.tensorflow.org/paper/whitepaper2015.pdf) and how could we integrate it into Torch?

One of the interesting points (not yet released?) of TensorFlow seems to be its capability to automatically evaluate graphs by intelligently scheduling data transport and execution across multiple machines and even being able to handle models larger than single-node memory. But it might be over-kill to replicate these features at the level Google tries to solve the problem.

Is tf over-engineered? I am personally not convinced that automatic distributed computation can be a universal solution freeing the machine learning practitioner from understanding which computations happen locally on a node and when slow network transfer takes in: For me it looks comparable to use of swap-files which give some freedom but are not the universal solution for memory-bound problems - e.g. the developer has to understand the system in order to leverage the full pontential of his/her hardware.

A general question is: How optimal can an automatic scheduling and data transport system actually operate, for which scenarios will this be the winning solution compared to hand-designed distribution schemes? What is the primary demand for distributed computation in the torch-community? I guess currently the majority of the Torch users will have 1-4 machines with each 1-4 GPUs. 

Can we come up with a simpler 'deep learning in your garage' solution?

@soumith came up with the [idea](https://gist.github.com/soumith/4a756212a2876572e3f4) of a light-weight distributed computation system:

> What would've been cooler is if you could create arbitrary serializable closures (like Lua functions for example, or C/C++ functions tagged with a shared-object) that can be scheduled at arbitrary nodes, with no restrictions. That would be a much lower barrier for development.

I support this idea and I am willing to help making this real!

Just to collect some links:

automatic-differentiation: https://github.com/twitter/torch-autograd
MPI: https://github.com/sixin-zh/mpiT
Shared tensor: https://github.com/Hello1024/shared-tensor
Multi-GPU: https://github.com/soumith/imagenet-multiGPU.torch

It would be great if other torch users could state which technical aspects of tf might be worth replicating. Who is interested in executiong distributed computations with torch, what are you using today?

**Comment by clementfarabet** [comment]
This is very much our view – we're planning on releasing a more structured version of torch-autograd which is going to expose the generated directed graph. From this graph we currently spit out one single Lua function, with automatically generated intermediate variables (tensors and numbers). From this graph you'll be able to add annotations, and this is how we plan to integrate with our internal distributed learning stack. I really think it's the right level of abstraction.

**Comment by soumith** [comment]
Looks like the twitter folks released closure dispatching packages:
https://blog.twitter.com/2016/distributed-learning-in-torch
