### ISSUE TITLE
Not enough memory when using torch.save()

### ISSUE THREAD

**Issue by fairylrt** [torch/torch7#454]
I'm trying to use torch.save() to save a table.
The table consists nearly 330 MB data, however, the program tell me not enough memory which is quite weird.
Why does that happen?

**Comment by yoosan** [comment]
I have the same problem, and I always happen segmentation fault. 
When I use torch, there happen many unhappy things.

**Comment by bneiluj** [comment]
Can you please post the entire code ?

**Comment by soumith** [comment]
Can you please use the forums for support: https://groups.google.com/forum/#!forum/torch7
Thanks.
