### ISSUE TITLE
Errors when DataParallelTable from cunn is used

### ISSUE THREAD

**Issue by lglhuada** [torch/torch7#458]
Do you guys know how to construct data form DataParallelTable from cunn. I changed a CNN into a dataparallel manner and the rest parts of my project is not modified, input data is {batchsize, framechannel, highth, width}. While I always got the error:

/root/torch/install/bin/luajit: invalid arguments: number 
expected arguments: [*CudaTensor*] CudaTensor
stack traceback:
	[C]: at 0x7f7e31db1ea0
	[C]: in function 'round'
	...t/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:490: in function '_calculateSliceRange'
	...t/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:527: in function '_distributeTensorRecursive'
	...t/torch/install/share/lua/5.1/cunn/DataParallelTable.lua:282: in function 'forward'
	train.lua:151: in function 'opfunc'
	/root/torch/install/share/lua/5.1/optim/sgd.lua:43: in function 'sgd'
	train.lua:185: in function 'train'
	train.lua:306: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x004064a0

Actually a number can be argument into torch.round function, do I need to reconstruct the data as {batchsize, #GPUs, framechannel, height, width}?

Thanks&Best,
guangliang

**Comment by Kaixhin** [comment]
If you have an issue with cunn, please raise it in the [appropriate repo](https://github.com/torch/cunn/issues).

If you are following the [example](https://github.com/torch/cunn/blob/master/doc/cunnmodules.md#dataparalleltable), you'll notice that `nn.DataParallelTable` takes the dimension to split as its only argument (and it would usually be 1 - the batch dimension), so you don't have to adjust your data. Additionally you'll see casting the model via `:cuda()`, so your data will have to be of type `torch.CudaTensor`, which is what your error is indicating.
