### ISSUE TITLE
Please add direct link to https://github.com/torch/torch7/wiki/Cheatsheet

### ISSUE THREAD

**Issue by hughperkins** [torch/torch7#462]
I think this repo's README.md should link directly to https://github.com/torch/torch7/wiki/Cheatsheet  It's very hard to find.

**Comment by andreaskoepf** [comment]
+1 .. and please also link to the fantastic http://torch.ch/blog/

**Comment by andreaskoepf** [comment]
btw hard to find but also excellent content: https://github.com/soumith/cvpr2015/blob/master/cvpr-torch.pdf

**Comment by soumith** [comment]
good suggestions. Anyone want to send a PR?
