### ISSUE TITLE
the torch ami can't find the nvidia driver on reboot

### ISSUE THREAD

**Issue by eulerreich** [torch/torch7#464]
After rebooting the g2.2xlarge instance, running `nvidia-smi` gave errors like "can't find nvidia driver. Make sure it's installed and running." More importantly cunn doesn't import.
I found the install package for it in the `~/download` folder, however, and ran `sudo ./NVIDIA-Linux-x86_64-340.29.run`, which reinstalled the driver and it worked.

**Comment by soumith** [comment]
hey @eulerreich , please use this issues page only for bug fixes and issues of the core torch7 library. For a general group, I suggest: https://groups.google.com/forum/#!forum/torch7

**Comment by soumith** [comment]
And also, thanks for the info :)
