### ISSUE TITLE
CharTensor appears to be unsigned

### ISSUE THREAD

**Issue by dm-jrae** [torch/torch7#469]
> =torch.CharTensor{-1}
 255
[torch.CharTensor of size 1]

> return torch.CharTensor{-1}:storage()
 255
[torch.CharStorage of size 1]

However CharTensor should be signed:
https://github.com/torch/torch7/blob/master/lib/TH/THGenerateAllTypes.h#L17
This seems like quite a nasty bug, does anyone know where the evil sorcery is taking place?

**Comment by fmassa** [comment]
It seems that the C standard doesn't specify if `char` is signed or unsigned, and it's implementation specific. Apparently, gcc implementation considers that it's unsigned by default.

**Comment by dm-jrae** [comment]
Thanks @fmassa for the quick response. Good to know :-)
