### ISSUE TITLE
module 'cwrap' not found

### ISSUE THREAD

**Issue by pannous** [torch/torch7#47]
Even after the successful installation of cwrap*\* and cleaning we cannot successfully manage to compile the project:

$ make
[ 3%] Built target TH
[ 44%] Built target luaT
[ 48%] Generating random.c
lua: random.lua:1: module 'cwrap' not found:
Failed loading module cwrap in LuaRocks rock cwrap scm-1

Any advice?

*\* cwrap installation successful:
$ luarocks --local --server=https://raw.github.com/torch/rocks/master install cwrap
Installing https://raw.github.com/torch/rocks/master/cwrap-scm-1.rockspec...
Using https://raw.github.com/torch/rocks/master/cwrap-scm-1.rockspec... switching to 'build' mode
Cloning into 'cwrap'...
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 8 (delta 0), reused 5 (delta 0)
Receiving objects: 100% (8/8), 9.80 KiB | 0 bytes/s, done.
Checking connectivity... done.
Updating manifest for $/.luarocks/lib/luarocks/rocks

cwrap scm-1 is now built and installed in $/.luarocks (license: BSD)

**Comment by jiapei100** [comment]
@pannous How to deal with it anyway?
Where to add
`#!/usr/bin/env lua -lluarocks.loader` ???

Thank you ...
In file CMakeLists.txt? which line???
