### ISSUE TITLE
Loop or previous error loading module 'torch'

### ISSUE THREAD

**Issue by esling** [torch/torch7#482]
Working on Mac OSX 10.10.5, I just updated to the new version of torch and now get this error.

/usr/bin/torch/install/bin/luajit: /usr/bin/torch/install/share/lua/5.1/trepl/init.lua:363: /usr/bin/torch/install/share/lua/5.1/trepl/init.lua:363: /usr/bin/torch/install/share/lua/5.1/trepl/init.lua:363: /usr/bin/torch/install/share/lua/5.1/trepl/init.lua:363: loop or previous error loading module 'torch'

The previous version (installed around september) worked just fine. I also tried several "fixes" proposed for other modules such as cunn (check for symlinks) or cutorch (rebuild from source) but none worked.

Any idea ?

**Comment by soumith** [comment]
Can you use this group to request support: https://groups.google.com/forum/#!forum/torch7
I'll reply there, should be easy to figure out the issue.
