### ISSUE TITLE
Torch.cat with FloatTensor does not work

### ISSUE THREAD

**Issue by RicherMans** [torch/torch7#490]
Hey there, so I recently came across this problem, that via default torch.cat() does not support any FloatTensors. I don't know why this behavior is intended, would be cool if somebody could explain.

```lua

a={torch.Tensor(10,3):fill(5),torch.Tensor(30,3):fill(3)}
torch.cat(a,1)
-- Works fine, since its double Tensors
b={torch.FloatTensor(10,3):fill(5),torch.FloatTensor(30,3):fill(3)}
torch.cat(b,1)
-- Error: expected DoubleTensor in tensor array
```

I didn't see anything in the Docs why this is only limited to doubletensors.

**Comment by fmassa** [comment]
@RicherMans check the comments in https://github.com/torch/torch7/pull/350

**Comment by RicherMans** [comment]
Thanks!
