### ISSUE TITLE
overload operators for tensors: '<', '>', '==', etc.

### ISSUE THREAD

**Issue by yangky11** [torch/torch7#495]
Hi,

Do you think it's good to have overloaded operators as syntatic sugar for torch.lt(), torch.gt(), torch.eq(), etc. ?

**Comment by soumith** [comment]
At the moment, there is an expectation of == by users is that it only is equal if it's the same tensor. 
<  and > can be overloaded I suppose.

**Comment by pakozm** [comment]
I'm not sure how this affects, but [Lua 5.1 manual](http://www.lua.org/manual/5.1/manual.html#2.5.2) says:

> The relational operators in Lua are
>
>     ==    ~=    <     >     <=    >=
> These operators always result in false or true.

And it seems that someone tried before and [asked it in stackoverflow](http://stackoverflow.com/questions/10951942/lua-metatable-lt-le-eq-forced-boolean-conversion-of-return-value).

Nevertheless, if you try, I will be interested in the result :-)

**Comment by soumith** [comment]
Francisco is right. So no :)
