### ISSUE TITLE
issue while calling lua/torch executable(created with srlua) from posix-spawn c++ on  Linux 12.04

### ISSUE THREAD

**Issue by mayurgw** [torch/torch7#497]
Hi my lua file is like:
--
print("Entered")
require 'image'
/*some code */

--
I create executable throught srlua package lets ABC.out

When i call this from my cpp file through posix_spawn

i get this error:

Entered
1: module 'image' not found:
	no field package.preload['image']
	no file './image.lua'
	no file '/usr/local/share/lua/5.1/image.lua'
	no file '/usr/local/share/lua/5.1/image/init.lua'
	no file '/usr/local/lib/lua/5.1/image.lua'
	no file '/usr/local/lib/lua/5.1/image/init.lua'
	no file '/usr/share/lua/5.1/image.lua'
	no file '/usr/share/lua/5.1/image/init.lua'
	no file './image.so'
	no file '/usr/local/lib/lua/5.1/image.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/image.so'
	no file '/usr/lib/lua/5.1/image.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

this works perfectly i just call normally from terminal as ./ABC.out.
I have installed lua as: sudo apt-get install lua5.1
and torch as mentioned here "http://torch.ch/docs/getting-started.html#_" .
I think there is some path issue.
It would be great if someone can help me

**Comment by soumith** [comment]
try using our forums for help: https://groups.google.com/forum/#!forum/torch7
