### ISSUE TITLE
Runing a Custom Torch

### ISSUE THREAD

**Issue by TalhaMetu** [torch/torch7#502]
Hi all,

I am trying to run the code provided by Weakly Supervised Object Recognition with Convolutional Neural Networks, here : 
http://www.di.ens.fr/willow/research/weakcnn/

They gave a custom version of torch. I install cuda 7.5 to Ubuntu 14.04 and install dependecies of torch then follow the simple instructions they gave at code which is : 
mkdir build	
	cd build
	cmake .. -DCMAKE_INSTALL_PREFIX=$PWD
	make -j12 install
After compiling the code, luarocks and lua commands responds. But when i write th, it says command not found.
Any idea how to fix this problem?

Thank you very much for your time and your valuable answers.

**Comment by soumith** [comment]
Please use our google groups mailing list for questions. The issue tracker is for bug reports.
