### ISSUE TITLE
Unable to compile Torch on ARM (Nvidia Jetson TK1)

### ISSUE THREAD

**Issue by SyRenity** [torch/torch7#504]
Trying to compile Torch on Jetson TK1, getting error due to missing call_arm.h.

Generating the call_arm.h manually via:
luajit dynasm/dynasm.lua -LN -o call_arm.h call_arm.dasc 

and trying to compile it brings following errror:
```
In file included from call.c:47:0:
call_arm.h:633:64: error: unknown type name ‘function_t’
 static void compile_extern_jump(struct jit* jit, lua_State* L, function_t func, uint8_t* code)                                                                ^
...
```
Opened issue for luaffifb, they say changes are needed to their source:
https://github.com/facebook/luaffifb/issues/6

Is this a recent dependancy? I succesfully compiled Torch on TK1 a month before, without such issues.
Can it be disabled and Torch compiled without it?

**Comment by spinpx** [comment]
Meet the same problem. Are you solved this ? Thanks

**Comment by SyRenity** [comment]
Not yet, going to try older version of torch soon which apparently didn't
have this dependency.

**Comment by soumith** [comment]
fixed in luaffifb.
