### ISSUE TITLE
torch/install/share/lua/5.1/torch/File.lua:298: read error: read 25 blocks instead of 100

### ISSUE THREAD

**Issue by zultuta** [torch/torch7#505]
I am working on transferring torch tensors over a computer network. I serialize the tensor..transfer over the LAN  and deserialize on the other end. I tried it out with small tensors which i generated using the torch.rand function. for example.. 
 
a = torch.rand(5,1)   -- random tensor generated
str = torch.serialize(a)   --serialize ..then i send serialized data through network.

using the above for example, i could receive the serialized string sent by the client  successfully from the other end(server) and deserialize back it the original tensor.

but if i use a larger tensore like torch.rand(100,1), when i run the server code to receive serialized strings over the network, i get errors like as below:

zulqornain@zulqornain-HP-EliteDesk-800-G1-TWR:~$ th listener.lua
Binding to host '*' and port 9093
Waiting connection from client on 0.0.0.0:9093
/home/zulqornain/torch/install/bin/luajit: /home/zulqornain/torch/install/share/lua/5.1/torch/File.lua:298: read error: read 25 blocks instead of 100 at /home/zulqornain/torch/pkg/torch/lib/TH/THMemoryFile.c:347
stack traceback:
	[C]: in function 'read'
	/home/zulqornain/torch/install/share/lua/5.1/torch/File.lua:298: in function </home/zulqornain/torch/install/share/lua/5.1/torch/File.lua:212>
	[C]: in function 'read'
	/home/zulqornain/torch/install/share/lua/5.1/torch/File.lua:298: in function 'readObject'
	/home/zulqornain/torch/install/share/lua/5.1/torch/File.lua:378: in function 'deserialize'
	listener.lua:24: in main chunk
	[C]: in function 'dofile'
	...nain/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

Please advice on this will be most appreciated
Thanks

**Comment by soumith** [comment]
This is an issue with your network transfers. The networking code is probably chunking the transfer, and you are attempting to deserialize a partial chunk.

**Comment by zultuta** [comment]
ok, Thanks

**Comment by sankethvedula** [comment]
Hi! I am facing the same issue! @zultuta Did you find a fix for this?
