### ISSUE TITLE
require ('socket') stdin:1: module 'socket' not found: (after installing torch)

### ISSUE THREAD

**Issue by zultuta** [torch/torch7#506]
I installed torch on my ubuntu14.04 by following the instruction at the torch install page here: http://torch.ch/docs/getting-started.html#_  . before installing torch, i already installed lua, luarocks and luasocket, by using (sudo luarocks install luasocket) and they are all working fine but after i installed torch, whenever i want to use the luasocket module, i get the error

Lua 5.3.2  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> require ('socket')
stdin:1: module 'socket' not found:
	no field package.preload['socket']
	no file '/home/muhammad/.luarocks/share/lua/5.1/socket.lua'
	no file '/home/muhammad/.luarocks/share/lua/5.1/socket/init.lua'
	no file '/home/muhammad/torch/install/share/lua/5.1/socket.lua'
	no file '/home/muhammad/torch/install/share/lua/5.1/socket/init.lua'
	no file './socket.lua'
	no file '/home/muhammad/torch/install/share/luajit-2.1.0-beta1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket.lua'
	no file '/usr/local/share/lua/5.1/socket/init.lua'
	no file '/home/muhammad/torch/install/lib/socket.so'
	no file '/home/muhammad/.luarocks/lib/lua/5.1/socket.so'
	no file '/home/muhammad/torch/install/lib/lua/5.1/socket.so'
	no file './socket.so'
	no file '/usr/local/lib/lua/5.1/socket.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	stdin:1: in main chunk
	[C]: in ?
> 
I then tried to install torch 7 first before installing lua, luarocks and lua socket but i still face the same problem when i require luasocket

I think this is because luarocks comes bundled with torch and something is mixed up somewhere?? please any advice on how to solve this would be most appreciated

**Comment by soumith** [comment]
This issue tracker is for bugs in the torch 7 tensor library. Please continue posting your questions on the Google groups

**Comment by neftaliw** [comment]
This is the first result that comes up on google when looking for this issue and it is closed without being solved. [clap] [clap] [clap]

**Comment by fmassa** [comment]
@neftaliw Here is the corresponding thread of the Google Groups https://groups.google.com/forum/#!searchin/torch7/socket|sort:relevance/torch7/AWO2oWN3dJ8/q6F4HHkiAgAJ

**Comment by neftaliw** [comment]
Thank you, it is frustrating that google search gives you dead ends when trying to solve these issues :)
