### ISSUE TITLE
Feature Request: Convert a table of tensors to tensor using torch.Tensor(T)

### ISSUE THREAD

**Issue by shockley** [torch/torch7#507]
th> T
```lua 
    {
      1 : DoubleTensor - size: 3
      2 : DoubleTensor - size: 3
    }
```
th> torch.Tensor(T)
invalid element (not a number) at ...

This feature might be useful. Thanks!!

**Comment by fmassa** [comment]
You can achieve the same functionality using [`torch.cat`](https://github.com/torch/torch7/blob/master/doc/maths.md)

**Comment by soumith** [comment]
^ what Francisco said.
