### ISSUE TITLE
resized serialized tensors are too large

### ISSUE THREAD

**Issue by markpeot** [torch/torch7#508]
Suppose that you do this:
   a = torch.Tensor(10000, 1000)
  torch.save('foo.bin', a)  --creates a file that is ~40 mbytes

   a:resize(0) --this does not release storage
   torch.save('qux.bin', a) --creates also a file that is ~40 mbytes.  
   --but I believe that the output file size should be close to zero.

I think that serialization should save just the "visible" part of Storage.  I assume that this is not done because lots of Tensors can conceivably use the same storage.

Mark

**Comment by markpeot** [comment]
In re:  I think that serialization should save just the "visible" part of Storage. I assume that this is not done because lots of Tensors can conceivably use the same storage.

I think specifically that zero'ing a tensor should disconnect the tensor from the underlying storage.

**Comment by timharley** [comment]
Serialization saves Tensors/Storages exactly as they are. I disagree that it should monkey with the Tensors to make them value-wise equal; having multiple Tensors aliasing the same storage is a very common setup, you wouldn't want serialization to break this.

If you want to drop a storage from a Tensor use `:set()`, not `:resize(0)`.

```
local t = torch.ones(10)
t:set()
print(t, t:storage())
```

**Comment by soumith** [comment]
I dont think zero'ing a tensor should disconnect the tensor from the underlying storage, that is just plain wrong and unexpected. As tim said, multiple tensors aliasing the same storage is a very very very common setup.
