### ISSUE TITLE
Endless "performing test c_has_sse4_1_2"

### ISSUE THREAD

**Issue by RiFTelFalse** [torch/torch7#509]
Hello everyone!

I'm trying to install Torch on Ubuntu 15.10 x64 (Via VirtualBox) following this [guide](http://torch.ch/docs/getting-started.html#_)
> curl -s https://raw.githubusercontent.com/torch/ezinstall/master/install-deps | bash
> git clone https://github.com/torch/distro.git ~/torch --recursive

Working normally, but
> cd ~/torch; ./install.sh

Stop after
`performing test c_has_sse4_1_2`

After 4 hours Ubuntu using 20mb RAM more and it's all changes.

**Comment by soumith** [comment]
cant reproduce.

**Comment by RiFTelFalse** [comment]
I can show you my trouble via teamviewer
![Screen](http://puu.sh/mCJJY/b6a9b495ad.png)

**Comment by petemolinero** [comment]
I have this problem too.
