### ISSUE TITLE
Difference between copy() and '='?

### ISSUE THREAD

**Issue by ayumiymk** [torch/torch7#510]
When I fine-tune a VGG-16 caffemodel. First, I create a model, and then I initial the model's parameters. But the questions is,  if I use '=' to initial the parameters, actually the parameters in the model don't change.But if I use 'copy' to initial the parameters, the parameters in the model really changed. So I don't konw why?

**Comment by soumith** [comment]
Could you post questions to our google groups here: https://groups.google.com/forum/#!forum/torch7 , this is only for bug tracking.

**Comment by ayumiymk** [comment]
I am so sorry. It's the first time to give the question here. Thank you.
