### ISSUE TITLE
memory leak in torch.save

### ISSUE THREAD

**Issue by tristancazenave** [torch/torch7#512]
Under Ubuntu 14.04 with 32Go RAM, I have the system used memory increasing until the system kills the job when writing a tensor to a file with torch.save, here is the code:

require 'nn'

local input = torch.FloatTensor (5000, 11 , 19 , 19)

for i = 0,2779 do
    input:zero ()
    nameInputFile = 'file.' .. i .. '.dat'
    torch.save (nameInputFile, input, binary, false)
    collectgarbage ()
end

**Comment by tristancazenave** [comment]
I solved the problem with this instruction in the loop:
   sys.execute ('sync; echo 3 | sudo tee /proc/sys/vm/drop_caches')

**Comment by soumith** [comment]
This seems to be something at the system / kernel level. I dont think this is a memory leak in torch.save. If you think otherwise, please reopen.
