### ISSUE TITLE
VolumetricMaxUnpooling

### ISSUE THREAD

**Issue by mattdns100689** [torch/torch7#515]
I am trying to use this layer but torch doesn't see it. Consequently I have tried to add the related .c and .lua files manually along with additions to the init files but I get the error
```
torch/install/share/lua/5.1/nn/VolumetricMaxUnpooling.lua:31: attempt to call field 'VolumetricMaxUnpooling_updateOutput' (a nil value)
```
so I am not sure if I have added all the required files into my torch folder correctly. I have added the files;

```
~/torch/extra/nn/VolumetricMaxUnpooling.lua
~/torch/extra/nn/generic/VolumetricMaxUnpooling.c
```
Furthermore I have added the lines;

```
#include "generic/VolumetricMaxUnpooling.c"
#include "THGenerateFloatTypes.h"
nn_FloatVolumetricMaxUnpooling_init(L);
nn_DoubleVolumetricMaxUnpooling_init(L);

include('VolumetricMaxUnpooling.lua')
```
to the init.c,init.lua files  respectively. 

Does anyone know what I can do to rectify this?

Thanks

**Comment by fmassa** [comment]
Once you have all those files, you need to install it. In your nn folder, do
```
luarocks make rocks/*
``'

**Comment by mattdns100689** [comment]
@fmassa Thanks very much for the info, that worked nicely. Also, do you know if there will be a volumetric version of SpatialUpSamplingNearest at some point?

**Comment by fmassa** [comment]
@mattdns100689 have a look at https://github.com/kmul00/torch-vol

**Comment by mattdns100689** [comment]
perfect thanks again

**Comment by soumith** [comment]
Next time, questions go to Google groups. Bug reports of nn opened on torch/nn
