### ISSUE TITLE
upvalues are untied after serialization / deserialization

### ISSUE THREAD

**Issue by soumith** [torch/torch7#516]
If there's an upvalue referred by the two functions, and the functions are serialized / deserialized, the upvalue references are no longer the same.

Repro:

```lua
local i = 1
local res = {}
function res.seti(j) i = j end
function res.printi() print(i) end

print("Before saving, variable i is shared")
res.seti(2)
res.printi()  -- output 2 since variable i is shared among two functions.

torch.save("./tmp", res)
local res2 = torch.load("./tmp")
print("After save/load, variable i is no longer shared")
res2.seti(3)
res2.printi() -- output 2 rather than 3
```

**Comment by leonbottou** [comment]
Cute!

**Comment by albanD** [comment]
This can be mitigated by using torch classes:

```lua
local i = torch.Tensor(1)
local res = {}
function res.seti(j) i[1] = j end
function res.printi() print(i[1]) end

print("Before saving, variable i is shared")
res.seti(2)
res.printi()  -- output 2 since variable i is shared among two functions.

torch.save("./tmp", res)
local res2 = torch.load("./tmp")
print("After save/load, variable i is no longer shared")
res2.seti(3)
res2.printi() -- output 3 as expected
```

Though if you change the saving to disable the `referenced` mode with `torch.save("./tmp", res, nil, false)` it breaks again.

**Comment by albanD** [comment]
@soumith as a quick try [this](https://github.com/albanD/torch7/tree/upvalue_binding) kind of change solve this issue.
The idea is to check when serializing which upvalues are linked.
Then when de-serializing we link back the upvalues that used to be linked.

Positive:
* Now the upvalues stay linked after de-serialization

Negative:
* We store with each upvalue an id -> increase the size of the serialized element.

Do you think it would be worth cleaning up and adding it to the torch7 codebase?

**Comment by soumith** [comment]
Leon and I were discussing this exact solution, discussing technical pitfalls etc. 

I think this is worth adding, but to maintain back-compatibility one has to introduce a LEGACY_TYPE_FUNCTION similar to how we introduced a LEGACY_TYPE_RECUR_FUNCTION: https://github.com/torch/torch7/blob/master/File.lua#L21
The increase in size of the serialized element is super minor, and the benefits outweigh it IMO.

**Comment by albanD** [comment]
I am not sure you actually need a new serialized type. Since we add a new element to the `upvalue` table, it will be ignored if you use an older version of torch (and the binding will be broken). I added [this](https://github.com/albanD/torch7/commit/a1ee5019123dc2fdee6dbf9ce1f243d4d40f2ade) commit where you just ignore the binding logic if the `upvalue` table does not contain the `id` (meaning that it has been serialized by an older version of torch and here again the binding will be broken).

**Comment by soumith** [comment]
I've just reviewed that branch. It all looks good. Took me some time to find debug.upvaluejoin and understand it. You're right, a new type is not needed.

**Comment by deltheil** [comment]
> Took me some time to find debug.upvaluejoin

So this has been [introduced in Lua 5.2](http://www.lua.org/manual/5.2/readme.html#changes) (and is also available out-of-the-box with LuaJIT) - so no Lua 5.1 support. Isn't it a problem?

**Comment by soumith** [comment]
oh, hmmm. if there's no mechanism in lua 5.1 to do this, then sadly, so be it. If we can write a compatibility function without mega-patching the internals of Lua 5.1, that's not a bad option.
At this point we're either LuaJIT or Lua 5.2 across board, and we're looking into Lua 5.3 support, so I am not terribly worried about consequences.

**Comment by deltheil** [comment]
> I am not terribly worried about consequences

:+1:
