### ISSUE TITLE
Failed searching manifest: Failed fetching manifest for

### ISSUE THREAD

**Issue by ashwinnair14** [torch/torch7#518]
Hi,
Running into the same problem. as #169 #250 #303 
already tried the sudo rm -rf ~/.cache/luarocks and tried again.
And still get the same error. @soumith 

I'm running the torch7 on a ubuntu 14.04 LTS pc behind a proxy. I have already made environment variables Http_proxy and proxy.

The default options for wget and curl and git has been set to run via this proxy. here are the steps I used to change the settings of the packages of [Wget proxy](http://stackoverflow.com/questions/11211705/setting-proxy-in-wget), [Curl proxy](http://stackoverflow.com/questions/7559103/how-to-setup-curl-to-permanently-use-a-proxy) & [git proxy](http://stackoverflow.com/questions/783811/getting-git-to-work-with-a-proxy-server)

The env variables are available in my .bashrc and /etc/enviornmentfiles.

I have also added the proxy in the config.lua file as per [this](https://github.com/keplerproject/luarocks/wiki/LuaRocks-through-a-proxy) post as well.

The error I get when i try to install this is

```
$sudo luarocks install cunn
Warning: Failed searching manifest: Failed loading manifest: 
Failed fetching manifest for http://luarocks.org/repositories/rocks 
- Error fetching file: Failed downloading 
http://luarocks.org/repositories/rocks/manifest


Error: No results matching query were found.
```

**Comment by soumith** [comment]
please use the google groups for issues as such! this is not a bug report for the torch7 package.
https://github.com/torch/torch7#need-help
