### ISSUE TITLE
BLAS_openblas_LIBRARY-NOTFOUND

### ISSUE THREAD

**Issue by Atcold** [torch/torch7#52]
I had to add

```
/usr/lib/gcc/x86_64-linux-gnu/4.8/ /opt/OpenBLAS/lib/
```

to [FindBLAS.cmake](https://github.com/torch/torch7/blob/master/lib/TH/cmake/FindBLAS.cmake#L70), line 70, in order to compile correctly with _Blas_ and _Gfortran_.

I'm on a Ubuntu 14.04.

**Comment by CuriousCat-7** [comment]
Yes, just updated my Torch7 and luaJIT and fixed!
thank you!
