### ISSUE TITLE
CmdLine overwrites default print function

### ISSUE THREAD

**Issue by dasguptar** [torch/torch7#528]
Once` CmdLine:log()` has been called, the global print function seems to be overwritten by the print function inside `CmdLine:log()`. I know it sounds weird, but before calling `CmdLine:log()`, doing a `print()` on a table results in nicely formatted and nested output, while after calling `CmdLine:log()`, the output is simply `table: 0x12345678`.

Here is a snippet that showcases this behaviour:
```
cmd = torch.CmdLine()
cmd:text('Testing CmdLine printing and logging')
cmd:text('Options')
cmd:option('-seed',123,'initial random seed')
cmd:option('-booloption',false,'boolean option')
cmd:option('-stroption','mystring','string option')

-- parse input params
params = cmd:parse(arg)
params.rundir = cmd:string('experiment', params, {dir=true})
paths.mkdir(params.rundir)

-- just a random table
a = {1,2,3}

-- print the table before logging
print(a)

-- create log file
cmd:log(params.rundir .. '/log', params)

-- print the table after logging
print(a)
```
The output it produces is as follows:
```
{
  1 : 1
  2 : 2
  3 : 3
}
[program started on Fri Feb  5 00:24:08 2016]
[command line arguments]
stroption	mystring
booloption	false
seed	123
rundir	experiment
[----------------------]
table: 0x417c30b8
```
Notice how printing the table no longer works as expected at the end. It seems [these lines in CmdLine.lua](https://github.com/torch/torch7/blob/master/CmdLine.lua#L193-L209) are guilty.
Changing the function name from `print` to something else, like `printLog` seems to fix this on my local install.

**Comment by fmassa** [comment]
If you change it to another name, then you won't actually print it to a file.
I think what you want is to include something like [this](https://github.com/torch/trepl/blob/master/init.lua#L260-L283) there

**Comment by dasguptar** [comment]
@fmassa I'm not sure why it won't print to a file. The [lines](https://github.com/torch/torch7/blob/master/CmdLine.lua#L207-L208) will still work if I change all mentions of the function name `print` to something else inside the `log` function, right? 

Anyway, I guess @soumith's commit is a better fix. :+1:

**Comment by soumith** [comment]
it's the order of print overrides.
torch gets the print function before trepl overrides the print function.
I'm working on a proper fix but it's getting quite complicated because multiple torch.CmdLine have to be supported, while collecting file handles after they destruct.

**Comment by dasguptar** [comment]
So I'm assuming the latest [PR](https://github.com/torch/torch7/pull/532) fixes this for now?
Just to be sure I understand correctly, how does doing `oprint = oprint or print` ensure that we get Torch's `print` function instead of the `log` function's nested `print` function?

**Comment by soumith** [comment]
that line ensures that we get trepl's print function instead of the inbuilt lua print function (which doesn't have fancy table printing).

**Comment by fmassa** [comment]
@soumith it also includes the colorings. I think the coloring should be disabled when `:log` is called, to avoid having weird characters in the log. wdyt ?
