### ISSUE TITLE
Could NOT find CUDA when installing Cutorch

### ISSUE THREAD

**Issue by anhhsv55** [torch/torch7#552]
Hi,

I encounter this problem when trying to install Cutorch.

```
CMake Error at /usr/local/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find CUDA: Found unsuitable version "5.0", but required is at
  least "5.5" (found /usr)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:372 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.2/Modules/FindCUDA.cmake:855 (find_package_handle_standard_args)
  CMakeLists.txt:7 (FIND_PACKAGE)
```

I'm sure that there is no Cuda version in /usr and /usr/local/cuda links to cuda-7.0. I could not find any possible cause of this problem, hence I don't know how to solve it.

Please advice. Many thanks.

**Comment by soumith** [comment]
Could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking the torch7 package. We'll happily reply there. Thanks.
