### ISSUE TITLE
Add lerp, trunc, frac, rcp functions

### ISSUE THREAD

**Issue by andreaskoepf** [torch/torch7#553]
I would like to discuss the addition of some handy math functions from the  [CG](http://http.developer.nvidia.com/Cg/index_stdlib.html)/[shader](https://msdn.microsoft.com/de-de/library/windows/desktop/ff471376%28v=vs.85%29.aspx) world.

If this was seen as a positive addition I could prepare a PR for torch7 & cutorch.

**Comment by andreaskoepf** [comment]
(I noticed that torch.mod() was recently added and removed fmod from the title.)

**Comment by andreaskoepf** [comment]
(I removed rsqrt, it is probably too specific)

**Comment by andreaskoepf** [comment]
Short description of functions:
- lerp -  linear interpolation of two scalars or vectors based on a weight: `a + w*(b-a)`
- trunc -  the integral value nearest to but no larger in magnitude than x: (`x < 0 ? -floor(-x) : floor(x)`).
- frac - the fractional portion of a scalar or each vector component: `x - floor(x)` 
- rcp - fast, approximate, per-component reciprocal (counterpart of neg for divisions): 1/x

**Comment by soumith** [comment]
i'd say "sure, why not"

**Comment by szagoruyko** [comment]
+1 and rsqrt, I remember I had to hack torch and cutorch to get it. can be useful.

**Comment by andreaskoepf** [comment]
Scheduled for next weekend.

**Comment by andreaskoepf** [comment]
Created #568

**Comment by andreaskoepf** [comment]
rcp is already implemented under the name `cinv()`. I personally would have preferred the name 'rcp' but since cinv() was added by @hughperkins  https://github.com/torch/torch7/commit/61686f259f8c853a8e2b188a0306ed590efcb2ab in January I am a bit too late ;-)..

**Comment by andreaskoepf** [comment]
A review of my PR would be nice. If I get green light, I could squash the commits.

**Comment by hughperkins** [comment]
You're asking the wrong way around, and in the wrong order ;-P

1. Squash the commits
2. Say 'Soumith, do you have any outstanding issues that you want to address on this PR?'

**Comment by andreaskoepf** [comment]
integrated.

**Comment by hughperkins** [comment]
:-)
