### ISSUE TITLE
torch.rand generate element whose value is 1.000, but according to doc torch.rand by default generate range [0, 1). 

### ISSUE THREAD

**Issue by eriche2016** [torch/torch7#560]
in my project code, i came acrross such issues. so what is the actual range? i am confused

**Comment by fmassa** [comment]
The range is `[0,1)`. What probably happened is that you are seeing a rounding of a number close to 1 when printing the tensor, giving the impression that it's one. For example
```
th> a = torch.Tensor(1):fill(0.99995)
                                                                      [0.0001s]	
th> print(a)
 1.0000
[torch.DoubleTensor of size 1]
```

**Comment by eriche2016** [comment]
appreciate your quick answer. but what if i do the following: 
th> a = torch.Tensor(1):fill(0.9999999)
th>a = (a * 50000):long() 
the above code will print 50000, which is weird. coz if a is less than 1, then a * 50000 must also be less that 50000, so when do floor operation, it will give me 50000, then what happened, is the problem of overflow? or is the torch.rand give me 1.0

**Comment by fmassa** [comment]
The snippet you just sent me gives me 49999...
```
th> a = torch.Tensor(1):fill(0.9999999)
                                                                      [0.0261s]	
th> a = (a * 50000):long()
                                                                      [0.0249s]	
th> a
 49999
[torch.LongTensor of size 1]
```

**Comment by eriche2016** [comment]
sorry, i give u the wrong snippet, try this, friend:
th> a = torch.Tensor(1):fill(0.99999999999999999)
th> a = (a * 50000):long()

**Comment by fmassa** [comment]
Well, the problem is that `0.99999999999999999` doesn't fit in double floating numbers, so 0.99999999999999999 is actually 1.

**Comment by eriche2016** [comment]
the actual code is from my project code here: 
local indices = torch.rand(128)
indices = (indices * 50000):long():add(1) 
the above code give me 50000 causing my project crashed. when i print indices, there is one element equal to 50001, which is weird? i donnot why

**Comment by eriche2016** [comment]
i can run it again and  print it for you if you like.

**Comment by fmassa** [comment]
It would be better to find a random seed that reproduces the problem without having to run it for forever. The ideal should be something like
```lua
torch.manualSeed(1254) -- find the seed that reproduces your case
indices = torch.rand(128)
indices = (indices * 50000):long():add(1) 
```

As a side note, you can directly generate integer numbers uniformly sampled. by doing
```lua
indices = torch.LongTensor(128):random(0,50000) -- ranges from 0 to 50000
```

**Comment by eriche2016** [comment]
yes  i have random seed, and i know when the bugs occurs

**Comment by eriche2016** [comment]
many thanks for your adivices, i will take it.  friend

**Comment by eriche2016** [comment]
many thanks for your adivices, i will take it.  friend

**Comment by fmassa** [comment]
Can you send a self-contained snippet that reproduces the problem ?
Are you using `float` as the default tensor type ? If yes, then what might be happening is the loss in precision while converting from `double` ([the random numbers are generated in `double`](https://github.com/torch/torch7/blob/master/lib/TH/THRandom.c#L218)) to `float` precision (numbers in lua are double).
```
th> print(torch.FloatTensor{0.9999999999}[1])
1	
                                                                      [0.0001s]	
th> print(torch.DoubleTensor{0.9999999999}[1])
0.9999999999	
```

**Comment by eriche2016** [comment]
oh yes， the datatype i use is float tensor,   and that may be the place where the bugs come from.  and i got it. thank u very much.
