### ISSUE TITLE
can't find libcudnn on mac os

### ISSUE THREAD

**Issue by iamsile** [torch/torch7#565]
When I use the torch7 on mac os 10.11, torch7 couldn't find the libcudnn.4.dylib. 

/Users/xxx/torch/install/bin/luajit: /Users/xxx/torch/install/share/lua/5.1/trepl/init.lua:363: /Users/xxx/torch/install/share/lua/5.1/trepl/init.lua:363: /Users/xx/torch/install/share/lua/5.1/cudnn/ffi.lua:1279: 'libcudnn (R4) not found in library path.
Please install CuDNN from https://developer.nvidia.com/cuDNN
Then make sure files named as libcudnn.so.4 or libcudnn.4.dylib are placed in your library load path (for example /usr/local/lib , or manually add a path to LD_LIBRARY_PATH)

How to solve it ?  Please help

**Comment by soumith** [comment]
Use our google groups for help
