### ISSUE TITLE
Unable to build torch - non-floating-point argument in call to function ‘__builtin_isnan’

### ISSUE THREAD

**Issue by denysvitali** [torch/torch7#571]
Hi everyone,
today I've tried to install torch7 in my ArchLinux environment.
I have followed the getting started guide at [torch.ch](http://torch.ch/docs/getting-started.html) but got stuck while compiling.
Some other users are expecting the same issue, as reported by an user in the [AUR package comments](https://aur.archlinux.org/packages/torch7-git/) (comment from 2016-02-22 18:22 by user archdria)

The error that is thrown is the following:
```
In file included from generic/THTensorMath.c:2:0,
                 from /home/dvitali/torch/pkg/torch/lib/TH/THTensor.c:20:
/home/dvitali/torch/pkg/torch/lib/TH/generic/THTensorMath.c: In function ‘THByteTensor_minall’:
/home/dvitali/torch/pkg/torch/lib/TH/generic/THTensorMath.c:395:3: error: non-floating-point argument in call to function ‘__builtin_isnan’
   TH_TENSOR_APPLY(real, tensor,
   ^
```
The following errors are all related to an isnan() call, for example in the case reported here the error is caused by [this function call](https://github.com/torch/torch7/blob/master/lib/TH/generic/THTensorMath.c#L395)

I'm trying to look into that right now

**Comment by denysvitali** [comment]
[The commit from 13 hours ago](https://github.com/torch/torch7/commit/594d4a58f256a6023136a10c86c25f18f1b6a62a) seems to be able to fix the issue, unfortunatly torch's online installer uses torch/distro.git instead of the mainline torch7.
I'll try with torch7-git AUR package and report back

**Comment by fmassa** [comment]
Could you try pulling the latest torch ? There was a fix for it yesterday that probably didn't go ti distro https://github.com/torch/torch7/pull/570
try doing 
```
luarocks install torch
```

**Comment by soumith** [comment]
I have updated distro just now, so this problem should now be fixed.
