### ISSUE TITLE
torch/install/share/lua/5.1/torch/File.lua:342: read error

### ISSUE THREAD

**Issue by OmarAhmadien** [torch/torch7#574]
I am trying to run a [supervised](http://code.madbits.com/wiki/doku.php?id=tutorial_supervised) Machine Learning tutorial code using lua .. 

When I load the dataset , the error below always occurs: 

![image](https://cloud.githubusercontent.com/assets/17507035/13489919/4cb67bfe-e132-11e5-92bc-4b3d13e043f6.png)

@soumith  Can you help me in this?

**Comment by Atcold** [comment]
Looks like the file you're trying to open is corrupted or not complete.

**Comment by soumith** [comment]
Could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking the torch7 package. We'll happily reply there. Thanks.

This is a partially downloaded file, and not a bug.
