### ISSUE TITLE
Kernel doesn't respond

### ISSUE THREAD

**Issue by chenkovsky** [torch/torch7#586]
I am a new user.
I try to run https://github.com/torch/tutorials/blob/master/2_supervised/1_data.lua in itorch notebook.
after loading the train data, I add a new cell. 
    `trainData.data`

when I run this cell, the kernel doesn't respond, and luajit occupies a lot of CPU, writes a lot of data to disk.
after I kill the itorch, luajit is still running.

**Comment by soumith** [comment]
Could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking the torch7 package. We'll happily reply there. Thanks.
