### ISSUE TITLE
How to add constraints of parameters in Torch?

### ISSUE THREAD

**Issue by yaolubrain** [torch/torch7#588]
Suppose I create an autoencoder model like
```
model = nn.Sequential()
model:add(nn.Reshape(28*28))
model:add(nn.Linear(28*28, layer_size))  -- W1
model:add(nn.Tanh())
model:add(nn.Linear(layer_size, 28*28))  -- W2
model:add(nn.Reshape(28, 28))
```
I want to add the constraint
W1 = W2'

I found 
https://github.com/clementfarabet/nnop#weight-sharing
https://github.com/torch/nn/blob/master/doc/overview.md#a-note-on-sharing-parameters

But I wonder what's the easiest way to do it.

**Comment by soumith** [comment]
please post questions to our google groups.
See this section for the link: https://github.com/torch/torch7#need-help
