### ISSUE TITLE
require package doesn't work

### ISSUE THREAD

**Issue by mlakhal** [torch/torch7#592]
After upgrading my torch package, everything works well on the prompt, but, when I try to write my script and run it via command line, every require package won't work. And I am having the same message for all the package, like for example with `require 'torch'` 

`module 'torch' not found:
	no field package.preload['torch']
	no file '/usr/local/share/lua/5.2/torch.lua'
	no file '/usr/local/share/lua/5.2/torch/init.lua'
	no file '/usr/local/lib/lua/5.2/torch.lua'
	no file '/usr/local/lib/lua/5.2/torch/init.lua'
	no file '/usr/share/lua/5.2/torch.lua'
	no file '/usr/share/lua/5.2/torch/init.lua'
	no file './torch.lua'
	no file '/usr/local/lib/lua/5.2/torch.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/torch.so'
	no file '/usr/lib/lua/5.2/torch.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './torch.so'
`

**Comment by soumith** [comment]
Could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking the torch7 package. This does not seem like a bug, as our contbuilds dont show anything of this sort. We'll happily reply there. Thanks.
