### ISSUE TITLE
luajit maintenance?

### ISSUE THREAD

**Issue by hughperkins** [torch/torch7#598]
Per https://www.reddit.com/r/MachineLearning/comments/48s2m8/torch_vs_tensorflow/d0m6js3 , there is no maintainer for luajit currently.  Note just to be clear I am *not* volunteering for this.  But does seem like something that is highlighted as a risk for torch.  Hence, raising an issue for it.

Seems like at least we should have a github fork of it perhaps, and handle merging changes?  There are a zillion github forks out there https://github.com/LuaDist/luajit/network https://github.com/openresty/luajit2/network but no-one seems to coordinating merging them?  (Again, just to be clear, not volunteering for this, just highlighting the point).

**Comment by timharley** [comment]
You mean like [this one](https://github.com/torch/luajit-rocks)?

**Comment by hughperkins** [comment]
> You mean something like this one?

from the linked article:

"We did not make any changes, except the compilation and installation processes."

**Comment by timharley** [comment]
Are you suggesting that someone from the torch community should step forward to maintain the whole luajit project itself? Or that we maintain our own fork for usage by the torch only? I thought you were suggesting the latter, and I just wanted to point out that we presently do this.

That quote isn't quite correct, the torch fork of luajit has a couple of patches:
https://github.com/torch/luajit-rocks/commit/cafad2e668764467d7846719ee964172c4e74b0b
https://github.com/torch/luajit-rocks/commit/fc56af2b73ac67b2f4efa454b8c1f315c6d8c678

**Comment by soumith** [comment]
1. LuaJIT is not unmaintained. The maintainership is being taken over by folks in the LuaJIT community. See the LuaJIT mailing lists for volunteer candidates etc.
2. We dont exclusively depend on LuaJIT nor do we care that much about it. Lua 5.2 + luaffifb provides the same experience. 

Considering 1 and 2, and the fact that we already maintain our fork, with albeit minor changes, i think we dont need to worry about this.

**Comment by hughperkins** [comment]
> Lua 5.2 + luaffifb provides the same experience. 

Ah, ok.  I was wondering about ffi.  I noticed that ffi seemed to be built into luajit.  And with THNN, ffi is kind of important.  But ffi works ok, with lua 5.2 + luaffib?

Question: is lua 5.1 + luaffib sufficient?  What htings are missing in lua 5.1, which are needed by torch?

**Comment by soumith** [comment]
Lua 5.1 + luaffifb is sufficient too. afaik, lua 5.1 doesn't support a minor feature where we share upvalues (https://github.com/torch/torch7/pull/519 ), and the rest is supported.

**Comment by hughperkins** [comment]
Cool.  Sounds good.  Note that, not sure if you care about such things, but seems like torch has a minor PR issue on the luajit point, considering that I've been using torch for ~8-10 months, and wasn't really aware of our roadmap on this point, and that the reddit post cited above is at the number one spot in the `torch vs tensorflow` thread, and no-one has provided any new information on this point.
