### ISSUE TITLE
Failed to load function from bytecode

### ISSUE THREAD

**Issue by volkov68** [torch/torch7#601]
Hello,
I get this error when i try to load the nin model (https://gist.github.com/szagoruyko/0f5b4c5e2d2b18472854)

net = torch.load("nin_bn_final.t7"):unpack()
/usr/local/share/lua/5.1/torch/File.lua:301: Failed to load function from bytecode: (binary): cannot load incompatible bytecode
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/torch/File.lua:301: in function 'readObject'
	/usr/local/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/usr/local/share/lua/5.1/torch/File.lua:409: in function 'load'
	[string "net = torch.load("nin_bn_final.t7"):unpack():..."]:1: in main chunk
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/trepl/init.lua:635: in function 'repl'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
	[C]: at 0x00404ac0

**Comment by szagoruyko** [comment]
there is a function saved with luajit2.1 that's incompatible with your lua for some reason. I will repack it without the function

**Comment by soumith** [comment]
move discussion to the gist, looks like not a bug.

**Comment by apeterswu** [comment]
@soumith ,Hi, I have the same problem, but when I updated my luajit version to be 2.1, it still failed and the error still showed. Could you help?
