### ISSUE TITLE
error while running cuda

### ISSUE THREAD

**Issue by Benedetta89** [torch/torch7#604]
I am trying to convert a training set from CPU to GPU data and I am getting an error of "attempt to call method 'cuda' (a table value)" : comando non trovato.

I get the error with all of the following attempts:
trainData=trainData:cuda()
net = net:cuda()
criterion = criterion:cuda()

Why is this error occurring and what is the right way to do this?
p.s. i've included the package cunn with require 'cunn'

**Comment by soumith** [comment]
Could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking the torch7 package. We'll happily reply there. Thanks.
