### ISSUE TITLE
System freeze, or 'Killed' error

### ISSUE THREAD

**Issue by ssampang** [torch/torch7#605]
Hi guys,

I've posted in detail about the issue [here](https://groups.google.com/forum/#!topic/torch7/LGea9b1Zf8k), but I thought it was worthwhile to create an issue here as well, since causing a system freeze is probably a bug. As I mentioned in the user group post, half of the time I run my code, my system locks up and I have to hard reset, and half of the time, the only output I see is 
```
FileLogger: log will be written to /home/sid/save/PrometheusU:1458442459:1/log	
==> epoch # 1 for optimizer :	
Killed
```

Any help would be greatly appreciated.

**Comment by soumith** [comment]
Killed, is almost always out of memory. Have you monitored your memory usage?

**Comment by ssampang** [comment]
Yes, I have a card with 2gb, and memory never exceeds 150mb - there's always at least 1gb of unused memory.

**Comment by ssampang** [comment]
Ah, you were right! I ran out of memory, but not on my gpu. 

Any idea what to do? I'm fairly sure the issue arises either [here](https://github.com/ssampang/HeartbeatAtt/blob/master/recurrent-visual-attention.lua#L163) or [here](https://github.com/ssampang/HeartbeatAtt/blob/master/recurrent-visual-attention.lua#L190) (or both), but I'm not sure how to make that code simpler. I essentially have a tensor of 1796 hidden states (1796x256 vector), where each needs to be fed through the same nn.Sequential (a 256-to-2 linear layer followed by a logsoftmax) and each essentially counts as a training example that's trained using an nn.ClassNLLCriterion. 

My solution was to use ParallelTables that consist of clones of the same nn.Sequential (with shared weights, so its essentially training a single nn.Sequential " in parallel") and ParallelCriterions as you can see, but that doesn't seem to work...

Each training example produces the intermediate 1796x256 vector, and so currently, I'm using a batch size of 1 since essentially the network is trained on a batch of 1796 vectors for each real training example. Is there some way I can portray the 1796x256 vector as a batch instead? Then I can get rid of the ParallelTable and ParallelCriterion representations and I'm guessing torch can manage its memory better?
