### ISSUE TITLE
Installation "build error: failed installing

### ISSUE THREAD

**Issue by JeffCrusey** [torch/torch7#606]
Im not sure why my issue is installing torch7 but receive the following error message

Error: could not find ipython in PATH. Do you have it installed?
cd build && make install
sh: line 0: cd: build: No such file or directory

Error: Build error: Failed installing.

Not updating your shell profile.
You might want to
add the following lines to your shell profile:

. /Users/jeffcrusey/torch/install/bin/torch-activate

Anyone have any ideas how to fix this? Thx

**Comment by soumith** [comment]
Answered on the forums. next time only use the forums for user support and dont post at multiple places.
