### ISSUE TITLE
mod and cmod bugs

### ISSUE THREAD

**Issue by j-wilson** [torch/torch7#607]
Bug in recently added mod and cmod functions:

__Correct Behavior__
```
th> a, b = -10, 3
th> a % b
2
th> a - b*math.floor(a/b)
2
```
Note that [maths.md](https://github.com/torch/torch7/blob/master/doc/maths.md#res-torchmodres-tensor-value) explicitly defines `mod` and `cmod` as performing this second computation

__Trouble Behavior__
```
th> a, b = -10, 3
th> torch.mod(torch.Tensor{a}, b)
-1
[torch.DoubleTensor of size 1]

th> torch.cmod(torch.Tensor{a}, torch.Tensor{b})
-1
[torch.DoubleTensor of size 1]
```

**Comment by soumith** [comment]
fixed via #620
