### ISSUE TITLE
bug in operator overloading in torch.class

### ISSUE THREAD

**Issue by iamalbert** [torch/torch7#610]
Torch class system seems to have bug handling overloaded operators when the instance is on the right-hand-side

```lua 
local cb =  function(x,y)                       
    print("\ncalled: ", x, y, "\n")            
end 

torch.class('TestClass') 

local mt = torch.getmetatable('TestClass')          
mt.__add__ =  cb
                                               
local m = TestClass()                               
                                               
print( m )            -- ok
print( m + 2 )      -- ok                   
print( 2 + m )      -- error                   
```

which has error
```
internal error in __add: no metatable
```

**Comment by soumith** [comment]
it's not a bug of the torch class system. 2 + m will call the __add__ of the "number" metatable. The LHS determines which metatable is called.

**Comment by iamalbert** [comment]
OK, but this is an contradiction to the original behavior of overloading operator in Lua

**Comment by soumith** [comment]
hmm, re-reading the Programming in Lua page, this does seem like a bug: http://www.lua.org/pil/13.1.html

Thanks for pointing it out

**Comment by soumith** [comment]
I'll try to trace where this comes from, if you have any pointers feel free to let me know.

**Comment by iamalbert** [comment]
I suppose that the handler is in the implementation of `static int luaT_mt__add(lua_State *L);`
( https://github.com/torch/torch7/blob/master/lib/luaT/luaT.c#L1199 ). It is an macro defined at https://github.com/torch/torch7/blob/master/lib/luaT/luaT.c#L1171 , which only checks the LHS for metatable. (https://github.com/torch/torch7/blob/master/lib/luaT/luaT.c#L1174)

we can provide another version for all binary operators.

**Comment by Atcold** [comment]
Wow! This has been there since the beginning! And I thought as well it was Lua's fault!
Good to know Lua supports mixed input!
