### ISSUE TITLE
Can't exit after requiare 'cunn'

### ISSUE THREAD

**Issue by spk921** [torch/torch7#613]
I am having problem that after require 'cunn' I can't exit torch. 

I am using nvidia-k40c GPU. Error message doesn't shows up. Also after forcing quieting the terminal 

I can't reboot computer properly. I am I the only one that having this problem?

**Comment by CDLuminate** [comment]
I can't repro this problem but according to `I can't reboot computer properly.` I guess some other software is the one to blame instead of cunn.

**Comment by Atcold** [comment]
@spk921, what's the problem? On what machine are you?

**Comment by spk921** [comment]
I solved this problem by installing proper driver Thanks. I forgot to closed.
