### ISSUE TITLE
torch cdiv

### ISSUE THREAD

**Issue by pefi9** [torch/torch7#621]
I don't understand behaviour of the torch:cdiv:

th> t1
 1860  1430  1730  1170  1280   830  1010   410   710   780  5150
[torch.LongTensor of size 1x11]

th> t2
 1875  1520  1765  1190  1315  1045  1095   645   815  1175  5160
[torch.LongTensor of size 1x11]

th> t1:cdiv(t2)
 0  0  0  0  0  0  0  0  0  0  0
[torch.LongTensor of size 1x11]

th> t1
 0  0  0  0  0  0  0  0  0  0  0
[torch.LongTensor of size 1x11]

Why is the result of the cdiv operation equal zeros?
Which operation should I use to get vector of : t1[{1,1}] / t2[{1,1}], t1[{1,2}]  / t2[{1,2}], ... , t1[{1,11}] / t2[{1,11}]  ?

**Comment by apaszke** [comment]
You should convert them to float tensors. Long values can't represent non-integer numbers, so fractions get rounded towards 0.

**Comment by pefi9** [comment]
Oh, I see. Thank's
