### ISSUE TITLE
install-deps permission errors

### ISSUE THREAD

**Issue by sachinruk** [torch/torch7#622]
I am trying to follow the installation instructions [here](http://torch.ch/docs/getting-started.html#_) for my Mac except that I am running into a whole bunch of permission issues at the line: `bash install-deps`

```
bash install-deps;
error: could not lock config file .git/config: Permission denied
Error: Failure while executing: git config core.autocrlf false
```
So I tried using sudo:
```
sudo bash install-deps 
Password:
Cowardly refusing to 'sudo brew update'
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.
```
And finally even with sudo su with the same error above.

So **question is** how do I get around this on a mac.

Thanks in advance.

**Comment by iamalbert** [comment]
`ls -l .git` to see if you have the right permission.

**Comment by soumith** [comment]
Could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking the torch7 package. We'll happily reply there. Thanks.
