### ISSUE TITLE
x:sum(x,2) not working?

### ISSUE THREAD

**Issue by justinmaojones** [torch/torch7#624]
The following code:
```
x = torch.randn(10,5)
print(x)
x:sum(x,2)
```
yields the output
```
th> x = torch.randn(10,5)
th> x
 0.2596 -1.3825 -0.6455  0.9318 -0.8341
 0.0225  0.2851 -0.1793 -0.7853 -0.7345
-0.7193  0.6036 -1.0995  0.3074  0.5726
-0.4301  2.2603 -1.1683  0.7816  0.0465
 0.5346 -0.0572 -0.5006  0.9371 -0.5283
 0.9010 -0.8099  0.3398 -1.3316 -1.7146
-0.8219 -0.1011  0.2541 -0.9475 -0.2794
-0.6996  0.6754  0.0967  0.6545  0.7057
-0.3205 -0.4559  0.9699  0.4586  0.6724
-0.8277 -0.1050  0.4339 -2.0991 -0.7028
[torch.DoubleTensor of size 10x5]

th> x:sum(x,2)
 0.2596
-1.3825
-0.6455
 0.9318
-0.8341
 0.0225
 0.2851
-0.1793
-0.7853
-0.7345
[torch.DoubleTensor of size 10x1]
```

Notice that the output of `x:sum(x,2)` is just the first column of the original `x`.  Shouldn't this be the row-wise sum?

**Comment by fmassa** [comment]
`torch.sum` does not work in-place.
Indeed, the first thing it does is to resize the output tensor to have the correct size, and as the output tensor is the same as the input tensor in the in-place case, that means that you are summing over a dimension of size 1 (which is the tensor itself).
You should do something like
```lua
y:sum(x,2) -- reuse tensor y
-- or
y = x:sum(2) -- allocate new tensor
```
