### ISSUE TITLE
declaration specifier expected near 'THCState'

### ISSUE THREAD

**Issue by marvin521** [torch/torch7#626]
> switching to CUDA
qlua: /usr/local/share/lua/5.1/cunn/THCUNN.lua:9: declaration specifier expected near 'THCState'
stack traceback:
	[C]: at 0x7fc573d46960
	[C]: in function 'typeof'
	/usr/local/share/lua/5.1/cunn/THCUNN.lua:9: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.1/cunn/init.lua:3: in main chunk
	[C]: in function 'require'

I met the problem above after I had reinstalled cunn. I tried to reinstall nn, cunn, cutorch, but they did not work.  When I update nn, It tells me: loop or previous error loading module 'cunn'.  I do not know how to solve this problem? anyone can tell me what should I do? thanks in advance.

**Comment by andreaskoepf** [comment]
The unknown 'THCState' results from an outdated 'nn' installation. Please try to update nn, too (e.g. by executing `update.sh` followd by `install.sh` in your `~/torch/ folder.

I cannot explain why you see 

>  loop or previous error loading module 'cunn'.

when you update nn. Normally nn has no dependency on cunn and does not try to load it - only the other way round, cunn requires nn. If nothing helps please reinstall torch.

**Comment by marvin521** [comment]
@andreaskoepf , Thanks. I solved this problem by deleting the whole torch folder and then reinstall torch.
