### ISSUE TITLE
torchtest.abs() always fail on 32-bit systems

### ISSUE THREAD

**Issue by alan33d** [torch/torch7#627]
lines 2832-2835 in test.lua:
   -- Checking that the right abs function is called for LongTensor
   local bignumber = 2^31 + 1
   local input = torch.LongTensor{-bignumber}
   mytester:assertgt(input:abs()[1], 0, 'torch.abs(3)')

This doesn't work for long int labs(long int n) in a 32-bit system.  On a 32-bit system, the min long int is -2147483648 and the max long int is 2147483647.  I've tried this on an armv7 (32-bit) and will always fail because labs(-2147483649) is not representable in a 32-bit system.  The output is always -2147483648.  

This test works fine on a 64-bit system.

**Comment by andreaskoepf** [comment]
The abs(-(2^31+1)) test only makes sense if `sizeof(long) > 4` . To fix the test it would be possible to simply add a `if torch.LongTensor():elementSize() > 4` ... In general I think Torch would benefit from defining system independent {Int8, Int16, Int32, Int64}Tensor classes and having system-dependent LongTensor mapping only for backward compatibility.
This would not remove all platform dependent problems (e.g. endianness) but for cases like the failing test of this issue the problem would disappear (if Int64Tensor would be used) - see also  https://github.com/torch/torch7/issues/572 and https://github.com/torch/torch7/issues/572.

**Comment by alan33d** [comment]
I put in your workaround for now and the test now runs on armv8 and armv7 platforms.  Thanks.  I will use this until an official fix is released.

**Comment by CDLuminate** [comment]
32-bit systems suffer from test failure for the same reason.

https://buildd.debian.org/status/package.php?p=lua-torch-torch7&suite=experimental

**Comment by CDLuminate** [comment]
created PR https://github.com/torch/torch7/pull/746

**Comment by CDLuminate** [comment]
Oops, but why do MIPS and MIPSEL pass this unit test without error ........

Their `long` are both 32-bit.....

**Comment by CDLuminate** [comment]
https://github.com/torch/torch7/pull/746 is merged, I think this issue can be closed now.
