### ISSUE TITLE
attempt to call field 'SpatialCrossMapLRN_updateOutput' (a nil value)

### ISSUE THREAD

**Issue by takatosp1** [torch/torch7#630]
Updated and installed using the shell
Then get the error when try to use "struct"
Then "luarocks install struct"
Then got ...24/torch/install/share/lua/5.1/nn/SpatialCrossMapLRN.lua:19: attempt to call field 'SpatialCrossMapLRN_updateOutput' (a nil value)

**Comment by fmassa** [comment]
You probably need to update `cunn`. Just to be sure, update both `torch`/`cutorch`/`nn` and `cunn`.
