### ISSUE TITLE
/home/torch/torch/install/bin/luajit: cannot open dofile(finaltest.lua): No such file or directory ??

### ISSUE THREAD

**Issue by setu1421** [torch/torch7#631]
I am getting the error message when trying to run from the terminal. At first i tried to run the below 
`th -i dofile('finaltest.lua')`
but got the error below:

> bash: syntax error near unexpected token `(' <br>

Then i changed it and run like below:
`th -i dofile\('finaltest.lua'\)` <br>
then got this error

> /home/torch/torch/install/bin/luajit: cannot open dofile(finaltest.lua): No such file or directory

**Comment by apaszke** [comment]
If you want to evaluate an expression you have to use an -e flag.
th -i -e "dofile('finaltest.lua')" will work.
However, the same effect can be achieved with only th -i finaltest.lua

Adam

**Comment by apaszke** [comment]
Also, please note that GitHub issues are used for reporting bugs only. If you have any trouble with using/installing torch please use the mailing list or Gitter.
