### ISSUE TITLE
Torch install error on Mac OS X 10.11.3

### ISSUE THREAD

**Issue by hwlin76** [torch/torch7#633]
When trying to install, I get

> $ bash install-deps
Already up-to-date.
Warning: git-2.8.1 already installed
Warning: readline-6.3.8 already installed
Warning: cmake-3.5.1 already installed
Warning: wget-1.17.1 already installed, it's just not linked
Warning: qt-4.8.7_2 already installed
Warning: jpeg-8d already installed
Warning: imagemagick-6.9.3-7 already installed
Warning: zeromq-4.1.4 already installed
Warning: graphicsmagick-1.3.23_1 already installed
Warning: openssl-1.0.2g already installed
Warning: Already linked: /usr/local/Cellar/readline/6.3.8
To relink: brew unlink readline && brew link readline
==> brew cask install caskroom/cask/brew-cask
Error: No available Cask for caskroom/cask/brew-cask
Error: nothing to install
Warning: A Cask for xquartz is already installed. Add the "--force" option to force re-install.
Error: No such keg: /usr/local/Cellar/gnuplot

I have installed gnuplot; this doesn't seem to help. Then install.sh returns
> `Prefix set to /Users/lin/torch/install
Installing Lua version: LUAJIT21
Installing common Lua packages
env MACOSX_DEPLOYMENT_TARGET=10.8 gcc -O2 -fPIC -I/Users/lin/torch/install/include -c src/lfs.c -o src/lfs.o
src/lfs.c:37:19: fatal error: errno.h: No such file or directory
 #include <errno.h>
                   ^
compilation terminated.

Error: Build error: Failed compiling object src/lfs.o`

**Comment by soumith** [comment]
Could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking the torch7 package. We'll happily reply there. Thanks.
