### ISSUE TITLE
How to build torch7 with system lua-5.3 ?

### ISSUE THREAD

**Issue by jiapei100** [torch/torch7#636]
Hi, 

If I don't want to enable
`TORCH_LUA_VERSION=${TORCH_LUA_VERSION:-"LUAJIT21"} # by default install LUAJIT21` ?

Where can I specify the system lua? Otherwise, it looks like the entire building process is just building lua ....

Thank you very much.
Pei

**Comment by jiapei100** [comment]
Sorry, done...
Follow this: https://github.com/torch/distro
`TORCH_LUA_VERSION=LUA53 ./install.sh`

**Comment by archenroot** [comment]
How to support this via CMAKE?
