### ISSUE TITLE
Out Of Memory from THNN.lua 

### ISSUE THREAD

**Issue by jaiabhayk** [torch/torch7#643]
I am getting the following error when I run in CPU mode even though my machine has 32 GB RAM.

torch/install/share/lua/5.1/nn/THNN.lua:109: $ Torch: not enough memory: you tried to reallocate 11GB. Buy new RAM! at /tmp/luarocks_torch-scm-1-2936/torch7/lib/TH/THGeneral.c:251
stack traceback:
        [C]: in function 'v'
        /cfarhomes/jaiabhay/torch/install/share/lua/5.1/nn/THNN.lua:109: in function 'Tanh_updateOutput'
        /cfarhomes/jaiabhay/torch/install/share/lua/5.1/nn/Tanh.lua:4: in function </cfarhomes/jaiabhay/torch/install/share/lua/5.1/nn/Tanh.lua:3>
        [C]: in function 'xpcall'
        ...es/jaiabhay/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        ...s/jaiabhay/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        train-on-mnist.lua:208: in function 'opfunc'
        ...mes/jaiabhay/torch/install/share/lua/5.1/optim/lbfgs.lua:66: in function 'lbfgs'
        train-on-mnist.lua:245: in function 'train'
        train-on-mnist.lua:345: in main chunk
        [C]: in function 'dofile'
        ...bhay/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:131: in main chunk
        [C]: at 0x004065f0

Steps To Reproduce the Issue:-
=======================
1) Run the following tutorial for full dataset with "LFBGS" method:-
https://github.com/torch/demos/blob/master/train-a-digit-classifier/train-on-mnist.lua

**Comment by soumith** [comment]
Could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking the torch7 package. We'll happily reply there. Thanks.
