### ISSUE TITLE
Tutorial Link with invalid access at code.madbits.com

### ISSUE THREAD

**Issue by zuoxingdong** [torch/torch7#644]
As it suggested in Cheat Sheet, there is a tutorial (second one) on http://code.madbits.com/. But it cannot be opened. Does everyone else also have this issue ? Or is the website down already ?

**Comment by soumith** [comment]
unfortunately the website was down, and no backup copy of those tutorials exist afaik.

**Comment by apaszke** [comment]
A couple days ago I have managed to hack my way through to the old tutorials. You can access them [here](https://web.archive.org/web/20160201031326/http://code.madbits.com/wiki/doku.php). I'll update the Cheat Sheet link with it.

**Comment by apaszke** [comment]
@soumith Or do you want to wait for the new ones, and not make people use the archives?

**Comment by soumith** [comment]
ah good someone managed to recover them :) , please update the cheatsheet.
