### ISSUE TITLE
[Feature Request]  Som Matlab style tensor oprations

### ISSUE THREAD

**Issue by liboyue** [torch/torch7#646]
There are a lot of useful matrix-number operations in Matlab. For example:
```
>> m = [1 2; 3 4]

m =

     1     2
     3     4

>> m > 2

ans =

     0     0
     1     1

>> m == 2

ans =

     0     1
     0     0
```
- Some operators like `>`, `<`, `==`, `~` can return a "mask", and then we can use this mask to index tensors.

- And it would be better if `[]` operator performs the same operations with `torch.index()`, `torch.maskedSelect()` and other elements querying functions.

- **The documentation is too long now, we need to provide a brief index...**

**Comment by andreaskoepf** [comment]
There are already a couple of [Logical operations on tensors](https://github.com/torch/torch7/blob/master/doc/maths.md#logical-operations-on-tensors).

```
th> m = torch.Tensor({{1,2},{3,4}})
th> m
 1  2
 3  4
[torch.DoubleTensor of size 2x2]

th> m:gt(2)
 0  0
 1  1
[torch.ByteTensor of size 2x2]

th> m:eq(2)
 0  1
 0  0
[torch.ByteTensor of size 2x2]

th> m[m:eq(2)] = 456
th> m
   1  456
   3    4
[torch.DoubleTensor of size 2x2]
```

**Comment by fmassa** [comment]
There was some discussion about relational operators in https://github.com/torch/torch7/issues/495 , and it seems that it's not possible to overload them to return anything sifferent from `false` or `true`.

**Comment by liboyue** [comment]
@andreaskoepf @fmassa Thanks!
