### ISSUE TITLE
undefined symbol: THCFloat2Half

### ISSUE THREAD

**Issue by mklf** [torch/torch7#648]
Hello all,
I encountered  a problem when I call `torch.Tensor(2,3):cudaHalf()` and  `cutorch.hasHalf` is `true`,this is my error message:
`/home/lifang/torch/install/bin/luajit: symbol lookup error: /home/lifang/torch/install/lib/libTHC.so: undefined symbol: THCFloat2Half
`

**Comment by soumith** [comment]
upgrade your cutorch via: luarocks install cutorch

**Comment by rdabral** [comment]
I am getting a similar error, but the undefined symbol is TH_CONVERT_ACCREAL_TO_REAL. Here's the error message:
/home/rishabh/torch/install/bin/luajit: symbol lookup error: /home/rishabh/torch/install/lib/lua/5.1/libTHNN.so: undefined symbol: TH_CONVERT_ACCREAL_TO_REAL

**Comment by pavanky** [comment]
@rdabral That is a macro not a function. Do you have any local modifications. It should not be showing up as an undefined symbol..
