### ISSUE TITLE
Torch fails on power platform with error for SpatialSubtractiveNormalization_2dkernel

### ISSUE THREAD

**Issue by jagadale** [torch/torch7#654]
SpatialSubtractiveNormalization_2dkernel
error on state
 LT(<) violation   val=296930.07056291, condition=1e-05
        /opt/../share/lua/5.1/torch/Tester.lua:26: in function 'assertlt'
        /opt/../share/lua/5.1/nn/test.lua:1391: in function </opt/../share/lua/5.1/nn/test.lua:1359>

**Comment by soumith** [comment]
we do not support powerpc and have no active plans to do so.

**Comment by jagadale** [comment]
failure seems to be easy, if you can just guide what is going wrong it will help us. All other test cases are passing,
