### ISSUE TITLE
Problem storing result with conv2

### ISSUE THREAD

**Issue by aroellin** [torch/torch7#663]
The function `torch.conv2` doesn't save the result correctly when using the `[Res,]` argument. I guess `Res` needs to be contiguous. This doesn't happen with, e.g., `torch.add`.

    th> A = torch.Tensor({{1,2,3},{4,5,6},{7,8,9}})
    th> A
     1  2  3
     4  5  6
     7  8  9
    [torch.DoubleTensor of size 3x3]

    th> K = torch.Tensor{{1,2},{3,4}}
    th> K
     1  2
     3  4
    [torch.DoubleTensor of size 2x2]

    th> torch.conv2(A,K)  # This is OK
     23  33
     53  63
    [torch.DoubleTensor of size 2x2]

    th> R = torch.Tensor(2,7):zero()
    th> R
     0  0  0  0  0  0  0
     0  0  0  0  0  0  0
    [torch.DoubleTensor of size 2x7]

    th> # Trying to store the result into a sub matrix of R doesn't work!
    th> torch.conv2(R:narrow(2,3,2),A,K) 
    th> R
      0   0  23  33  53  63   0
      0   0   0   0   0   0   0
    [torch.DoubleTensor of size 2x7]

As a comparison, the function `torch.add` works fine:

    th> torch.add(R:narrow(2,3,2),K,K)
    th> R
     0  0  2  4  0  0  0
     0  0  6  8  0  0  0
    [torch.DoubleTensor of size 2x7]

**Comment by deltheil** [comment]
Yes: in such a case the result tensor is expected to be [contiguous](https://github.com/torch/torch7/blob/599222ec29bfd7a1eb6c38365b6db2aeccda291e/lib/TH/generic/THTensorConv.c#L89). In the current state of the code it sounds like an additional `THArgCheck` at `THTensor_(conv2Dmul)` level would be welcome.

**Comment by deltheil** [comment]
An alternative could be to clone the result tensor a la `addr` ([clone](https://github.com/torch/torch7/blob/2243cbd0b8de8ad457b0dae1d7b8b926dcb0cb84/lib/TH/generic/THTensorMath.c#L954) then [copy](https://github.com/torch/torch7/blob/2243cbd0b8de8ad457b0dae1d7b8b926dcb0cb84/lib/TH/generic/THTensorMath.c#L961)).

**Comment by aroellin** [comment]
Thanks for the comment. Indeed, I use clone and copy at the moment as a workaround. I was trying to patch the conv2 function accordingly, but the problem is buried too deep in the code. 

Anyway, since you've confirmed the problem, I just have to live with it for the time being. The issue is recorded now in case anyone else stumbles over it.
