### ISSUE TITLE
error installation on Mac os

### ISSUE THREAD

**Issue by rsarxiv** [torch/torch7#664]
Always occurs errors as follows:

Prefix set to /Users/zhangjun/torch/install
Installing Lua version: LUAJIT21
CMake Error at /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler
  "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang"
  is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: /Users/zhangjun/torch/build/CMakeFiles/CMakeTmp

  

  Run Build Command:"/usr/bin/make" "cmTC_047d2/fast"

  /Applications/Xcode.app/Contents/Developer/usr/bin/make -f
  CMakeFiles/cmTC_047d2.dir/build.make CMakeFiles/cmTC_047d2.dir/build

  Building C object CMakeFiles/cmTC_047d2.dir/testCCompiler.c.o

  
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
  -Wa,-q -o CMakeFiles/cmTC_047d2.dir/testCCompiler.c.o -c
  /Users/zhangjun/torch/build/CMakeFiles/CMakeTmp/testCCompiler.c

  clang: error: unsupported argument '-q' to option 'Wa,'

  make[1]: *** [CMakeFiles/cmTC_047d2.dir/testCCompiler.c.o] Error 1

  make: *** [cmTC_047d2/fast] Error 2

Can somebody help me?Thanks a lot.

**Comment by soumith** [comment]
Could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking the torch7 package. We'll happily reply there. Thanks.

**Comment by rsarxiv** [comment]
ok thanks a lot.
