### ISSUE TITLE
Numeric results of __div (operator) and torch.div are different for floats

### ISSUE THREAD

**Issue by markpeot** [torch/torch7#665]
a/b and torch.div(a,b) produce different results.

Example:
```
a = torch.Tensor{5.485723897298472867}:float()
b = 6.75897509789057

d1 = a/b
d2 = torch.div(a, b) 
d3 = torch.mul(a, 1/b)  -- This is the same as the implementation of / 

print(' This should be zero, but is not: ', d1 - d2) -- returns --5.9605E-8

print(' This is zero: ', d1 - d3)  
```

Discussion:  
* __div is implemented as torch.mul(a, 1/b[1]) in generic/TensorOperator.c
* torch.div is implemented via element-by-element division.

I believe that the result of torch.div *should* match the result derived from __div.  

v/r
Mark

**Comment by soumith** [comment]
You're right. If no one has objections with this change, I'll be sending a PR to fix this in the next few days.
