### ISSUE TITLE
baddbmm with not contiguous res tensor

### ISSUE THREAD

**Issue by JeremyMorvan** [torch/torch7#671]
Hi all,

I've just encountered an bug with the baddbmm function. It seems to be due to the non-contiguousity of the result tensor. Here is how to reproduce it : 

```
a = torch.randn(1,3,2)
b = torch.randn(1,2,6)
c = torch.randn(1,3,6,2):select(4,1)
cc = c:clone()

print((c-cc):abs():max())
c:baddbmm(a,b)
cc:baddbmm(a,b)
print((c-cc):abs():max())
```

Same thing happens in Cuda.

Thank you,
Jérémy

**Comment by akashmehra** [comment]
You probably need to use index (followed by a reshape) instead of select (select doesn't change the stride). index will give you a new tensor though and will be slow.

**Comment by JeremyMorvan** [comment]
Yes, I'll find another way to do what I want to do (probably slower) but I posted this message because I don't think this is due to my usage of baddbmm : 
This looks like an operation that does not give the same result for two tensors that have the same content and the same size.

**Comment by fmassa** [comment]
This is indeed a bug. I'm fixing it. Thanks for the bug report !
