### ISSUE TITLE
Multiple Calls to forward backward results in different gradient values

### ISSUE THREAD

**Issue by jaiabhayk** [torch/torch7#678]
I noticed differenet gradient and funciton values, when i run forward/backward passes multiple times, ie.:-

local feval = function(x)

      if x ~= parameters then parameters:copy(x) end

      

      for ii=1,10 do

      gradParameters:zero()

      local outputs = model:forward(inputs)

      local f = criterion:forward(outputs, targets)

      local df_do = criterion:backward(outputs, targets)

      model:backward(inputs, df_do)

      print('f:' ,f)

      print('gradParameters:select(1,4):', gradParameters:select(1,4))

      end

I modified the following below code (train.lua):-

https://github.com/szagoruyko/cifar.torch

Below are the values for multiple passes:-

f:      2.3644347190857 

gradParameters:select(1,4):     0.044307205826044

f:      2.3353869915009 

gradParameters:select(1,4):     -0.065141014754772

f:      2.4054944515228 

gradParameters:select(1,4):     -0.068587675690651

f:      2.3545389175415 

gradParameters:select(1,4):     -0.00055959774181247

f:      2.3607265949249 

gradParameters:select(1,4):     -0.045512720942497

f:      2.358110666275  

gradParameters:select(1,4):     -0.014055838808417

f:      2.3740320205688 

gradParameters:select(1,4):     -0.052351955324411

f:      2.356383562088  

gradParameters:select(1,4):     -0.0074184881523252

f:      2.3853816986084 

gradParameters:select(1,4):     0.026203541085124

Any idea why it might be happening, in each iteration I am reseting the gradient parameters to zero before forward/backward passes ?

**Comment by jaiabhayk** [comment]
Even more precisely, if you call multiple times the code== outputs = model:forward(inputs), it gives different output everytime which is causing issue:-

for ii=1,10 do
       outputs = model:forward(inputs)
      print('outputs:select(1,4):', outputs:select(1,4))
      end

outputs:select(1,4):    -0.1507

-0.0350

-0.3732

-0.1635

 0.3870

-0.1836

-0.0319

 0.0047

-0.0485

 0.0375

[torch.CudaTensor of size 10]



outputs:select(1,4):     0.4712

-0.4351

 0.2075

 0.1827

 0.3260

-0.2062

 0.2182

-0.1095

 0.2208

-0.0091

[torch.CudaTensor of size 10]



outputs:select(1,4):    -0.6828

-0.2905

-0.0211

 0.0114

 0.1190

-0.3154

 0.0561

 0.0011

-0.2033

 0.2285

[torch.CudaTensor of size 10]

**Comment by soumith** [comment]
This is a question, and it is for our forums: https://groups.google.com/forum/#!forum/torch7
You've already posted there, and someone will answer there soon.

**Comment by jaiabhayk** [comment]
I filed it as a bug/issue, because output should be consistent for multiple calls to model:forward(inputs) ?

**Comment by soumith** [comment]
it's not a bug because some of the CUDA kernels (presumably the ones that cifar.torch is using) are not deterministic. They produce slightly different results at each pass. Also, it is not clear that it was a bug in the first place, not sure what other stuff cifar.torch is doing under the hood. Regardless, a bug report for cunn has to be opened here: https://github.com/torch/cunn
