### ISSUE TITLE
Creating a new torch object results in "has no call operator"

### ISSUE THREAD

**Issue by iN1k1** [torch/torch7#681]
Hi All,
I'm using Torch in an object-oriented manner. I've followed the [tutorial ](https://github.com/torch/torch7/blob/master/doc/utility.md) to create a new custom class MyClass using the `torch.class()` method, i.e.
```torch
local myClass, parent = torch.class('MyClass', 'MyClassParent') 
function __init(something)
parent:__init(something)
end
```

Then I started filling the `myClass` object with a couple of functions. One of such functions creates a new object of type `MyClass`, i.e.
```torch
function test(foo)
local myLocalClass = MyClass(foo)
end
```
However, when the code reaches such a point I'm getting the following message: "MyClassParent has no call operator".

If I then change the test function to:
```torch
function test(foo)
 local myLocalClass = MyClass.new(foo)
end
```
it works, however the `__init(something)` method always refers to the same parent instance and does not create it for each call to `MyClass.new(foo)`.

I'm running the code on Ubuntu 14.04. I've updated all the torch related packages to the last distro.
Is there anyone who is getting a similar issue?

Thanks
Niki

**Comment by albanD** [comment]
In your first code sample, the `__init` function that you create is global and not associated to `myClass` is that a typo? If not you it should look like: 
```lua
local myClass, parent = torch.class('MyClass', 'MyClassParent') 
function myClass:__init(something)
  parent.__init(self, something)
end
```

**Comment by iN1k1** [comment]
Hi albanD,
thanks for your super quick reply!
Yup! You're right, that is a typo (same for the `foo()` function).. both are associated with the `myClass` object instance.

**Comment by albanD** [comment]
Ok.
Could you provide a small peace of code that reproduce the error "MyClassParent has no call operator"? This will be simpler to find where the problem is.

**Comment by iN1k1** [comment]
Hi albanD..
You know what.. I was just typing in the mwe.. then I found my huge mistake..
I was actually calling the `__init` function of `myClass` not passing it the current `self` object but giving it as input the `parent` itself.. So for anyone who might face the same issue.. here is the reason:
I was using the following WRONG code  
```lua
local myClass, parent = torch.class('MyClass', 'MyClassParent') 
function myClass:__init(something)
parent:__init(something) -- This is wrong!
end
```
which calls the `__init(something)` function using the `parent` objects itself due to the `:` operator shortcut!
The CORRECT working code is thus:
```lua
local myClass, parent = torch.class('MyClass', 'MyClassParent') 
function myClass:__init(something)
parent.__init(self, something) -- This is right!
end
```
Thanks albanD for the indirect support.. the syntax code highlighter helped a lot note the difference in your code and the one I was using!
Please consider this issue as solved... ;)
