### ISSUE TITLE
simple example of using optim to train a network?

### ISSUE THREAD

**Issue by hughperkins** [torch/torch7#684]
In the doc, I guess we are still using weird ways of training that no-one ever uses, is that a fair impression?

Can we have an example that uses optim, which I think is the standard recently?

Example of an issue based on some tutorial from the dark ages :-P

https://github.com/hughperkins/clnn/issues/21#issuecomment-219415509

**Comment by hughperkins** [comment]
I suppose this bug should be logged against `nn` really.  Anyway, here is the training example provided currently:

https://github.com/torch/nn/blob/master/doc/training.md#nn.traningneuralnet.dok

- no minibatches
- this really bizarroid metatable stuff
- totally inconsistent with how people actually use torch :-P

**Comment by soumith** [comment]
merged! Thanks :)

**Comment by Atcold** [comment]
> weird ways of training that no-one ever uses

I use it, I've created tutorials about it and teach it to beginners. `optim` requires another package to be taught first.
If you want to explain how to use `optim`, then well, you can add more documentation, but basic training techniques should be not removed.

**Comment by culurciello** [comment]
agreed
