### ISSUE TITLE
How to get the gradient from the learned models?

### ISSUE THREAD

**Issue by ajeetksingh** [torch/torch7#688]
Hi,

I use the following snippet of code to load the weights for visualization purposes:

`model = torch.load('modelfile')`
`layer_1_wts = model:get(1).weight
`
Is there any way I could get the **gradients** too?

Thanks :)

**Comment by soumith** [comment]
Could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking the torch7 package. We'll happily reply there. Thanks.

**Comment by ajeetksingh** [comment]
Oh, I didn't know that.. 
Apologies. :)
