### ISSUE TITLE
example-linear-regression.lua bug

### ISSUE THREAD

**Issue by zinyang** [torch/torch7#689]
Hello, 

I tried the linear regression example, and I did some modifications, more specifically, I added code to save the model (by using torch.save) every epoch and changed the optimizer to adagrad. 

So what I did was, I picked two (of the saved) models and tried to run the network uppon them, I  loaded them using torch.load and called the method model:evaluate() also commented the model:backward line and printed the loss in both cases. 
What I found is, that returned loss is the exactly same in both cases 2904.4629103637 even though the models have different loses. 

Is it supposed to work this way?

[examp.lua.txt](https://github.com/torch/torch7/files/272970/examp.lua.txt)
filename format examp_model_"timestamp" _ "iter" _ "loss"
[examp_model_1463673012_4552_2921.2644803106.txt](https://github.com/torch/torch7/files/272972/examp_model_1463673012_4552_2921.2644803106.txt) 
[examp_model_1463673053_1544_2469.7540212613.txt](https://github.com/torch/torch7/files/272971/examp_model_1463673053_1544_2469.7540212613.txt)

**Comment by soumith** [comment]
Could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking the torch7 package. We'll happily reply there. Thanks.
