### ISSUE TITLE
Slow down on CPU in ubuntu 14.04

### ISSUE THREAD

**Issue by chsasank** [torch/torch7#691]
Hi,
I'm running a file with the following code in my macbook air and a ubuntu server with i7 cpu:
```lua
for i = 1,32*3 do 
    img1 = torch.rand(3,224,224)
    img2 = torch.rand(3,224,224)
    alpha = 0.5
    tocl = torch.tic()
    img1:mul(alpha):add(1 - alpha, img2)
    print(torch.toc(tocl))
end
```

on my macbook air:
```
$ time th test.lua
real    0m0.524s
user    0m0.363s
sys    0m0.144s
```

On ubuntu server:
```
$ time th test.lua
real    0m7.031s
user    0m11.184s
sys     0m6.260s
```
7s vs 0.5s is surprising! Is this a bug?

I have rerun the code with `img1 = torch.rand(3,224,224):cuda()` and `img2 = torch.rand(3,224,224)` and this time:
```
real    0m0.952s
user    0m0.524s 
sys     0m0.296s  
```

So this seems like a cpu-specific issue. May be a BLAS issue?
I reinstalled by:
```
$ cd ~/torch
$ ./install-deps
$ ./install.sh
```

In the log, I got:
```
-- Checking for [mkl - guide - pthread - m]
--   Library mkl: not found
-- MKL library not found
-- Checking for [openblas]
--   Library openblas: /usr/lib/libopenblas.so
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Performing Test BLAS_F2C_DOUBLE_WORKS
-- Performing Test BLAS_F2C_DOUBLE_WORKS - Failed
-- Performing Test BLAS_F2C_FLOAT_WORKS
-- Performing Test BLAS_F2C_FLOAT_WORKS - Success
-- Found a library with BLAS API (open).
-- Looking for cheev_
-- Looking for cheev_ - not found
-- It seems OpenBlas has not been compiled with Lapack support
-- Looking for cheev_
-- Looking for cheev_ - found
-- Found a library with LAPACK API. (generic)
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Performing Test C_HAS_inline
-- Performing Test C_HAS_inline - Success
-- C inline is supported (inline)
-- Performing Test C_HAS_THREAD
-- Performing Test C_HAS_THREAD - Success
-- Configuring done
-- Generating done
```
BLAS is found but additions are still slow on CPU.

Can somebody look into this?

Thanks,
Sasank.

**Comment by albanD** [comment]
Do you have the same behavior if your add `torch.setnumthreads(1)` at the beginning of your script?

**Comment by chsasank** [comment]
Yep, that works!

With `torch.setnumthreads(1)`, there is no more slowdown:
```
real    0m0.823s                   
user    0m0.600s 
sys     0m2.404s      
```

Can you please explain why this happened?

**Comment by chsasank** [comment]
Is it related to [this issue](https://github.com/torch/image/issues/7) here ?

**Comment by albanD** [comment]
Yes, the tensor you consider are above the given threshold (100 000 elements in the tensor).

**Comment by chsasank** [comment]
But then, why does it work alright on mac?

**Comment by soumith** [comment]
clang on mac doesn't have OpenMP, that's why.

**Comment by chsasank** [comment]
Thanks a lot, @albanD @soumith

**Comment by alice-cool** [comment]
Could you give some suggestions about cpu edition Torch7 installed on Linux system?
Because my CUDA11.0 doesn't match the cmake 3. So I want to install CPU Torch. 

On the official website, I think it only lists the procedures about GPU Torch installation.
