### ISSUE TITLE
addmm documentation

### ISSUE THREAD

**Issue by bonan-colfax** [torch/torch7#692]
in maths.md
addmm is:
`[res] torch.addmm([res,] [beta,] [v1,] M [v2,] mat1, mat2)`
in THTensorMath.c
addmm is:
`void THTensor_(addmm)(THTensor *r_, real beta, THTensor *t, real alpha, THTensor *m1, THTensor *m2)`

is v1 removed and is v2 alpha?

**Comment by soumith** [comment]
This should give you exact details: https://github.com/torch/torch7/blob/master/TensorMath.lua#L506-L530

But tl;dr: yes.
