### ISSUE TITLE
Debian package of Torch7 module

### ISSUE THREAD

**Issue by CDLuminate** [torch/torch7#696]
@soumith @borisfom

I'm working on on Torch Debian packaging, and now I have successfully built `lua-torch-torch7` package locally. I'll upload it some time later.

This partially solves torch/distro#70

BTW, I wish torch upstream can make releases so I can write a file named `watch`, which automatically tracks upstream updates, so we can update corresponding modules in time.

https://bugs.debian.org/826532

FYI, I currently use such version for paths package: `0~20160604-g69d7a01`, where the HEAD commit hash is following -g, and the date is the latest commit date.

Thanks.

**Comment by CDLuminate** [comment]
packaging repo is here:
http://anonscm.debian.org/cgit/debian-science/packages/lua-torch-torch7.git/

this package is currently pending for review:
https://bugs.debian.org/826715

**Comment by borisfom** [comment]
@CDLuminate : thanks a lot! I am going to try it. Where should we get compatible luajit package ?

**Comment by CDLuminate** [comment]
@borisfom `Debian/experimental` ships `luajit 2.1.0`

**Comment by CDLuminate** [comment]
`lua-torch-torch7_0~20160803-g17ff317-1` uploaded to debian/experimental. Ubuntu/devel will not have this package untill uploaded to Debian/sid (namely Debian/Unstable)

**Comment by CDLuminate** [comment]
https://buildd.debian.org/status/package.php?p=lua-torch-torch7&suite=experimental

Torch7 build is success on `amd64`, `arm64`, `i386`, `mips`, `powerpc`, and `ppc64el` architectures.
(here I'm still correct if you had checked the link above)

That is to say it seems that the torch7 code didn't suffer from portability problem.

I'm marking this issue as done, although it's still not available for Debian/sid.
