### ISSUE TITLE
spell error at tensor.md

### ISSUE THREAD

**Issue by anoidgit** [torch/torch7#699]
"Returns true iff the dimensions of the Tensor match the elements of the storage."
should be
"Returns true if the dimensions of the Tensor match the elements of the storage."

**Comment by soumith** [comment]
usually, iff refers to (if and only if) in math terminology. Maybe that's what the docs are implying: http://mathworld.wolfram.com/Iff.html

**Comment by anoidgit** [comment]
thank you
