### ISSUE TITLE
Install: could NOT find Qt4 (found suitable version "4.8.5", minimum required is "4.3.0")

### ISSUE THREAD

**Issue by zygmuntz** [torch/torch7#70]
When I run the install scripts, I get the following error. How to fix it?

curl -sk https://raw.githubusercontent.com/torch/ezinstall/master/install-deps | bash
curl -sk https://raw.githubusercontent.com/torch/ezinstall/master/install-luajit+torch | bash

(...)

[100%] Built target cunn
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/lib/luarocks/rocks/cunn/scm-1/lib/libcunn.so
-- Set runtime path of "/usr/local/lib/luarocks/rocks/cunn/scm-1/lib/libcunn.so" to "$ORIGIN/../lib:/opt/OpenBLAS/lib:/usr/local/lib:/usr/local/cuda/lib64"
-- Installing: /usr/local/lib/luarocks/rocks/cunn/scm-1/lua/cunn/init.lua
-- Installing: /usr/local/lib/luarocks/rocks/cunn/scm-1/lua/cunn/test.lua
Warning: Directory 'doc' not found
Updating manifest for /usr/local/lib/luarocks/rocks

cunn scm-1 is now built and installed in /usr/local/ (license: BSD)
Installing https://raw.githubusercontent.com/torch/rocks/master/qtlua-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/qtlua-scm-1.rockspec... switching to 'build' mode
Cloning into 'qtlua'...
remote: Counting objects: 171, done.
remote: Compressing objects: 100% (161/161), done.
remote: Total 171 (delta 9), reused 132 (delta 1)
Receiving objects: 100% (171/171), 357.84 KiB | 170.00 KiB/s, done.
Resolving deltas: 100% (9/9), done.
Checking connectivity... done.
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DLUA=/usr/local/bin/luajit -DLUA_BINDIR="/usr/local/bin" -DLUA_INCDIR="/usr/local/include" -DLUA_LIBDIR="/usr/local/lib" -DLUADIR="/usr/local/lib/luarocks/rocks/qtlua/scm-1/lua" -DLIBDIR="/usr/local/lib/luarocks/rocks/qtlua/scm-1/lib" -DCONFDIR="/usr/local/lib/luarocks/rocks/qtlua/scm-1/conf" && make

-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find Qt4 (missing: QT_MOC_EXECUTABLE QT_RCC_EXECUTABLE
  QT_UIC_EXECUTABLE) (found suitable version "4.8.5", minimum required is
  "4.3.0")
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindQt4.cmake:1393 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:27 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_qtlua-scm-1-2097/qtlua/build/CMakeFiles/CMakeOutput.log".
See also "/tmp/luarocks_qtlua-scm-1-2097/qtlua/build/CMakeFiles/CMakeError.log".

Error: Build error: Failed building.

**Comment by HaiguangWen** [comment]
I have this very same issue on my Mac.
```
Could NOT find Qt4 (missing: QT_RCC_EXECUTABLE) (found suitable version
"4.8.7", minimum required is "4.3.0")                                  
```
Any easy solution?

**Comment by Atcold** [comment]
It looks like you may have *Anaconda* installed on your system.
Simply take it out from your `PATH` and everything should install just fine.

**Comment by aabobakr** [comment]
installing anaconda's qt using `conda install pyqt=4` worked for me.
