### ISSUE TITLE
Luajit: symbol lookup error after reinstalling 'cutorch'

### ISSUE THREAD

**Issue by todpole3** [torch/torch7#701]
After running

`luarocks install cutorch
`
(At that point I actually have cutorch installed on the machine hence I basically did a reinstallation.)

I seem to be getting this error out of no clue:

> /home/xilin/Toolkits/torch/install/bin/luajit: symbol lookup error: /home/xilin/Toolkits/torch/install/lib/lua/5.1/libTHCUNN.so: undefined symbol: THC_overlappingIndices

**Comment by szagoruyko** [comment]
update cunn too:
```
luarocks install cunn
```

**Comment by todpole3** [comment]
Thanks. 

My solution is to run 

`./clean.sh`

from the torch installation folder and then re-installed everything.

**Comment by ArghyaPal** [comment]
I am getting this error:

`th> require "cunn"
/home/arghya/torch/install/bin/luajit: symbol lookup error: /home/arghya/torch/install/lib/libTHC.so: undefined symbol: _ZNSt13random_device7_M_initERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
`

I did:
1. Several time fresh installation
2. rm -rf ~/.cache/luarocks

but no luck..
