### ISSUE TITLE
Module cwrap is not found (install without sudo)

### ISSUE THREAD

**Issue by zhongzho** [torch/torch7#702]
Hi Soumith, 

I am installing Torch on CentOS 6.7 on my lab cluster without sudo. I have tried your one line ezinstall, but it produce the error since I do not have sudo. 

So I am installing lua and luarocks to my $HOME and then did the following, 

luarocks --from=https://raw.githubusercontent.com/torch/rocks/master/ install torch

The error says cwrap is not found, but I installed cwrap properly: 
luarocks --from=https://raw.githubusercontent.com/torch/rocks/master/ install cwrap
Installing https://raw.githubusercontent.com/torch/rocks/master/cwrap-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/cwrap-scm-1.rockspec... switching to 'build' mode
Cloning into 'cwrap'...
remote: Counting objects: 17, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 17 (delta 1), reused 8 (delta 1), pack-reused 0
Receiving objects: 100% (17/17), 13.53 KiB, done.
Resolving deltas: 100% (1/1), done.
Updating manifest for /home/zhongzhou/lib/luarocks/rocks
cwrap scm-1 is now built and installed 

Since I do not have sudo, what is your advice of going forward? Thank you! 

Cheers, 
Zhong

**Comment by zhongzho** [comment]
+Soumith, is there a way to specify the path for cwrap so that it can be found? Right now the default is to search for it in usr/bin but I installed lua and luarocks in my $HOME and I do not have sudo. Thanks!

**Comment by fmassa** [comment]
you should not use ezinstall, it's outdated. Use the instructions from the website instead http://torch.ch/docs/getting-started.html#_

**Comment by zhongzho** [comment]
This link is the first one I tried, it does not work if there is no sudo rights.

**Comment by zhongzho** [comment]
+Soumith, I have tried all the above ways, it does not work on the server when I do not have sudo rights. 

Please advise me in how to proceed.
