### ISSUE TITLE
maskedCopy implemented (or documented) strangely

### ISSUE THREAD

**Issue by mranzinger** [torch/torch7#703]
Reading the documentation for maskedCopy, I would expect the function to behave in a manner consistent with the following:

1) `dest[i] = mask[i] ? src[i] : dest[i]`

but it appears as though it's actually implemented something like this:

2)
```
k = 0
dest[i] = mask[i] ? src[k++] : dest[i]
```

which seems strange to me given the wording of the docs

"Copies the masked elements of tensor into itself. The masked elements are those elements having a corresponding 1 in the mask Tensor." With the word "_corresponding_", it would imply the first definition of the function. The latter part of the docs "The source tensor should have at least as many elements as the number of 1s in the mask." hint at what function is actually computing, but it doesn't follow from the first part. 

So, assuming the function is implemented properly as (2), is there an implementation of (1) somewhere? I'm actually not sure what the wording for (2) should be since it seems to be a weird hybrid of a select and a copy.

**Comment by soumith** [comment]
i completely agree with you. When I first read the docs of this function, I had a wtf moment as well.

I improved the doc via https://github.com/torch/torch7/commit/4b0ec6dd3382df69806c479d8de308c25373b74e and added another simple example at the beginning.
