### ISSUE TITLE
After :resize() elements are not contiguous in memory

### ISSUE THREAD

**Issue by ngimel** [torch/torch7#708]
Readme page for resize says "In particular, the elements of the resized tensor are contiguous in memory." Yet, if the new size is the same as the old size, and tensor was non-contiguous, it remains non-contiguous:

```
th> b=torch.FloatTensor(2,2,8)
th> b:stride()
 16
  8
  1
[torch.LongStorage of size 3]
th> b=b:transpose(1,2)
th> b:stride()
  8
 16
  1
[torch.LongStorage of size 3]
th> b=b:resize(2,2,8)
th> b:stride()
  8
 16
  1
[torch.LongStorage of size 3]
```

If old and new sizes differ, the new tensor is contiguous as expected.

**Comment by iamalbert** [comment]
It seems that when "resizing" to equal size the underlying Storage is not resized either.
https://github.com/torch/torch7/blob/master/lib/TH/generic/THTensor.c#L711

**Comment by ngimel** [comment]
The storage should not be resized when resizing to an equal (or smaller) size. Tensor should become contiguous, however.

**Comment by fmassa** [comment]
Fixing this would solve https://github.com/torch/torch7/issues/289
I proposed a simple fix for a special case of it in https://github.com/torch/torch7/pull/295, but changing such a core function should be done with care

**Comment by andreaskoepf** [comment]
+1 for guaranteeing contiguous tensors after resize and changing the code to match the [documentation](https://github.com/torch/torch7/blob/master/doc/tensor.md#resizing) which says "In particular, the elements of the resized tensor are contiguous in memory.". As the contents of a tensor after resize is undefined a simple fix could just update the strides in the `hascorrectsize != 0` case (see [THTensor.c#L679](https://github.com/torch/torch7/blob/master/lib/TH/generic/THTensor.c#L679)) or to reduce code-complexity the whole hascorrect-size tests could be removed.
