### ISSUE TITLE
Torch load in ascii mode through C++ Lua API

### ISSUE THREAD

**Issue by UndeadBlow** [torch/torch7#715]
Hello. I have annoying problem that I can't solve for a month.
I have the model, saved by Torch in ascii mode and I'm trying to load it in Lua script through the C++. 
When I'm loading that model with Lua or Th in console all is ok. But when I an trying to run the same script with C++ API error appear:
`File.lua:259: read error: read 0 blocks instead of 1 at /torch/pkg/torch/lib/TH/THDiskFile.c:332 in function LoadLua`
I've checked Lua version, path, cpath, everything that is possible to check, all is similar to console Lua, but doesn't works. I have only one Lua version on PC, that Torch installed via install.sh, so that can not be bad .so linking issue or wrong header.
Binary models works correctly, only ascii throws error.
What could it be?

**Comment by soumith** [comment]
that is indeed strange. I would start simple and print the filename that you are loading (i.e. the argument to torch.load ) and see that it is the same when going via the torch codepath and C++ codepath...

**Comment by jalajthanaki** [comment]
Hi , I'm getting following errors
` /home/jalaj/torch/install/bin/lua: /home/jalaj/torch/install/share/lua/5.2/torch/File.lua:259: read error:   read 0 blocks instead of 1 at /home/jalaj/torch/pkg/torch/lib/TH/THDiskFile.c:332
stack traceback:
	[C]: in function 'readInt'
	/home/jalaj/torch/install/share/lua/5.2/torch/File.lua:259: in function 'readObject'
	/home/jalaj/torch/install/share/lua/5.2/torch/File.lua:409: in function 'load'
	./data.lua:70: in function 'loadXY'
	rmain.lua:3: in main chunk
	[C]: in function 'dofile'
	...alaj/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: in ?
`

**Comment by jalajthanaki** [comment]
Any Solution or any approach to solve the above issue

Thanks

**Comment by zhihuiwisdom** [comment]
Did you solve it?I've had the same problem   
Thanks，reply
