### ISSUE TITLE
Current Torch7 built error...

### ISSUE THREAD

**Issue by jiapei100** [torch/torch7#728]
Hello...

My working environment:
Ubuntu: 16:04
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.1) 5.4.0 20160609
```
lua: Lua 5.3.1  Copyright (C) 1994-2015 Lua.org, PUC-Rio
jiapei:build$ /usr/bin/env lua -lluarocks.loader
Lua 5.3.1  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> ^C
jiapei:build$ luajit
LuaJIT 2.0.4 -- Copyright (C) 2005-2016 Mike Pall. http://luajit.org/
JIT: ON CMOV SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> ^C
```

After cmake configuration, when I do "make", I got the following error messages:

> [ 55%] Generating random.c
> cd .../torch7 && .../torch7/random.lua .../torch7/build/random.c
> .../torch7/random.lua: 1: local: not in a function
> CMakeFiles/torch.dir/build.make:68: recipe for target 'random.c' failed
> make[2]: *** [random.c] Error 2
> make[2]: Leaving directory '.../torch7/build'
> CMakeFiles/Makefile2:71: recipe for target 'CMakeFiles/torch.dir/all' failed
> make[1]: *** [CMakeFiles/torch.dir/all] Error 2
> make[1]: Leaving directory '.../torch7/build'
> Makefile:130: recipe for target 'all' failed
> make: *** [all] Error 2

Any suggestions???

Cheers
Pei

**Comment by soumith** [comment]
Could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking the torch7 package. We'll happily reply there. Thanks.

**Comment by jiapei100** [comment]
@soumith Yes. Thank you ... Already done... 
Close this topic .....
