### ISSUE TITLE
"luarocks install cunn" fail to install..

### ISSUE THREAD

**Issue by jiapei100** [torch/torch7#731]
To whom it may concern:

`jiapei:lua$ luarocks install cunn`
gives me the following error messages:

> [  9%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_MultiLabelMarginCriterion.cu.o
> [ 11%] Building NVCC (Device) object lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_SpatialConvolutionMM.cu.o
> /tmp/luarocks_cunn-scm-1-WTP7Ai/cunn/lib/THCUNN/MultiLabelMarginCriterion.cu:3:35: fatal error: THCReduceApplyUtils.cuh: No such file or directory
> compilation terminated.
> CMake Error at THCUNN_generated_MultiLabelMarginCriterion.cu.o.cmake:207 (message):
>   Error generating
>   /tmp/luarocks_cunn-scm-1-WTP7Ai/cunn/build/lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_MultiLabelMarginCriterion.cu.o
> 
> 
> lib/THCUNN/CMakeFiles/THCUNN.dir/build.make:84: recipe for target 'lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_MultiLabelMarginCriterion.cu.o' failed
> make[2]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/THCUNN_generated_MultiLabelMarginCriterion.cu.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
>    Removing non-existent dependency file: generic/THStorage.h
> 
> 
> CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
>    Removing non-existent dependency file: generic/THStorageCopy.h
> 
> 
> CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
>    Removing non-existent dependency file: generic/THCStorage.h
> 
> 
> CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
>    Removing non-existent dependency file: generic/THCStorageCopy.h
> 
> 
> CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
>    Removing non-existent dependency file: generic/THTensor.h
> 
> 
> CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
>    Removing non-existent dependency file: generic/THTensorCopy.h
> 
> 
> CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
>    Removing non-existent dependency file: generic/THTensorRandom.h
> 
> 
> CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
>    Removing non-existent dependency file: generic/THTensorMath.h
> 
> 
> CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
>    Removing non-existent dependency file: generic/THTensorConv.h
> 
> 
> CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
>    Removing non-existent dependency file: generic/THTensorLapack.h
> 
> 
> CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
>    Removing non-existent dependency file: generic/THCTensor.h
> 
> 
> CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
>    Removing non-existent dependency file: generic/THCTensorCopy.h
> 
> 
> CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
>    Removing non-existent dependency file: generic/THCTensorMath.h
> 
> 
> CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
>    Removing non-existent dependency file: generic/THCTensorMathBlas.h
> 
> 
> CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
>    Removing non-existent dependency file: generic/THCTensorMathPairwise.h
> 
> 
> CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
>    Removing non-existent dependency file: generic/THCTensorMathPointwise.h
> 
> 
> CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
>    Removing non-existent dependency file: generic/THCTensorMathReduce.h
> 
> 
> CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
>    Removing non-existent dependency file: generic/THCTensorMathCompare.h
> 
> 
> CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
>    Removing non-existent dependency file: generic/THCTensorMathCompareT.h
> 
> 
> CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA/make2cmake.cmake:65 (message):
>    Removing non-existent dependency file: generic/THCTensorMasked.h
> 
> 
> CMakeFiles/Makefile2:103: recipe for target 'lib/THCUNN/CMakeFiles/THCUNN.dir/all' failed
> make[1]: *** [lib/THCUNN/CMakeFiles/THCUNN.dir/all] Error 2
> Makefile:127: recipe for target 'all' failed
> make: *** [all] Error 2
> 
> Error: Build error: Failed building.
> jiapei:lua$ 

How to "luarocks install cunn"

Cheers

**Comment by fmassa** [comment]
Installation issues should go to the [Google Groups](https://groups.google.com/forum/#!forum/torch7), this helps keeping github issues for tracking bugs only.

For your issue, you should probably update `cutorch` before installing the latest `cunn`.
```
luarocks install cutorch
```
