### ISSUE TITLE
Inconsistent behavior of nn.Clamp in CPU and GPU modes

### ISSUE THREAD

**Issue by zhehangd** [torch/torch7#734]
I found that nn.Clamp acts differently in CPU mode and GPU mode at critical points. In nn the derivative is 0 and in cunn the derivative is 1. The following code reveals this problem.

```
require 'nn'
require 'cunn'

do
  local layer  = nn.Clamp(0,1)
  local input  = torch.Tensor({-1,0,0.5,1,2})
  local output = layer:forward(input)
  local gradOutput = torch.Tensor({1,1,1,1,1})
  local gradInput  = layer:backward(input,gradOutput)
  print(gradInput)
end

do
  local layer  = nn.Clamp(0,1):cuda()
  local input  = torch.Tensor({-1,0,0.5,1,2}):cuda()
  local output = layer:forward(input)
  local gradOutput = torch.Tensor({1,1,1,1,1}):cuda()
  local gradInput  = layer:backward(input,gradOutput):cuda()
  print(gradInput)
end
```

which results in

```
 0
 1
 1
 1
 0
[torch.DoubleTensor of size 5]

 0
 0
 1
 0
 0
[torch.CudaTensor of size 5]
```
It seems that ReLU gives 0 derivative at critical points in both modes, so I suppose the CPU mode Clamp should be changed to agree with the other.

I met this problem when I tried to apply gradient descent to the input image, in which I clamped the value between 0 and 1 in the first layer of the network. In CPU mode the black background got updated, but in GPU mode the pixels died because of 0 gradient. In practice the problem can be solved by using a small negative number, e.g. -1e-3, instead of 0.

**Comment by soumith** [comment]
this is now fixed by @gchanan via https://github.com/torch/cunn/pull/329
