### ISSUE TITLE
Is CUDA 8.0 Supported?

### ISSUE THREAD

**Issue by 3DTOPO** [torch/torch7#735]
I am attempting to reinstall Torch after installing a Pascal based Titan X and the 8.0RC CUDA toolkit on Ubuntu 14.04 and I am getting the following errors.

Is CUDA 8.0RC supported?

> -- Found Torch7 in /home/prime/torch/install
-- Compiling for CUDA architecture: 5.2
-- Configuring done
-- Generating done
-- Build files have been written to: /home/prime/torch/extra/cutorch/build
[  2%] [  4%] [  6%] [  9%] [ 11%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCBlas.cu.o
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorSort.cu.o
Scanning dependencies of target cutorch_static
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCReduceApplyUtils.cu.o
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorageCopy.cu.o
Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorage.cu.o
[ 13%] CMake Error at THC_generated_THCBlas.cu.o.cmake:206 (message):
  Error generating
>  >/home/prime/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCBlas.cu.o
>
>
>make[2]: *** [lib/THC/CMakeFiles/THC.dir/./THC_generated_THCBlas.cu.o] Error 1
>make[2]: *** Waiting for unfinished jobs....
>CMake Error at THC_generated_THCTensorSort.cu.o.cmake:206 (message):
  Error generating
>  >/home/prime/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorSort.cu.o
>
>
>CMake Error at THC_generated_THCReduceApplyUtils.cu.o.cmake:206 (message):
>  Error generating
>  >/home/prime/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCReduceApplyUtils.cu.o
>
>
>make[2]: *** [lib/THC/CMakeFiles/THC.dir/./THC_generated_THCTensorSort.cu.o] Error 1
>Building C object CMakeFiles/cutorch_static.dir/Storage.c.o
>make[2]: *** [lib/THC/CMakeFiles/THC.dir/./THC_generated_THCReduceApplyUtils.cu.o] Error 1
>CMake Error at THC_generated_THCStorage.cu.o.cmake:206 (message):
>  Error generating
>  >/home/prime/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorage.cu.o
>
>
>[ 16%] make[2]: *** [lib/THC/CMakeFiles/THC.dir/./THC_generated_THCStorage.cu.o] Error 1
CMake Error at THC_generated_THCStorageCopy.cu.o.cmake:206 (message):
  Error generating
>  >/home/prime/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorageCopy.cu.o
>
>
>[ 20%] [ 20%] [ 23%] make[2]: *** [lib/THC/CMakeFiles/THC.dir/./THC_generated_THCStorageCopy.cu.o] Error 1
>make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
>Building C object CMakeFiles/cutorch_static.dir/init.c.o
>make[1]: *** Waiting for unfinished jobs....
>Building C object CMakeFiles/cutorch_static.dir/Tensor.c.o
>Building C object CMakeFiles/cutorch_static.dir/TensorMath.c.o
>[ 25%] Building C object CMakeFiles/cutorch_static.dir/TensorOperator.c.o
>Building C object CMakeFiles/cutorch_static.dir/torch/utils.c.o
>In file included from /home/prime/torch/extra/cutorch/lib/THC/THC.h:4:0,
                 from /home/prime/torch/extra/cutorch/build/TensorMath.c:3:
/home/prime/torch/extra/cutorch/build/lib/THC/THCGeneral.h:8:18: fatal error: cuda.h: No such file or directory
> #include "cuda.h"
>                  ^
>compilation terminated.
>In file included from /home/prime/torch/extra/cutorch/lib/THC/THC.h:4:0,
                 from /home/prime/torch/extra/cutorch/Storage.c:2:
/home/prime/torch/extra/cutorch/build/lib/THC/THCGeneral.h:8:18: fatal error: cuda.h: No such file or directory
 #include "cuda.h"
>                  ^
>compilation terminated.
In file included from /home/prime/torch/extra/cutorch/lib/THC/THC.h:4:0,
>                 from /home/prime/torch/extra/cutorch/Tensor.c:2:
/home/prime/torch/extra/cutorch/build/lib/THC/THCGeneral.h:8:18: fatal error: cuda.h: No such file or directory
 #include "cuda.h"
                  ^
compilation terminated.
In file included from /home/prime/torch/extra/cutorch/init.c:3:0:
/home/prime/torch/extra/cutorch/build/lib/THC/THCGeneral.h:8:18: fatal error: cuda.h: No such file or directory
 #include "cuda.h"
                  ^
compilation terminated.
In file included from /home/prime/torch/extra/cutorch/lib/THC/THC.h:4:0,
                 from /home/prime/torch/extra/cutorch/TensorOperator.c:3:
/home/prime/torch/extra/cutorch/build/lib/THC/THCGeneral.h:8:18: fatal error: cuda.h: No such file or directory
 #include "cuda.h"
                  ^
compilation terminated.
make[2]: *** [CMakeFiles/cutorch_static.dir/TensorMath.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/cutorch_static.dir/TensorOperator.c.o] Error 1
make[2]: *** [CMakeFiles/cutorch_static.dir/Tensor.c.o] Error 1
make[2]: *** [CMakeFiles/cutorch_static.dir/Storage.c.o] Error 1
make[2]: *** [CMakeFiles/cutorch_static.dir/init.c.o] Error 1
make[1]: *** [CMakeFiles/cutorch_static.dir/all] Error 2
make: *** [all] Error 2
>
>Error: Build error: Failed building.

**Comment by soumith** [comment]
First run ./clean.sh before running ./install.sh

**Comment by 3DTOPO** [comment]
Thanks - that seems to have got me further, but now it fails with the following. 

>Found CUDA on your machine. Installing CUDA packages
Warning: unmatched variable LUALIB
cmake -E make_directory build && cd build && cmake .. -DLUALIB= -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/prime/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/prime/torch/install/lib/luarocks/rocks/cutorch/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install
>
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Torch7 in /home/prime/torch/install
CMake Error at /usr/share/cmake-2.8/Modules/FindCUDA.cmake:548 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  CMakeLists.txt:7 (FIND_PACKAGE)
>
>
-- Configuring incomplete, errors occurred!
See also "/home/prime/torch/extra/cutorch/build/CMakeFiles/CMakeOutput.log".

**Comment by soumith** [comment]
Can you rm -rf ~/torch and reclone / reinstall 
http://torch.ch/docs/getting-started.html#_

**Comment by GhettoGirl** [comment]
I updated to CUDA 8 yesterday and that broke my old Torch install. A lot of symbol lookup errors and stuff like that.

Recloned a fresh copy and tried to compile today. There are a lot of errors related to `match_functions.h` (from CUDA toolchain).

```
/opt/cuda/include/math_functions.h(8897): error: cannot overload functions distinguished by return type alone
```

Here some more output: http://hastebin.com/xohacanobu.js

--

Since I'm using only one program which requires Torch, I'm gonna downgrade CUDA today. So don't expect anymore help from me.

**Comment by atique81** [comment]
Hi @soumith 
is it possible to run torch on NVIDIA GTX 1080 which requires CUDA 8?

**Comment by soulmachine** [comment]
I have the same question too

**Comment by soumith** [comment]
@GhettoGirl that should be fixed now
@soulmachine @atique81 yes it is supported from the day one.

**Comment by atique81** [comment]
Thanks @soumith !
