### ISSUE TITLE
Compatibility issue while loading data in Torch

### ISSUE THREAD

**Issue by aparnamhnty** [torch/torch7#741]
I am new to Torch.....I want to implement the code given at http://torch.ch/blog/2015/07/30/cifar.html
While trying to execute train.lua........it initially shows the parameters and configures the model, but while loading the data, it complains that 'Failed to load function from bytecode: (binary): cannot load incompatible bytecode.
What shall I do to solve this problem.
![capture](https://cloud.githubusercontent.com/assets/9334941/17765583/69021fe8-6544-11e6-888f-ac8ead36c5bb.PNG)

**Comment by Atcold** [comment]
You already posted this error here https://github.com/torch/torch7/issues/641
Why are you making duplicates?
