### ISSUE TITLE
torch7 does not compile with gcc-6 and intel-mkl compilers

### ISSUE THREAD

**Issue by kirk86** [torch/torch7#742]
I have the following problem of not being able to compile torch7 with neither gcc-6 nor intel-mkl compilers.

`system: osx 10.11`
`compilers: default clang version 7.x.x [no openmp support built-in] `
                  `clang bit older version 3.x.x [with openmp support built-in]`
                  `gcc-6 [with openmp support built-in]`
                  `intel-mkl [openmp support built-in]`

So far I've been able to build torch only with the different clang versions but not with gcc-6 or with the intel versions.

Another thing to notice is that if I compile and build torch7 with clang and then install a package via `luarocks` for instance `rnn` but instead I instruct `luarocks` to use the intel-mkl compilers instead of the default clang then it builds fine without any problems, which is bizarre.

Here is an error I get trying to compile with `gcc-6`:

`Prefix set to /Users/user/torch/install`
`Installing Lua version: LUAJIT21`
`CMake Error at /usr/local/Cellar/cmake/3.6.1/share/cmake/Modules/CMakeTestCCompiler.cmake:61 (message):`
  `The C compiler "/usr/local/bin/gcc-6" is not able to compile a simple test
  program.`

  `It fails with the following output:`

  ` Change Dir: /Users/user/torch/build/CMakeFiles/CMakeTmp`

  `Run Build Command:"/usr/bin/make" "cmTC_a57d5/fast"`

  `/Library/Developer/CommandLineTools/usr/bin/make -f
  CMakeFiles/cmTC_a57d5.dir/build.make CMakeFiles/cmTC_a57d5.dir/build`

 ` Building C object CMakeFiles/cmTC_a57d5.dir/testCCompiler.c.o`

 ` /usr/local/bin/gcc-6 -o CMakeFiles/cmTC_a57d5.dir/testCCompiler.c.o -c
  /Users/user/torch/build/CMakeFiles/CMakeTmp/testCCompiler.c`

  `Linking C executable cmTC_a57d5`

  /usr/local/Cellar/cmake/3.6.1/bin/cmake -E cmake_link_script
  CMakeFiles/cmTC_a57d5.dir/link.txt --verbose=1

  `/usr/local/bin/gcc-6 -Wl,-search_paths_first`
 ` -Wl,-headerpad_max_install_names`
  `CMakeFiles/cmTC_a57d5.dir/testCCompiler.c.o -o cmTC_a57d5`

 ` ld: library not found for -lSystem`

  `collect2: error: ld returned 1 exit status`

  `make[1]: *** [cmTC_a57d5] Error 1`

  `make: *** [cmTC_a57d5/fast] Error 2`

 ` CMake will not be able to correctly generate this project.`
`Call Stack (most recent call first):`
 ` CMakeLists.txt`

**Comment by CDLuminate** [comment]
Torch7 compiles with GCC-6 (gcc-6.2) under linux.

**Comment by kirk86** [comment]
For me it didn't work under OS X. Plus that even if I manage to compile when I run it I get segmentation fault.

**Comment by kirk86** [comment]
I've managed to make ti work after @soumith's suggestion
install with the following command 

`TORCH_LUA_VERSION=LUA52 ./install.sh`
