### ISSUE TITLE
Indices returned by sort function are incorrect

### ISSUE THREAD

**Issue by davidhunteruk** [torch/torch7#743]
In the following example, the indices returned by the sort function are incorrect.

```lua
q = torch.Tensor(3,2)
q[1] = torch.rand(1,2)
q[2] = torch.rand(1,2)
q[3] = torch.rand(1,2)
print(q)
qs, i = torch.sort(q,1)
print(qs)
print(i)
```

Example output:

```lua
 0.6536  0.4772
 0.9452  0.0418
 0.6151  0.0454
[torch.DoubleTensor of size 3x2]

 0.6151  0.0418
 0.6536  0.0454
 0.9452  0.4772
[torch.DoubleTensor of size 3x2]

 3  2
 1  3
 2  1
[torch.LongTensor of size 3x2]
```

**Comment by fmassa** [comment]
Why are they incorrect? You are sorting over the first dimension, and the indices for your example seems good to me.

**Comment by davidhunteruk** [comment]
Apologies - that was a bad example! See the edited version above. It seems to happen sporadically.

**Comment by soumith** [comment]
hi, the edited example also seems to have a correct answer.
Are you expecting to sort over the second dimension maybe? i.e. torch.sort(q, 2) ?

**Comment by fmassa** [comment]
I'm sorry, but I still can't see why they are wrong. Could you please write the expected output as well?

**Comment by davidhunteruk** [comment]
No, you're right, I misinterpreted what the indices represented. For some reason, I assumed that they indicated the post-sort order of elements in the original tensor i.e.

```lua
 0.6536  0.4772
 0.9452  0.0418
 0.6151  0.0454
[torch.DoubleTensor of size 3x2]

 0.6151  0.0418
 0.6536  0.0454
 0.9452  0.4772
[torch.DoubleTensor of size 3x2]

 2  3
 3  1
 1  2
[torch.LongTensor of size 3x2]
```
