### ISSUE TITLE
LookupTable.lua:75: bad argument #3 to 'index' (Tensor | LongTensor expected, got torch.CudaLongTensor)

### ISSUE THREAD

**Issue by badripatro** [torch/torch7#747]
Error detail analysis:
_________________________________________________________________
 $th train.lua -gpuid 0
_________________________________________________________________
using CUDA on GPU 0...
Loading data files...
Loading train fc7 features from data/train_fc7.t7
Loading val fc7 features from data/val_fc7.t7
Parameters: 6813673
Batches: 1076
Max iterations: 53800
/home/cse/torch/install/bin/luajit:
/home/cse/torch/install/share/lua/5.1/nn/Container.lua:67:
In 1 module of nn.Sequential:
/home/cse/torch/install/share/lua/5.1/nn/LookupTable.lua:75: bad argument
#3 to 'index' (Tensor | LongTensor expected, got torch.CudaLongTensor)
stack traceback:
   [C]: in function 'index'
   /home/cse/torch/install/share/lua/5.1/nn/LookupTable.lua:75: in
function </home/cse/torch/install/share/lua/5.1/nn/LookupTable.lua:68>
   [C]: in function 'xpcall'
   /home/cse/torch/install/share/lua/5.1/nn/Container.lua:63: in function
'rethrowErrors'
   /home/cse/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function
'forward'
   train.lua:375: in function 'opfunc'
   /home/cse/torch/install/share/lua/5.1/optim/adam.lua:37: in function
'adam'
   train.lua:476: in main chunk
   [C]: in function 'dofile'
   .../cse/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in
main chunk
   [C]: at 0x00405970

WARNING: If you see a stack trace below, it doesn't point to the place
where this error occurred. Please use only the one above.
stack traceback:
   [C]: in function 'error'
   /home/cse/torch/install/share/lua/5.1/nn/Container.lua:67: in function
'rethrowErrors'
   /home/cse/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function
'forward'
   train.lua:375: in function 'opfunc'
   /home/cse/torch/install/share/lua/5.1/optim/adam.lua:37: in function
'adam'
   train.lua:476: in main chunk
   [C]: in function 'dofile'
   .../cse/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in
main chunk
   [C]: at 0x00405970

_________________________________________________________________
Reffered : I have searched this problem and found following link :
_________________________________________________________________
https://groups.google.com/forum/#!topic/torch7/6igs4XdoSW4
https://github.com/jcjohnson/neural-style/issues/210
https://github.com/jcjohnson/torch-rnn/issues/56
https://groups.google.com/forum/#!topic/torch7/uEeBWwkyDPU
_________________________________________________________________
Solution : After ,I referred those link, i have re-installed following  packages

luarocks install nn
luarocks install cunn
luarocks install cunn 1.0-0
luarocks install torch
luarocks install cutorch
luarocks install cutorch 1.0-0
_________________________________________________________________
But, I got same error. Please let me know how do i solve this issue.

**Comment by soumith** [comment]
Could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking the torch7 package. We'll happily reply there. Thanks.

**Comment by badripatro** [comment]
Sure, Thanks
