### ISSUE TITLE
A very strange problem about indexing cuda tensor.

### ISSUE THREAD

**Issue by lymhust** [torch/torch7#754]
The time of indexing a cuda tensor changes significantly after call the forward function of an arbitrary neural network. Here is my code:

```
tensor = torch.CudaLongTensor(20)

-- Calculate the time
sys.tic()
a = tensor[1]
print('Time: '..(sys.toc()*1000)..'ms')

-- Call an arbitrary NN
input = torch.CudaTensor(1,3,48,48)
model:forward(input)

-- Calculate the time again
sys.tic()
a = tensor[1]
print('Time: '..(sys.toc()*1000)..'ms')
```
 Result is very strange:
Time: 0.5948ms
Time: 27.2789ms

Can anybody provide me some help about this problem? Thanks!

**Comment by soumith** [comment]
answered here https://github.com/torch/cutorch/issues/493#issuecomment-244344991
Please do not open two duplicate issues
