### ISSUE TITLE
Handling Variable length sequences in training an RNN

### ISSUE THREAD

**Issue by mineshmathew** [torch/torch7#759]
I have been using a C++ implementation of RNN+CTC written by Alex Graves  for a sequence learning problem - to transcribe a sequence of feature vectors into a sequence of labels. And there the implementation supports only 'online training' ie one sequence is fed at a time, gradients are computed based on the criterion and weights are updated then and there itself. Now that all the new deep learning libraries support parallelism using GPUs,  I wanted to try out my problem in one of these. I have a few queries in this regard, when it comes to the issue of having sequences of variable lengths
- I understand that the training is often done in batches. How would I do that if my sequences are of variable lengths. I know that padding is an option. But I would prefer not to pad my sequences with zeros.
- If I decide not to use and fall back to  'online training' mode, ( ie with one sequence at a time), does it mean that I loose the advantage of parallelism. What I mean to ask is if I do online training does it mean that running on a GPU wont give me any advantage in terms of training time
- I also read about features like maskZero(). How is it exactly different from padding

**Comment by nicholas-leonard** [comment]
@mineshmathew `maskZero()` allows you to separate each sequence with a single zero-element. In this way, it isn't as wasteful as padding the start or end of each sequence with multiple zero-elements.
