### ISSUE TITLE
Compilation issues on Nvidia TK1

### ISSUE THREAD

**Issue by SergeyMalashenko** [torch/torch7#763]
NEON.c:64:13: error: ‘z’ undeclared (first use in this function)
       :"r" (z), "r" (x),"r" (y), "r"(n)

THVectorDispatch.c:19:62: error: expected ‘}’ before ‘;’ token
       FUNCTION_IMPL(THVector_(fill_NEON), SIMDExtension_NEON);
                                                              ^
THVectorDispatch.c:40:61: error: expected ‘}’ before ‘;’ token
       FUNCTION_IMPL(THVector_(add_NEON), SIMDExtension_NEON);
                                                             ^
THVectorDispatch.c:62:62: error: expected ‘}’ before ‘;’ token
       FUNCTION_IMPL(THVector_(diff_NEON), SIMDExtension_NEON);
                                                              ^
THVectorDispatch.c:84:63: error: expected ‘}’ before ‘;’ token
       FUNCTION_IMPL(THVector_(scale_NEON), SIMDExtension_NEON);
                                                               ^
THVectorDispatch.c:106:61: error: expected ‘}’ before ‘;’ token
       FUNCTION_IMPL(THVector_(mul_NEON), SIMDExtension_NEON);

**Comment by penzant** [comment]
The compilation succeeded with:

NEON.c L32
-> static void THFloatVector_diff_NEON(float *z, const float *x, const float *y, const long n) {

THVectorDispatch.c L19 L40 L62 L84 L106
replace ';' with ','

on TX1, Ubuntu 16.04

**Comment by BTNC** [comment]
I guess replace line32 with `static void THFloatVector_diff_NEON(float *z, const float *x, const float *y, const long n) {` should solve it.

**Comment by soumith** [comment]
thanks to @BTNC for tracking this down. This is fixed in master via https://github.com/torch/torch7/commit/eb397ad0bd77cfe67a5e27f05d25217cba95ffef

**Comment by sansoy** [comment]
I'm experiencing the same compile issues on my nVidia TK1 ....

[  3%] Built target luaT
[  6%] Building C object lib/TH/CMakeFiles/TH.dir/THVector.c.o
In file included from generic/THVectorDispatch.c:1:0,
                 from /home/ubuntu/torch/pkg/torch/lib/TH/THVector.c:17:
/home/ubuntu/torch/pkg/torch/lib/TH/generic/THVectorDispatch.c:19:62: error: expected ‘}’ before ‘;’ token
       FUNCTION_IMPL(THVector_(fill_NEON), SIMDExtension_NEON);
                                                              ^
/home/ubuntu/torch/pkg/torch/lib/TH/generic/THVectorDispatch.c:40:61: error: expected ‘}’ before ‘;’ token
       FUNCTION_IMPL(THVector_(add_NEON), SIMDExtension_NEON);
                                                             ^
/home/ubuntu/torch/pkg/torch/lib/TH/generic/THVectorDispatch.c:62:62: error: expected ‘}’ before ‘;’ token
       FUNCTION_IMPL(THVector_(diff_NEON), SIMDExtension_NEON);
                                                              ^
/home/ubuntu/torch/pkg/torch/lib/TH/generic/THVectorDispatch.c:84:63: error: expected ‘}’ before ‘;’ token
       FUNCTION_IMPL(THVector_(scale_NEON), SIMDExtension_NEON);
                                                               ^
/home/ubuntu/torch/pkg/torch/lib/TH/generic/THVectorDispatch.c:106:61: error: expected ‘}’ before ‘;’ token
       FUNCTION_IMPL(THVector_(mul_NEON), SIMDExtension_NEON);
                                                             ^
make[2]: *** [lib/TH/CMakeFiles/TH.dir/THVector.c.o] Error 1
make[1]: *** [lib/TH/CMakeFiles/TH.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.

**Comment by BTNC** [comment]
Replace ";" with "," at the end of each line 19, 40, 62, 84, 106 may solve it.

**Comment by rtarquini** [comment]
I'm having the same issue as sansoy.  I've replaced the ';' with ',' but now get assembler errors when build THVector.c.0

![capture](https://cloud.githubusercontent.com/assets/14279702/19244346/fb0354d8-8ee9-11e6-8b61-f65931df98c5.JPG)
