### ISSUE TITLE
[bug] Tensor operations 

### ISSUE THREAD

**Issue by thunderink** [torch/torch7#771]
I just found out something weird about Tensor operations in torch. I tried:

![screenshot from 2016-09-21 21-56-56](https://cloud.githubusercontent.com/assets/18603761/18734863/599d6608-8046-11e6-8a57-649cd2eeb4a3.png)

So apparently even when the dimensions don't match these operations still work...

Is this how Tensor supposed to work or this is an actual bug?

**Comment by Atcold** [comment]
Hmm... This could be annoying if, say, one forgets a transposition.

```lua
th> a
 1  2  3
 3  4  5
[torch.DoubleTensor of size 2x3]

                                                                      [0.0002s]
th> b = torch.Tensor{ {1, 1, 1}, {0, 0, 0}}
                                                                      [0.0002s]
th> b
 1  1  1
 0  0  0
[torch.DoubleTensor of size 2x3]

                                                                      [0.0002s]
th> a - b
 0  1  2
 3  4  5
[torch.DoubleTensor of size 2x3]

                                                                      [0.0002s]
th> a - b:t()
 0  2  2
 3  3  5
[torch.DoubleTensor of size 2x3]
```

**Comment by ksharsha** [comment]
It looks like torch handles the tensor operations in form of vectors and then resizes the result into the tensor of required size.
a=torch.Tensor{{1,2,3},{4,5,6}}
c=torch.Tensor{{1,2},{3,4},{5,6}}
th> a-c
 0  0  0
 0  0  0
[torch.DoubleTensor of size 2x3]

                                                                      [0.0004s]
th> c-a
 0  0
 0  0
 0  0
[torch.DoubleTensor of size 3x2]
However, if the total number of elements in both tensors are not the same we get an error while doing operations.
th> c=torch.Tensor{{1,2},{3,4}}
                                                                      [0.0001s]
th> a-c
inconsistent tensor size at /home/harsha/git/torch/pkg/torch/lib/TH/generic/THTensorMath.c:576

**Comment by soumith** [comment]
what @ksharsha is correct. this is not a bug.
