### ISSUE TITLE
How to initialize weights?

### ISSUE THREAD

**Issue by gonzalolc** [torch/torch7#781]
Hello
I'm new in torch and lua and probably it is a very easy question to solve.
I'm trying to use xavier initialization adding this to my model. (from [https://github.com/e-lab/torch-toolbox/tree/master/Weight-init](url)

`-- design model 
require('nn') 
model = nn.Sequential() 
model:add(nn.SpatialConvolutionMM(3,4,5,5))

-- reset weights 
method = 'xavier' 
model_new = require('weight-init')(model, method)
`

when runing my model, I get:
ERROR: /usr/share/lua/5.1/trepl/init.lua:384: module 'weight-init' not found:No LuaRocks module found for weight-init

where should weight-init.lua be?

thanks

**Comment by farrajota** [comment]
You should check @Kaixhin [nninit](https://github.com/Kaixhin/nninit) for weight initialization (it has a simple example on how to use it)
