### ISSUE TITLE
How to designate tasks to GPUs with torch7?

### ISSUE THREAD

**Issue by AlecWong** [torch/torch7#786]
Hi, I encounter with an issue about the unbalanced usage of GPUs recently.
nvidia-smi:
```
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     10131    C   /home/u/torch/install/bin/luajit         2479MiB |
|    1     10131    C   /home/u/torch/install/bin/luajit         2479MiB |
|    2     10131    C   /home/u/torch/install/bin/luajit         2479MiB |
|    3     10131    C   /home/u/torch/install/bin/luajit         5458MiB｜
```
I have 4 GPUs, each is 6GBytes.  And I need to allocate a CudaTensor which is 1.2M-by-batch_size.
According to the the usage information, the input images are distributed to these four GPUs equally. And the CudaTensor is distributed to GPU-3. So, when I increase the batch_size, the memory of GPU-3 will be used up, while there are lots of memory not used in the other 3 GPUs.. 
So, I wonder is there any way to re-distributed the data processed by each GPUs? I mean, for example, assume batch size is 256, then: GPU0,GPU1 and GPU2 process 240 images, and GPU3 processes 16 images?

**Comment by soumith** [comment]
you can do this by changing the internals of DataParallelTable here https://github.com/torch/cunn/blob/master/DataParallelTable.lua#L540-L575

but it isn't exposed to the user directly.
