### ISSUE TITLE
Error: Build error: Failed building.

### ISSUE THREAD

**Issue by shravankumar147** [torch/torch7#787]
Found CUDA on your machine. Installing CUDA packages
Warning: unmatched variable LUALIB
Warning: unmatched variable jopts

isTegra=$(uname -a   | grep -E '(tegra|aarch)' | wc | awk '{print $1'})
if [ "1" -eq "$isTegra"  ]
  then
    jopts=3
  else
    jopts=$(getconf _NPROCESSORS_ONLN)
fi

echo "Building on $jopts cores"
cmake -E make_directory build && cd build && cmake .. -DLUALIB= -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS} -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/users/shravankumar/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/users/shravankumar/torch/install/lib/luarocks/rocks/cutorch/scm-1" && make -j install

Building on 8 cores
-- Found Torch7 in /users/shravankumar/torch/install
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find CUDA: Found unsuitable version "5.5", but required is at
  least "6.5" (found /usr)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:313 (_FPHSA_FAILURE_MESSAGE)
  /users/shravankumar/torch/install/share/cmake/torch/FindCUDA.cmake:1009 (find_package_handle_standard_args)
  CMakeLists.txt:7 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/users/shravankumar/torch/extra/cutorch/build/CMakeFiles/CMakeOutput.log".

Error: Build error: Failed building.

**Comment by howard0su** [comment]
Could NOT find CUDA: Found unsuitable version "5.5", but required is at least "6.5" (found /usr)

Your Cuda version is too old.
