### ISSUE TITLE
torch.ByteTensor.THNN backend not imported

### ISSUE THREAD

**Issue by xiaolixiaoyi** [torch/torch7#790]
I tried to train a CNN, but I got the following error:

`/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/nn/Container.lua:67:
In 1 module of nn.Sequential:
.../torch/install/share/lua/5.1/nn/SpatialConvolutionMM.lua:70: torch.ByteTensor.THNN backend not imported
stack traceback:
	[C]: in function 'assert'
	.../torch/install/share/lua/5.1/nn/SpatialConvolutionMM.lua:70: in function <.../torch/install/share/lua/5.1/nn/SpatialConvolutionMM.lua:69>
	[C]: in function 'xpcall'
	/root/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	sgd_ccs.lua:280: in function 'opfunc'
	/root/torch/install/share/lua/5.1/optim/sgd.lua:44: in function 'optimMethod'
	sgd_ccs.lua:301: in function 'train'
	dssgd_ccs.lua:101: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/root/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	sgd_ccs.lua:280: in function 'opfunc'
	/root/torch/install/share/lua/5.1/optim/sgd.lua:44: in function 'optimMethod'
	sgd_ccs.lua:301: in function 'train'
	dssgd_ccs.lua:101: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670`

I've included 'cunn' and 'cudnn' in my code.

**Comment by fmassa** [comment]
Your input is a `ByteTensor`. Convert it to `float` before passing it to the network.

**Comment by xiaolixiaoyi** [comment]
Yes, it works!
Thank you very much!

**Comment by fmassa** [comment]
This issue can be closed

**Comment by auggie909** [comment]
@xiaolixiaoyi 
Hi, I met the same problem. Would you please tell me how did you convert? Thanks!
