### ISSUE TITLE
Installation of Torch deps failed on macOS sierra

### ISSUE THREAD

**Issue by chenzhekl** [torch/torch7#791]
```
qt: This formula either does not compile or function as expected on macOS
versions newer than El Capitan due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
```

Since homebrew has no plan to support Qt for macOS newer than El Capitan (Homebrew/homebrew-core#1957), it is unable to install Torch anymore. Do you have plan to switch to Qt5?

**Comment by reachbp** [comment]
Hi , I am facing the same issue... Do we have to rollback to Mac El Capitan?

**Comment by chenzhekl** [comment]
Hi @reachbp, I think yes. For torch, migrating from Qt4 to Qt5 requires a lot of work and time. It is hard to say whether it will happen or not. For homebrew, they just didn't plan to fix the problem. Thus rollback may be the best solution for now.

**Comment by soumith** [comment]
I've now made qt optional for OSX in the instal-deps script. The optional packages qtlua and qttorch will not install during the install process, but that's fine.
https://github.com/torch/distro/commit/d10e1f05d3d07356586c0d843c426f89aa986ae0

**Comment by reachbp** [comment]
Works now on Mac sierra,, although I had to comment out Line 82...

**Comment by imaclover** [comment]
skip qt install will case cannot install camera
