### ISSUE TITLE
cutorch Error Downloading, Luajit, cuda 7.5

### ISSUE THREAD

**Issue by arthurptj** [torch/torch7#805]
Pls help 

arthur$ luarocks install cutorch
Installing https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec... switching to 'build' mode
Cloning into 'cutorch'...
remote: Counting objects: 202, done.
remote: Compressing objects: 100% (157/157), done.
remote: Total 202 (delta 57), reused 87 (delta 43), pack-reused 0
Receiving objects: 100% (202/202), 190.90 KiB | 0 bytes/s, done.
Resolving deltas: 100% (57/57), done.
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/Users/arthur/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/Users/arthur/torch/install/lib/luarocks/rocks/cutorch/scm-1" && make -j$(getconf _NPROCESSORS_ONLN) install

-- The C compiler identification is AppleClang 7.0.0.7000072
-- The CXX compiler identification is AppleClang 7.0.0.7000072
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /Users/arthur/torch/install
CMake Error at /opt/local/share/cmake-3.4/Modules/FindCUDA.cmake:617 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  CMakeLists.txt:7 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_cutorch-scm-1-3370/cutorch/build/CMakeFiles/CMakeOutput.log".

Error: Build error: Failed building.

**Comment by arthurptj** [comment]
I specify the path of CUDA_TOOLKIT_ROOT_DIR beforehand as it says but it still wont work.

**Comment by BTNC** [comment]
Could you be more specific how you specified the variable beforehand?

**Comment by arthurptj** [comment]
CUDA_BIN_PATH=/usr/local/cuda

**Comment by BTNC** [comment]
If cmake still suggests specifying CUDA_TOOLKIT_ROOT_DIR after setting env CUDA_BIN_PATH, you have to check if cuda is properly installed under CUDA_BIN_PATH. It it is suggesting some other errors, it is likely your cuda is installed inproperly and you may need to install the complete toolkit properly. Please google, there should be similar cuda installation issues like yours.

**Comment by arthurptj** [comment]
found my problem "AMD Radeon HD 6750M"
