### ISSUE TITLE
can you recommend a IDE for me to debug lua?

### ISSUE THREAD

**Issue by vanpersie32** [torch/torch7#806]
hi, as is known to us, it is difficult to debug program written in lua. So guys, can you recommend a good IDE to debug LUA for me?

**Comment by wydges** [comment]
zbstudio, don't know alternatives
https://studio.zerobrane.com/

**Comment by vanpersie32** [comment]
yeah, I am using it.But somehow I encounter a problem. When I set a breakpoint and run lua program. The program suspends at the breakpoint, but when I try to evaluate value of some variables. The software reports error, cannot evaluate when the program is running .It it so weird...

**Comment by pkulchenko** [comment]
@vanpersie32, if it's reproducible and you can provide details, open a ticket at ZeroBraneStudio or send me an email (address in the profile) and I'll take a look.
