### ISSUE TITLE
ARM64 NEON unknown register name 'r0' in asm

### ISSUE THREAD

**Issue by jhondge** [torch/torch7#808]
Torch building failure on arm64 under Mac os 10.11.6

NEON.c:25:15: error: 
      unknown register name 'r0' in asm
      : "cc", "r0", "r4",  "memory",
              ^
NEON.c:65:15: error: 
      unknown register name 'r0' in asm
      : "cc", "r0", "r1", "r2", "r4", "memory",
              ^
NEON.c:144:15: error: 
      unknown register name 'r0' in asm
      : "cc", "r0", "r2", "r5", "memory",

PS: It's work fine at armv7 (32bit)

**Comment by soumith** [comment]
this should now be fixed. All NEON inline assembly has been removed: https://github.com/torch/torch7/blob/master/lib/TH/vector/NEON.c
