### ISSUE TITLE
Does torch support atrous convolution layer now?

### ISSUE THREAD

**Issue by brisker** [torch/torch7#810]
Does torch support atrous convolution layer now?

**Comment by fmassa** [comment]
Look for `SpatialDilatedConvolution`

**Comment by brisker** [comment]
@fmassa 
any demos or tutorials on the official websites or somewhere?

**Comment by fmassa** [comment]
@brisker There is documentation available https://github.com/torch/nn/blob/master/doc/convolution.md#nn.SpatialDilatedConvolution

**Comment by brisker** [comment]
@fmassa 
Thanks a lot!
Besides, could you please recommend some papers or open source project implemented in torch using  SpatialDilatedConvolution(like FCN or something else)

**Comment by fmassa** [comment]
I know about this open source code in torch https://github.com/e-lab/ENet-training
The paper is linked in the README.

**Comment by brisker** [comment]
@fmassa 
what about some "instance segmentation" demos implemented in Torch?

**Comment by fmassa** [comment]
Facebook has released their SharpMask code for instance segmentation.
https://github.com/facebookresearch/deepmask

**Comment by brisker** [comment]
@fmassa 
Thanks

**Comment by brisker** [comment]
@fmassa 
what if I want to concat the two outputs? what function to use?
![image](https://cloud.githubusercontent.com/assets/13804492/19640333/b3b83262-9a0e-11e6-9d52-ca1ce0aecedd.png)

**Comment by fmassa** [comment]
It's all in the docs. You can either use [`nn.Concat`](https://github.com/torch/nn/blob/master/doc/containers.md#nn.Concat), or [`nn.ConcatTable`](https://github.com/torch/nn/blob/master/doc/table.md#nn.ConcatTable) followed by your other function (if it is to concatenate the outputs, [`nn.JoinTable`](https://github.com/torch/nn/blob/master/doc/table.md#jointable) )
Also, those questions are better suited for the [Google Groups](https://groups.google.com/forum/embed/?place=forum%2Ftorch7#!forum/torch7), or the [Gitter ](https://gitter.im/torch/torch7), as we use github issues to track bugs.

**Comment by brisker** [comment]
@fmassa 
How to use 4 gpus on torch?
