### ISSUE TITLE
Uniformly distributed continuous random numbers in closed interval [0, 1] 

### ISSUE THREAD

**Issue by gingerbread10** [torch/torch7#811]
Hi,

Is there a way to generate uniformly distributed real numbers from a closed interval using torch?

Thanks.

**Comment by fmassa** [comment]
`tensor:uniform(a, b)` generates numbers in an open interval. If you want numbers in a closed interval, I'd generate integer numbers (using tensor:random) and then I'd divide by the maximum value for the type (maybe something like 2^32-1 if using doubles, but I'd check the value).
You could also, after the `random` call, apply the modulo with a number (say 10000), and divide by this number.

**Comment by gingerbread10** [comment]
Thanks fmassa! I was also thinking of a work around like that one. It should do the trick.
