### ISSUE TITLE
where is the code and data from http://www.clement.farabet.net/?

### ISSUE THREAD

**Issue by yaoguangshun** [torch/torch7#825]
Hi I have seen one paper about "Learning Hierarchical Features for Scene Labeling".But I can't find the code and data from http://www.clement.farabet.net?  Who has the  relevant link and answer? Looking forward your answer. Thank you so much

**Comment by nicholas-leonard** [comment]
You should ask @clementfarabet

**Comment by clementfarabet** [comment]
I had to take some of this down for legal issues (but most components were moved into nnx) at the time.
