### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by harshmunshi** [torch/torch7#832]
I tried the following command:

git clone https://github.com/torch/distro.git ~/torch --recursive
cd ~/torch; bash install-deps;
./install.sh

But during the installation I get the following error:

/home/ubuntu/torch/extra/cunn/lib/THCUNN/RReLU.cu(17): error: explicit type is missing ("int" assumed)

/home/ubuntu/torch/extra/cunn/lib/THCUNN/RReLU.cu(17): error: "half" is not a class or function template name in the current scope

/home/ubuntu/torch/extra/cunn/lib/THCUNN/RReLU.cu(17): error: expected a ";"

/home/ubuntu/torch/extra/cunn/lib/THCUNN/RReLU.cu(67): warning: parsing restarts here after previous syntax error

/home/ubuntu/torch/extra/cunn/lib/THCUNN/generic/RReLU.cu(30): error: identifier "rreluUpdateOutputTrain" is undefined

/home/ubuntu/torch/extra/cunn/lib/THCUNN/generic/RReLU.cu(38): error: identifier "rreluUpdateOutputTrain" is undefined

/home/ubuntu/torch/extra/cunn/lib/THCUNN/generic/RReLU.cu(55): error: identifier "RReLUUpdateOutputEval_functor" is undefined

/home/ubuntu/torch/extra/cunn/lib/THCUNN/generic/RReLU.cu(55): error: type name is not allowed

/home/ubuntu/torch/extra/cunn/lib/THCUNN/generic/RReLU.cu(30): error: identifier "rreluUpdateOutputTrain" is undefined

/home/ubuntu/torch/extra/cunn/lib/THCUNN/generic/RReLU.cu(38): error: identifier "rreluUpdateOutputTrain" is undefined

/home/ubuntu/torch/extra/cunn/lib/THCUNN/generic/RReLU.cu(55): error: identifier "RReLUUpdateOutputEval_functor" is undefined

/home/ubuntu/torch/extra/cunn/lib/THCUNN/generic/RReLU.cu(55): error: type name is not allowed

11 errors detected in the compilation of "/tmp/tmpxft_00005359_00000000-7_RReLU.cpp1.ii".
CMake Error at THCUNN_generated_RReLU.cu.o.cmake:267 (message):
  Error generating file
  /home/ubuntu/torch/extra/cunn/build/lib/THCUNN/CMakeFiles/THCUNN.dir//./THCUNN_generated_RReLU.cu.o

**Comment by xinyu1607** [comment]
I have a similar problem. And there are other following errors:

/home/torch/extra/cunn/lib/THCUNN/SharedMem.cuh(17): error: identifier "half" is undefined

/home/torch/extra/cunn/lib/THCUNN/SharedMem.cuh(19): error: identifier "half" is undefined

/home/torch/extra/cunn/lib/THCUNN/SharedMem.cuh(20): error: identifier "half" is undefined

/home/torch/extra/cunn/lib/THCUNN/LogSoftMax.cu(86): error: identifier "fmaxType" is undefined

5 errors detected in the compilation of "/tmp/tmpxft_000005ab_00000000-7_LogSoftMax.cpp1.ii".

**Comment by soumith** [comment]
@harshmunshi @xinyu1607 can you update CUDA to atleaast 7.5? I suspect it is lower than that.

@gchanan you prob have to add ifdef guards at certain places

**Comment by gchanan** [comment]
I was able to reproduce these with CUDA 7.0, let me work on fixing this.  As @soumith mentions, updating to CUDA 7.5 should fix for now.

**Comment by xinyu1607** [comment]
@soumith Thank you for your reply. I have fixed this error with CUDA 7.5.
