### ISSUE TITLE
OpenBlas could not be compiled

### ISSUE THREAD

**Issue by BAILOOL** [torch/torch7#835]
Having this error when trying to `bash install-deps;`
![selection_085](https://cloud.githubusercontent.com/assets/11172777/20208199/d7c8d7f4-a82f-11e6-89bf-c9d0452116b3.png)
Any ideas how to resolve it? Thanks in advance.

**Comment by fmassa** [comment]
You should post this issue in OpenBLAS repo https://github.com/xianyi/OpenBLAS
