### ISSUE TITLE
I have wrote my own criterion code, and if I want to convert it into a mini-batch mode, need I modify something based on the current one?

### ISSUE THREAD

**Issue by brisker** [torch/torch7#843]
I have wrote my own criterion code, and if I want to convert it into a mini-batch mode, need I modify something based on the current one? If yes, is there any existing example for me to refer to?

**Comment by fmassa** [comment]
You can write a for loop iterating over the different elements, or write dedicated code for the batch mode, like done in https://github.com/torch/nn/blob/master/MarginRankingCriterion.lua#L12-L29

**Comment by brisker** [comment]
@fmassa 
@samehkhamis 
suppose in criterion.updateGradInput(input,target), after the calculation , I get a 3-d gradient tensor, call it my_grad, using the two 4-d tensors--- input and target. Now I need to back propagate my_grad through the network, so in model.backward(input, my_grad) , input is a 4-d tensor and my_grad is a 3-d tensor, and this  seems to be wrong. So need I copy my_grad (batch_size-1) times and generate a new 4-d gradient tensor?  If not, how to back propagate it into the 4-d inputs?
