### ISSUE TITLE
how to visualize torch network structure?

### ISSUE THREAD

**Issue by brisker** [torch/torch7#847]
how to visualize the torch network structure like this
![image](https://cloud.githubusercontent.com/assets/13804492/20559517/dac7fd5c-b1af-11e6-901f-fbc0d0e517a4.png)

**Comment by fmassa** [comment]
If your network is written in `nngraph`, there is a functionality there to [print it to a graph](https://github.com/torch/nngraph#two-hidden-layers-mlp).
If it is pure `nn`, you can use [`optnet`](https://github.com/fmassa/optimize-net)

**Comment by brisker** [comment]
@fmassa 
 given a input image tensor batch_size * channel * height * width , how to visualize the output tensor's information of every layer  in the network ?(module and nn.identity all in one visualization image)

**Comment by brisker** [comment]
@fmassa 
Thanks !

**Comment by fmassa** [comment]
If that answers your question, could you please close the issue?

**Comment by lutzroeder** [comment]
[Netron](https://www.github.com/lutzroeder/netron) has experimental support for rendering `.t7` models.
