### ISSUE TITLE
I can successfully train my model, but why "cuda runtime error (2) : out of memory..." in test time?

### ISSUE THREAD

**Issue by brisker** [torch/torch7#853]
I train my model on a Titan X with 12GB memory , and during training about 90% of the gpu memory is used, with a batch size of 12. In test time, I just use one image, but why the code returns this memory error?
@fmassa 
@soumith

/home/jcc/torch/install/share/lua/5.1/torch/Tensor.lua:458: cuda runtime error (2) : out of memory at /home/jcc/torch/extra/cutorch/lib/THC/generic/THCStorage.cu:65
stack traceback:
	[C]: in function 'set'
	/home/jcc/torch/install/share/lua/5.1/torch/Tensor.lua:458: in function 'view'
	/home/jcc/torch/install/share/lua/5.1/nn/Reshape.lua:46: in function 'func'
	/home/jcc/torch/install/share/lua/5.1/nngraph/gmodule.lua:345: in function 'neteval'
	/home/jcc/torch/install/share/lua/5.1/nngraph/gmodule.lua:380: in function 'forward'
	[string "require 'torch'   -- torch..."]:66: in main chunk
	[C]: in function 'xpcall'
	/home/jcc/torch/install/share/lua/5.1/itorch/main.lua:210: in function </home/jcc/torch/install/share/lua/5.1/itorch/main.lua:174>
	/home/jcc/torch/install/share/lua/5.1/lzmq/poller.lua:75: in function 'poll'
	/home/jcc/torch/install/share/lua/5.1/lzmq/impl/loop.lua:307: in function 'poll'
	/home/jcc/torch/install/share/lua/5.1/lzmq/impl/loop.lua:325: in function 'sleep_ex'
	/home/jcc/torch/install/share/lua/5.1/lzmq/impl/loop.lua:370: in function 'start'
	/home/jcc/torch/install/share/lua/5.1/itorch/main.lua:389: in main chunk
	[C]: in function 'require'
	(command line):1: in main chunk
	[C]: at 0x00406670

**Comment by fmassa** [comment]
Probably at test time your image is too big?

**Comment by brisker** [comment]
@fmassa 
the same size as in the training dataset

**Comment by fmassa** [comment]
I would double check the data.
Also, can't say much more without more information. If the only difference between train and test is the `:evaluate()` and the data you feed to the net.
I'd say there is a bug in your evaluation code somewhere

**Comment by brisker** [comment]
@fmassa 
find some error in training. I am doing two-class semantic segmentation(background and foreground), and suppose the output of the network is 12 * 2 * 224 * 224 ( where 12 indicates batch size, 2 indicates background and foreground channel ) and in my hand I have 12 *224 * 224 annotation for this mini-batch images, where the 224 *224 tensor is an image with only 0 and 1 pixel value annotation. Is cudnn.SpatialCrossEntropyCriterion() the criterion I should use? 
 If yes , this criterion need the "Classweights" parameter, I can not find any documents showing me how to set this parameter. Could you please tell me? Is it just torch.Tensor{0,1} ?
