### ISSUE TITLE
Does torch have any cluster algorithm libraries, like Kmeans, meanshift, etc. ??

### ISSUE THREAD

**Issue by brisker** [torch/torch7#863]
Does torch have any cluster algorithm libraries, like Kmeans, meanshift, etc. ??

**Comment by liboyue** [comment]
I guess you can try https://github.com/koraykv/unsup/blob/master/kmeans.lua

**Comment by brisker** [comment]
@liboyue  
Is there any that does not need assigning  the cluster center numbers in advance ?

**Comment by soumith** [comment]
Could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking the torch7 package. We'll happily reply there. Thanks.
