### ISSUE TITLE
How could I free the memory on GPU?

### ISSUE THREAD

**Issue by anoidgit** [torch/torch7#864]
I can not load my whole dataset to the GPU, because it is too big, so I load a part of it, put on gpu, and after train a few cycles, I reload another part. My code seems like this:
td={} for i=1,32 do table.insert(td,torch.load("fname"..somerand..".asc"):cuda()) for i=1,1000 do train() for i=1,4 do table.remove(td,1) table.insert(td,torch.load("fname"..somerand..".asc")) end end
but every time it load from the disk, seems the old data on gpu was not freed, the memory usage just goes higher and higher until break.

**Comment by toshi-k** [comment]
Hi anoidgit,

If you want to free the memory explicitly, run this command.
`collectgarbage()`

**Comment by anoidgit** [comment]
Thank you, I have solved this in your way. @toshi-k
