### ISSUE TITLE
torch.Tensor access via :index() delivers inconsistent results after data moved to CUDA device via :cuda()

### ISSUE THREAD

**Issue by goforthanddie** [torch/torch7#877]
Hello there,
the following code reproduces my problem. I want to access a tensor with labels randomly and stumbled across the problem of retrieving inconsistent results when using :index() as access method.

```
require 'cutorch'
i = torch.LongTensor(3)
i[{1}] = 7816227
i[{2}] = 19206839
i[{3}] = 19206840
torch.manualSeed(101)
labels = torch.Tensor(19206840)
labels = labels:random(1,257)
print(tostring(labels:index(1, i)))
print(tostring(labels[i[{1}]]) .. ' ' .. tostring(labels[i[{2}]]) .. ' ' ..tostring(labels[i[{3}]]))
labels = labels:cuda()
print(tostring(labels:index(1, i)))
print(tostring(labels[i[{1}]]) .. ' ' .. tostring(labels[i[{2}]]) .. ' ' ..tostring(labels[i[{3}]]))
```

I expect lines 9 and 12 to produce the same results. but they dont. I get 171, 46, 139 before moving labels to the CUDA device and 171, 13, 13 afterwards in line 12. Interestingly the other access method works fine.

**Comment by artcg** [comment]
Please post the full output including print(labels)

**Comment by goforthanddie** [comment]
```
 171
  46
 139
[torch.DoubleTensor of size 3]

171 46 139
 171
  13
  13
[torch.CudaTensor of size 3]

171 46 139
```

**Comment by soumith** [comment]
you need to replace the line:
labels = labels:cuda()

with 

labels = labels:cudaDouble()

or even better
labels = labels:cudaLong()

CudaTensor is of type FloatTensor, so you are running out of float precision and hence the errors

**Comment by goforthanddie** [comment]
Thanks for your reply, but it seems I can only call :index() having called :cuda(), it does not work having called :cudaDouble() or :cudaLong(). It gives me an 'attempt to call method 'index' (a nil value)'. Any clue?

**Comment by fmassa** [comment]
@goforthanddie you probably need to update cutorch (so best is to update torch. nn, cutorch and cunn).
The corresponding `:cudaLong()` version of index was added in https://github.com/torch/cutorch/pull/461
