### ISSUE TITLE
Architecture not supported on Mac OS Sierra?

### ISSUE THREAD

**Issue by frantic0** [torch/torch7#878]
I am trying to install torch7 on Mac OS Sierra 10.12.2 (16C67)
2.5 GHz Intel Core i7

When run ./install.sh I get 

Prefix set to /Users/user/torch/install
Installing Lua version: LUAJIT21
CMake Error at exe/luajit-rocks/luajit-2.1/CMakeLists.txt:219 (MESSAGE):
  architecture not supported

 Is CUDA a must have for installing torch?

**Comment by soumith** [comment]
@frantic0 you could try: 

```
./clean.sh
TORCH_LUA_VERSION=LUA52 ./install.sh
```

I've just tested it on OSX Sierra, unfortunately i could not replicate the issue.

**Comment by frantic0** [comment]
thanks @soumith

I just did but I get errors..

`
In file included from /Users/francisco/torch/exe/luajit-rocks/lua-5.2/src/luac.c:15:
/Users/francisco/torch/exe/luajit-rocks/lua-5.2/src/lua.h:12:10: fatal error: 'stdarg.h' file not found
#include <stdarg.h>
         ^
1 error generated.
make[2]: *** [exe/luajit-rocks/lua-5.2/CMakeFiles/luac.dir/src/luac.c.o] Error 1
make[1]: *** [exe/luajit-rocks/lua-5.2/CMakeFiles/luac.dir/all] Error 2
make: *** [all] Error 2
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: /Users/francisco/torch/install/lib/liblua.dylib (No such file or directory)
./install.sh: line 90: /Users/francisco/torch/install/bin/luarocks: No such file or directory
Installing common Lua packages
./install.sh: line 94: /Users/francisco/torch/install/bin/luarocks: No such file or directory
 `

**Comment by soumith** [comment]
@frantic0 http://stackoverflow.com/questions/30172986/stdarg-h-file-not-found-error says that the xcode is damaged? not finding stdarg.h is very strange, and definitely points to something amiss with your compiler's standard library

**Comment by frantic0** [comment]
@soumith I tried a clean installation of Xcode and of the command line tools. I also built a test application that includes <cstdarg> or <stdarg.h> and it is working, so it shouldn't be that...


When I run ```TORCH_LUA_VERSION=LUA52 ./install.sh```, I get some more elements
<pre>
Prefix set to /Users/user/torch/install
Installing Lua version: LUA52
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   liblua

This warning is for project developers.  Use -Wno-dev to suppress it.

In file included from /Users/user/torch/exe/luajit-rocks/lua-5.2/src/luac.c:15:
/Users/user/torch/exe/luajit-rocks/lua-5.2/src/lua.h:12:10: fatal error: 
      'stdarg.h' file not found
#include <stdarg.h>
         ^
1 error generated.
make[2]: *** [exe/luajit-rocks/lua-5.2/CMakeFiles/luac.dir/src/luac.c.o] Error 1
make[1]: *** [exe/luajit-rocks/lua-5.2/CMakeFiles/luac.dir/all] Error 2
make: *** [all] Error 2
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: can't open file: /Users/user/torch/install/lib/liblua.dylib (No such file or directory)
./install.sh: line 90: /Users/user/torch/install/bin/luarocks: No such file or directory
Installing common Lua packages
./install.sh: line 94: /Users/user/torch/install/bin/luarocks: No such file or directory

</pre>
Before that I tried to run install-deps and install.sh, for which I got: 
 
<pre>
Updated 1 tap (homebrew/core).
==> Updated Formulae
apache-brooklyn-cli                              axel                                             mitmproxy                                        sbtenv
Warning: git-2.11.0 already installed
Warning: readline is a keg-only and another version is linked to opt.
Use `brew install --force` if you want to install this version
Warning: cmake-3.7.1 already installed
Warning: wget-1.18 already installed
Warning: jpeg-8d already installed
Warning: imagemagick-6.9.7-0 already installed
Warning: zeromq-4.2.0 already installed
Warning: graphicsmagick-1.3.25 already installed
Warning: openssl is a keg-only and another version is linked to opt.
Use `brew install --force` if you want to install this version
Warning: Already linked: /usr/local/Cellar/readline/7.0.1
To relink: brew unlink readline && brew link readline
Warning: The default Caskroom location has moved to /usr/local/Caskroom.

Please migrate your Casks to the new location and delete /opt/homebrew-cask/Caskroom,
or if you would like to keep your Caskroom at /opt/homebrew-cask/Caskroom, add the
following to your HOMEBREW_CASK_OPTS:

  --caskroom=/opt/homebrew-cask/Caskroom

For more details on each of those options, see https://github.com/caskroom/homebrew-cask/issues/21913.
Warning: A Cask for xquartz is already installed.

To re-install xquartz, run:
  brew cask reinstall xquartz
Uninstalling /usr/local/Cellar/gnuplot/5.0.5... (47 files, 2.8M)
==> Using the sandbox
==> Downloading https://downloads.sourceforge.net/project/gnuplot/gnuplot/5.0.5/gnuplot-5.0.5.tar.gz
Already downloaded: /Users/francisco/Library/Caches/Homebrew/gnuplot-5.0.5.tar.gz
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/gnuplot/5.0.5 --with-readline=/usr/local/opt/readline --with-pdf=/usr/local/opt/pdflib-lite --with-qt=no --without-tutorial --witho
==> make
==> make install
🍺  /usr/local/Cellar/gnuplot/5.0.5: 47 files, 2.8M, built in 54 seconds
==> Torch7's dependencies have been installed
</pre>

The results for the install.sh
<pre>
Prefix set to /Users/user/torch/install
Installing Lua version: LUAJIT21
CMake Error at exe/luajit-rocks/luajit-2.1/CMakeLists.txt:219 (MESSAGE):
  architecture not supported
</pre>

I tried to install luajit and lua rocks independently and succeeded, but not using the torch distro.

**Comment by soumith** [comment]
hey @frantic0
I am not sure about a solution here, as I am not able to reproduce the issue (unfortunately).
Can you tell me your XCode version so that I can try and reproduce it myself?

**Comment by frantic0** [comment]
Thanks @soumith. I am using Xcode Version 8.2.1 (8C1002).

**Comment by soumith** [comment]
ok i'm on xcode 8.1, i'm updating now.

**Comment by soumith** [comment]
hey @frantic0 
I installed the latest version of XCode, version 8.2.1.
I still have no issue installing Torch.

One last thing i'd suggest is to install (or update) cmake from homebrew, other than that I'm having a hard time figuring out what's wrong.

**Comment by frantic0** [comment]
Thanks @soumith, just tried on a new machine, a Mac Pro, and everything went fine. No impediment at all...
