### ISSUE TITLE
install.sh check for CUDA fails in Arch

### ISSUE THREAD

**Issue by artcg** [torch/torch7#879]
In the torch install script (install.sh) it checks to see if CUDA is install by 

path_to_nvcc=$(which nvcc)

However by default arch installs CUDA to /opt and nvcc isn't in $PATH so the check fails

Could possibly be fixed by checking 'pacman -Q cuda' if distro is detected as Arch linux

**Comment by artcg** [comment]
BTW the installer didn't work out to use gcc-5 either which is necessary for nvcc so it might be useful to automatically check for that
(worked fine when I ran with ./install.sh CC=gcc-5)

**Comment by pavanky** [comment]
May be send in a PR ?

**Comment by artcg** [comment]
Sure will do that later on
