### ISSUE TITLE
How to use the nn.Threshold() module? I can not find any documents instructions

### ISSUE THREAD

**Issue by brisker** [torch/torch7#883]
How to use the nn.Threshold() module? I can not find any documents instructions.
Besides, can this module be use in convolutional maps? (2D)

**Comment by Cadene** [comment]
If you don't find any documentations, you can use the github search "This repository" functionality :
https://github.com/torch/nn/search?utf8=%E2%9C%93&q=nn.Threshold

Thus you can see how nn.ReLU extend nn.Threshold :
https://github.com/torch/nn/blob/1c0d2bbc1fa7b7ab21ac43883ce043ca209121e9/ReLU.lua

Thus, that Threshold can be used after a nn.SpatialConvolution : https://github.com/torch/nn/blob/1c0d2bbc1fa7b7ab21ac43883ce043ca209121e9/doc/module.md#L326
