### ISSUE TITLE
Getting: atempt to call global 'unpack' (a nil value) error when using torch with lua instead of luaJIT.

### ISSUE THREAD

**Issue by ankerbachryhl** [torch/torch7#885]
Here is the full error:

/torch/install/bin/lua: ./util/model_utils.lua:34: attempt to call global 'unpack' (a nil value)
stack traceback:
	./util/model_utils.lua:34: in function 'storageInSet'
	./util/model_utils.lua:60: in function 'flatten'
	./util/model_utils.lua:103: in function 'combine_all_parameters'
	train.lua:178: in main chunk
	[C]: in function 'dofile'
	.../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: in ?

**Comment by soumith** [comment]
you can add the line:

local unpack = unpack or table.unpack

**Comment by ankerbachryhl** [comment]
Where should i add it? :) @soumith

**Comment by soumith** [comment]
to your code
