### ISSUE TITLE
How to design a parallel network and input these outputs to  LSTM in series?

### ISSUE THREAD

**Issue by guoyang007** [torch/torch7#893]
just like LRCN model,every image input to a CNN and a length of these outputs reshape to a series into the LSTM, but we know ,the "parallel" of CNN layer is just a simulation,the input of 8 frames is just input to the CNN layer in series and the stack into the LSTM.

 now I need to do something different on the branches , to change the CNN to CNN+LSTM on the branches,and then stack into the last LSTMs. the model is like this:[(cnn+lstm)s+LSTM](http://ocb9txzav.bkt.clouddn.com/conv.png). because my inputs is not images but time series data,and every time step in my data is also a short  sequence in a time window. so i need to get the feature of the inner time window at every time step. 

However, in the original network,the LSTM layer just can receive the sequence of images,but how can i add the LSTM layer to get the feature of the sequence in the time window at every step?

**Comment by soumith** [comment]
Thanks a lot for filing this issue! We'll triage and take a look at it as soon as possible!
Could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking the torch7 package. We'll happily reply there. Thanks.
