### ISSUE TITLE
MSVC error C2440: 'type cast': cannot convert from 'THHalf' to 'THHalf'

### ISSUE THREAD

**Issue by BTNC** [torch/torch7#897]
Hi,

I am facing following error with latest torch compiled with vs2015:
THTensorCopy.c(7): error C2440: 'type cast': cannot convert from 'THHalf' to 'THHalf'
THTensorCopy.c(39): error C2440: 'type cast': cannot convert from 'THHalf' to 'THHalf'

I am not sure how to fix it for msvc. Any help is appreciated.

Thanks,

**Comment by gchanan** [comment]
Thanks for the report -- I don't have MSVC to test with, but hopefully I can post a patch for you to try.

**Comment by gchanan** [comment]
can you try https://github.com/gchanan/torch7/commit/c5bf47ab40c64835a828bc581892cafe522b49ba ?

**Comment by gchanan** [comment]
Created https://github.com/torch/torch7/pull/899.
