### ISSUE TITLE
/usr/share/lua/5.1/torch/init.lua:54: attempt to concatenate a nil value

### ISSUE THREAD

**Issue by archenroot** [torch/torch7#898]
while trying to run demos from [multipathnet](https://github.com/facebookresearch/multipathnet) by executing th demo.lua -img ./deepmask/data/testImage.jpg

I get error:
```
luajit: /usr/share/lua/5.1/trepl/init.lua:389: /usr/share/lua/5.1/trepl/init.lua:389: /usr/share/lua/5.1/trepl/init.lua:389: /usr/share/lua/5.1/trepl/init.lua:389: /usr/share/lua/5.1/trepl/init.lua:389: /usr/share/lua/5.1/trepl/init.lua:389: /usr/share/lua/5.1/trepl/init.lua:389: /usr/share/lua/5.1/trepl/init.lua:389: /usr/share/lua/5.1/torch/init.lua:54: attempt to concatenate a nil value
stack traceback:
	[C]: in function 'error'
	/usr/share/lua/5.1/trepl/init.lua:389: in function 'require'
	demo.lua:15: in main chunk
	[C]: in function 'dofile'
	/usr/bin/th:150: in main chunk
	[C]: at 0x004045a0
```

And it is relevant to this executed code:
```
function torch.include(package, file)
   dofile(torch.packageLuaPath(package) .. '/' .. file)
end
```

I was building most of components and it is dozen of components from git sources, so could this be an issue. In general error handling and logging looks to me still quite basic in whole torch.

with regards,

Ladislav

**Comment by soumith** [comment]
answered https://github.com/facebookresearch/multipathnet/issues/41
