### ISSUE TITLE
error in the use of nn.CAddTable and nn.ConcatTable

### ISSUE THREAD

**Issue by brisker** [torch/torch7#904]
I tried to concat two outputs of two different layers with CAddTable and ConcatTable like this:

        input=torch.Tensor(1,3,60,60):fill(1) 
        input=input:cuda()

	local conv_block_1 = nn.Sequential()
	conv_block_1:add(cudnn.SpatialConvolution(3, 16, 5, 5, 1, 1, 2, 2))  --(60+2*2-5)/1+1=60
	conv_block_1:add(cudnn.SpatialBatchNormalization(16))
	conv_block_1:add(cudnn.ReLU(true))

	local conv_block_2 = nn.Sequential()
	conv_block_2:add(cudnn.SpatialConvolution(16, 32, 5, 5, 1, 1, 2, 2)) -- (60+2*2-5)/1+1=60
	conv_block_2:add(cudnn.SpatialBatchNormalization(32))
	conv_block_2:add(cudnn.ReLU(true))

	local conv_block_3 = nn.Sequential()
	conv_block_3:add(cudnn.SpatialConvolution(32, 16, 5, 5, 1, 1, 2, 2)) -- (60+2*2-5)/1+1=60
	conv_block_3:add(cudnn.SpatialBatchNormalization(16))
	conv_block_3:add(cudnn.ReLU(true))

	local concat_block_1 = nn.ConcatTable()
	concat_block_1:add(conv_block_1)  ----
	concat_block_1:add(conv_block_3 )
	
	local add_block_1 = nn.Sequential()
	add_block_1:add(concat_block_1)
	add_block_1:add(nn.CAddTable())
	add_block_1:add(cudnn.ReLU(true))

	local model=nn.Sequential()
	model:add(conv_block_1)
	model:add(conv_block_2)
        model:add(conv_block_3)
        model:add(add_block_1)
        model:cuda()
        print(model)
        model:forward(input)
but why the code just run this error:
input has to contain 3 feature maps, but receives input of size : 1 *  16* 60 * 60？

**Comment by soumith** [comment]
Could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking the torch7 package. We'll happily reply there. Thanks.
