### ISSUE TITLE
bug when running ./update.sh 

### ISSUE THREAD

**Issue by brisker** [torch/torch7#909]
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jcc/torch/pkg/paths/build
[100%] Built target paths
cd build && make install
[100%] Built target paths
Install the project...
-- Install configuration: "Release"
-- Installing: /home/jcc/torch/install/lib/luarocks/rocks/paths/scm-1/lua/paths/init.lua
-- Installing: /home/jcc/torch/install/lib/luarocks/rocks/paths/scm-1/lib/libpaths.so
Updating manifest for /home/jcc/torch/install/lib/luarocks/rocks
paths scm-1 is now built and installed in /home/jcc/torch/install/ (license: BSD)

Warning: unmatched variable LUALIB
cmake -E make_directory build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DLUA=/home/jcc/torch/install/bin/luajit -DLUALIB= -DLUA_BINDIR="/home/jcc/torch/install/bin" -DLUA_INCDIR="/home/jcc/torch/install/include" -DLUA_LIBDIR="/home/jcc/torch/install/lib" -DLUADIR="/home/jcc/torch/install/lib/luarocks/rocks/torch/scm-1/lua" -DLIBDIR="/home/jcc/torch/install/lib/luarocks/rocks/torch/scm-1/lib" -DCMAKE_INSTALL_PREFIX="/home/jcc/torch/install/lib/luarocks/rocks/torch/scm-1" && make -j$(getconf _NPROCESSORS_ONLN)

-- Compiling with OpenMP support
-- Compiling with OpenMP support
-- Could not find hardware support for NEON on this machine.
-- No OMAP3 processor on this on this machine.
-- No OMAP4 processor on this on this machine.
-- Looking for cpuid.h
-- Looking for cpuid.h - found
CMake Error at lib/TH/CMakeLists.txt:85 (CHECK_C_SOURCE_COMPILES):
  Unknown CMake command "CHECK_C_SOURCE_COMPILES".

-- Configuring incomplete, errors occurred!
See also "/home/jcc/torch/pkg/torch/build/CMakeFiles/CMakeOutput.log".
See also "/home/jcc/torch/pkg/torch/build/CMakeFiles/CMakeError.log".

Error: Build error: Failed building.

**Comment by soumith** [comment]
this should be fixed now in distro master.
