### ISSUE TITLE
Unable to detect AVX2 in simd.h

### ISSUE THREAD

**Issue by Jokeren** [torch/torch7#916]
Hi, @rguthrie3 @soumith 

I and @pavanky found that it cannot detect AVX2 support, and I figure out two mistakes:

1. `CPUID_AVX2_BIT` should be **0x20** instead of **0x10**. (The 5th bit start from **0**). 

2. After setting c=0x0,  the `asm volatile ( "cpuid\n\t"  : "+a"(a), "=b"(b), "+c"(c), "=d"(d) );` statement works.

However, `__get_cpuid()` is still unable to show the support of `AVX2` with g++ 4.8.4.

**Comment by pavanky** [comment]
I tried this with gcc 5.4.0. Same issue.

**Comment by Jokeren** [comment]
Bug fix, https://github.com/torch/torch7/pulls

**Comment by Jokeren** [comment]
Bug fix, https://github.com/torch/torch7/pull/924
