### ISSUE TITLE
Failure during install - NVCC build problem?

### ISSUE THREAD

**Issue by ShreyasSkandan** [torch/torch7#918]
I'm currently running CUDA 8.0 + GTX 1070 + Ubuntu 14. I got through step 1 and step 2 of the install but during the actuall ./install.sh command the installer fails.

The errors start off like this

> -- got cuda version 8.0
> -- Found CUDA with FP16 support, compiling with torch.CudaHalfTensor
> -- CUDA_NVCC_FLAGS: -gencode;arch=compute_61,code=sm_61;-DCUDA_HAS_FP16=1
> -- THC_SO_VERSION: 0
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/shreyas/torch/extra/cutorch/build
> [  2%] [  2%] [  3%] [  4%] [  5%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCHalf.cu.o
> [  6%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCBlas.cu.o
> Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCReduceApplyUtils.cu.o
> Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCSleep.cu.o
> [  8%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorage.cu.o
> Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCStorageCopy.cu.o
> [  9%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensor.cu.o
> Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorCopy.cu.o
> [ 10%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMath.cu.o
> [ 11%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMath2.cu.o
> [ 12%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathBlas.cu.o
> [ 13%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathMagma.cu.o
> [ 15%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathPairwise.cu.o
> /usr/local/cuda-8.0/include/thrust/detail/reference.inl(127): error: no default constructor exists for class "thrust::detail::execute_with_allocator<THCThrustAllocator, thrust::system::cuda::detail::execute_on_stream_base>"
>           detected during:
>             instantiation of "void thrust::reference<Element, Pointer, Derived>::assign_from(OtherPointer) [with Element=signed long, Pointer=thrust::pointer<signed long, thrust::detail::execute_with_allocator<THCThrustAllocator, thrust::system::cuda::detail::execute_on_stream_base>, thrust::use_default, thrust::use_default>, Derived=thrust::use_default, OtherPointer=const signed long *]" 
> (65): here
.
.
.

And they eventually break the installer like this
> .
> .
> .
>            instantiation of "OutputIterator thrust::copy_if(const thrust::detail::execution_policy_base<DerivedPolicy> &, InputIterator1, InputIterator1, InputIterator2, OutputIterator, Predicate) [with DerivedPolicy=thrust::detail::execute_with_allocator<THCThrustAllocator, thrust::system::cuda::detail::execute_on_stream_base>, InputIterator1=thrust::counting_iterator<long, thrust::use_default, thrust::use_default, thrust::use_default>, InputIterator2=thrust::device_ptr<unsigned char>, OutputIterator=thrust::permutation_iterator<thrust::device_ptr<long>, thrust::transform_iterator<strided_range<thrust::device_ptr<long>>::stride_functor, thrust::counting_iterator<long, thrust::use_default, thrust::use_default, thrust::use_default>, thrust::use_default, thrust::use_default>>, Predicate=NonZeroOp<unsigned char>]" 
> /home/shreyas/torch/extra/cutorch/lib/THC/generic/THCTensorMath.cu(313): here
> 
> [ 16%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathReduce.cu.o
> [ 17%] Building NVCC (Device) object lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMathScan.cu.o
> 2 errors detected in the compilation of "/tmp/tmpxft_00000bb3_00000000-7_THCTensorMath.cpp1.ii".
> CMake Error at THC_generated_THCTensorMath.cu.o.cmake:267 (message):
>   Error generating file
>   /home/shreyas/torch/extra/cutorch/build/lib/THC/CMakeFiles/THC.dir//./THC_generated_THCTensorMath.cu.o
> 
> 
> make[2]: *** [lib/THC/CMakeFiles/THC.dir/./THC_generated_THCTensorMath.cu.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [lib/THC/CMakeFiles/THC.dir/all] Error 2
> make: *** [all] Error 2
> 
> Error: Build error: Failed building.

Any help/pointers would be greatly appreciated!

Thanks in advance,
Shreyas

**Comment by gchanan** [comment]
I'm looking into this.

**Comment by gchanan** [comment]
I haven't been able to reproduce with CUDA 8.0.  Out of curiosity, which gcc version are you using?

**Comment by pavanky** [comment]
@ShreyasSkandan any chance you have multiple versions of thrust on the system?

**Comment by ShreyasSkandan** [comment]
@gchanan I'm running gcc version 4.8.4. Could it be the cause of the error?

@pavanky I'm not familiar with thrust. Is there any way I can verify that I don't have multiple versions of it on my system?

Thank you for taking the time to look into this. I appreciate it.

**Comment by gchanan** [comment]
I don't think the gcc version is the error.

More likely as @pavanky suggested there are multiple thrust versions or it's an issue with thrust on Ubuntu -- it seems everyone reporting this in on Ubuntu, but maybe just everyone uses Ubuntu.

I do notice the line numbers don't seem to match up with my install (CentOs 6.8) -- for example /usr/local/cuda-8.0/include/thrust/detail/reference.inl is a blank line.

**Comment by pavanky** [comment]
@gchanan It's a blank line for me too on archlinux.

@ShreyasSkandan How did you install cuda-8.0 ?

**Comment by ShreyasSkandan** [comment]
@pavanky @gchanan Sorry for having wasted your time guys. I remembered that I was on the CUDA 8.0 beta version instead of the release version. I installed the latest CUDA 8.0 release and it works!
