### ISSUE TITLE
Topk is not working correctly in my code

### ISSUE THREAD

**Issue by gaosh** [torch/torch7#923]
I used torch.topk() function in my code, however, when it runs, it generates result greater than the boundary of the variable.
```Lua
local _,n = self.Age:topk(1,true,true)
print(n)
```
The result of n is
```
4.4237603911762e+18
```
Which is out of range with respect to self.Age.

**Comment by soumith** [comment]
could you please give a small snippet to reproduce this?

This can be user-error, if self.Age was partly not initialized.

**Comment by gaosh** [comment]
I am not sure which part of my code cause this problem. It works fine when my model running alone, this problem happens when I combine my model with models from torch and torch rnn library.

**Comment by soumith** [comment]
without any way to reproduce this, i cannot figure out whats going on.
