### ISSUE TITLE
GAN generative adversarial networks Image generation problem 

### ISSUE THREAD

**Issue by vinodkkurmi** [torch/torch7#932]
hello, I m facing problem to generate the images using the GAN model. I am refering the context encoder (https://github.com/pathak22/context-encoder) code. I am using the Alexnet network encoder and and corresponding decoder. 
1) If I am used the image (range from 0-255,byte) the image generation not working. while giving image (range [0-1]) it is working fine. 
2) For pretrained alexnet  of VGG16 , why it is necessary to give image (which has rang [0-255]) for classification task. what kind prepossessing is required   for testing an image using these  pretrained model??

**Comment by soumith** [comment]
Could you post this to our google groups here: https://groups.google.com/forum/#!forum/torch7 , we only use this github issues for bug tracking the torch7 package. We'll happily reply there. Thanks.
