### ISSUE TITLE
Multiple forward of a network(a linear layer)  in gives same output for differnt input

### ISSUE THREAD

**Issue by vinodkkurmi** [torch/torch7#935]
Hello , If I make multiple forward pass of liner layer network(2x1, given code below) . The variable store the  output of first (till 2nd last)  forward pass gives the same values as last forward pass value.
Code 
require 'torch';
require 'nn';

module = nn.Linear(2, 1)  --A linear layer
print((module.weight:sum()*(0.5)) + module.bias)  -- Value of Y=Wx+b, when x=[0.5,0.5]'
print((module.weight:sum()*1) + module.bias)    -- Value of Y=Wx+b, when x=[1,1]'
print((module.weight:sum()*(2)) + module.bias)    -- Value of Y=Wx+b, when x=[2,2]'
print((module.weight:sum()*(3)) + module.bias)     -- Value of Y=Wx+b, when x=[3,3]'

---- Input is X=[0.5,0.5]'
input1 = torch.Tensor(2):fill(0.5) 
print('input1',input1)
local out_11 = module:forward(input1)
print(' out_11', out_11)

---- Input is X=[1,1]'
input2 = torch.Tensor(2):fill(1) 
print('input2',input2)
local out_21 = module:forward(input2)
print(' out_21', out_21)

---- Input is X=[2,2]'
input3 = torch.Tensor(2):fill(2) 
print('input3',input3)
local out_31 = module:forward(input3)
print(' out_31', out_31)

---- Input is X=[3,3]'
input4 = torch.Tensor(2):fill(3) 
print('input4',input4)
local out_41 = module:forward(input4)
print(' out_41', out_41)

---Again priting the value of output--
print(' out_11', out_11)
print(' out_21', out_21)
print(' out_31', out_31)
print(' out_41', out_41)
-------------------Output------------
-0.4600  0.2376
[torch.DoubleTensor of size 1x2]

0.001 *
 8.9223
[torch.DoubleTensor of size 1]

-0.1023
[torch.DoubleTensor of size 1]

-0.2135
[torch.DoubleTensor of size 1]

-0.4359
[torch.DoubleTensor of size 1]

-0.6582
[torch.DoubleTensor of size 1]

input1	 0.5000
 0.5000
[torch.DoubleTensor of size 2]

 out_11	-0.1023
[torch.DoubleTensor of size 1]

input2	 1
 1
[torch.DoubleTensor of size 2]

 out_21	-0.2135
[torch.DoubleTensor of size 1]

input3	 2
 2
[torch.DoubleTensor of size 2]

 out_31	-0.4359
[torch.DoubleTensor of size 1]

input4	 3
 3
[torch.DoubleTensor of size 2]

 out_41	-0.6582
[torch.DoubleTensor of size 1]

 out_1	-0.6582
[torch.DoubleTensor of size 1]

 out_21	-0.6582
[torch.DoubleTensor of size 1]

 out_2	-0.6582
[torch.DoubleTensor of size 1]

 out_31	-0.6582
[torch.DoubleTensor of size 1]

 out_3	-0.6582
[torch.DoubleTensor of size 1]

 out_4	-0.6582
[torch.DoubleTensor of size 1]
-----------------------------------
Here value of  out_11,out_21,out_31 has been changed from the previous  value to value of out_41 . I am not getting the reason. Is there any overriding issue of memory or anything else??? 

How can I solve this problem???

**Comment by pavanky** [comment]
`module:forward()` returns `module.output` which changes from run to run. If you want to save previous results, you may need to clone the output.

**Comment by vinodkkurmi** [comment]
@pavanky  Thanks I got it....
