### ISSUE TITLE
Bug in tensor:csub()

### ISSUE THREAD

**Issue by lospooky** [torch/torch7#937]
Hi,
i've found the following bug on my installation, all packages updated no earlier than last week.
I'll paste a simple repro case:
```
t = torch.ones(10)
t[{{2,t:size(1)}}]:csub(t[{{1,t:size(1)-1}}])
```
the output I get is 1010101010  instead of the correct 1000000000.
The problem only occurs with CPU tensors (tested it with Double, Float, and Byte); CudaTensors are fine.
Also, using add,  `t[{{2,t:size(1)}}]:add(-t[{{1,t:size(1)-1}}])` produces the correct result.

Any suggestions on where to start looking to fix it? Wouldn't mind doing the PR myself.

**Comment by soumith** [comment]
giving the same tensor for both LHS and RHS is not allowed in csub (or in most operations). This is expected behavior.
To get the correct result, you can do:

```
t = torch.ones(10)
t2 = t[{{1,t:size(1)-1}}]:clone()
t[{{2,t:size(1)}}]:csub(t2)
```
