### ISSUE TITLE
th command not working after clean install on ubuntu 16

### ISSUE THREAD

**Issue by saurabhvyas** [torch/torch7#945]
Neither luajit nor lua found in path on ubuntu after clean install
this is when I ran ./test.sh

I followed official instructions as indicated on the website

**Comment by rcplane** [comment]
Had a brief discussion with the user, at the least luarocks package was missing from install-deps

**Comment by soumith** [comment]
we install our own luarocks.
Before running ./test.sh, one has to run:
. ~/torch/install/bin/torch-activate

**Comment by saurabhvyas** [comment]
so I have manually added lua to my environment path , and it is accessible now from terminal but I cant seem to install luarocks by following instructions from https://luarocks.org/#quick-start

The screenshot shows torch install success after removing torch directory and trying again 

![image](https://cloud.githubusercontent.com/assets/6899784/23299582/0b4d6318-faa8-11e6-8711-78b9d14bd419.png)

**Comment by albanD** [comment]
Since torch is doing a local install, it has to be added to your path to work. To do so, run `~/torch/install/bin/torch-activate` (and add it to your bashrc).

**Comment by saurabhvyas** [comment]
I tried that , I am getting this error
saurabhorange@orangepc:~/torch$ ~/torch/install/bin/torch-activate
bash: /home/saurabhorange/torch/install/bin/torch-activate: No such file or directory

**Comment by albanD** [comment]
You did run `./install.sh` after running `bash install-deps` right?  (see [full innstructions here](http://torch.ch/docs/getting-started.html#_))

**Comment by saurabhvyas** [comment]
Yes I did , I copied those 3 lines of code line by line

**Comment by albanD** [comment]
the `./install.sh` command should have created a `install` folder in `~/torch` and you should find both `th` and `luearocks` in the `bin` folder at `~/torch/install/bin`

**Comment by saurabhvyas** [comment]
unfortunately it didnt create an install folder , thats the main problem , I have tried reinstalling it multiple times , here is how folder looks 
![image](https://cloud.githubusercontent.com/assets/6899784/23330374/414011a8-fb72-11e6-8817-6c725e3cff38.png)

**Comment by albanD** [comment]
What happens when you open this folder in a terminal and run `./install.sh` ?

**Comment by saurabhvyas** [comment]
I opened the folder in this terminal and tried running install.sh , and I saw some new commands executing ( one I didnt observe before when I copy pasted those 3 installanation commands into terminal from official docs ) and it failed because of connection timeout error of github rep  ( something related to xlua) , then I ran ./clean.sh and reran ./install.sh , This time it went all green and even asked me if I wanted to add path in bashrc file , I typed yes and restarted and it works!
Thanks for the help everyone :)

**Comment by wgallo3** [comment]
same problem, sad that nobody found a solution here.............

**Comment by stevankojic** [comment]
@wgallo3
Adding `/Users/USERNAME/torch/install/bin` to PATH after Torch installation worked for me so maybe you can try:

1. Check your current PATH in terminal:
`echo $PATH`
2.  If there is no 'torch path' then you need to add it to your .bash_profile (or other shell initialization file you are using) : 
`nano ~/.bash_profile`
3. Add this to .bash_profile (replacing USERNAME with your user name):
```
#Adding Torch directory to PATH
export PATH="/Users/USERNAME/torch/install/bin:$PATH”
```
4. Press CTRL-X for exit, then Y for saving, then RETURN to confirm.
5. Restart terminal
6. Check your PATH again:
`echo $PATH`

If everything went ok you should be able to start: torch-activate, th, luajit, luarocks from terminal.

Note: .bash_profile will run only on login shells. For non-login shells, you would need to create/edit a .bashrc

**Comment by duhaime** [comment]
When I installed Torch, it added to `.bashrc`:

```
. /home/localadmin/torch/install/bin/torch-activate
```

Running this command in bash (or running `source ~/.bashrc`) gives me access to `th` again.

The terminal that you used when you installed Torch should contain a similar line, and sourcing the given config file should give you access to the `th` command again. Some possible relevant config files:

```
# On Linux with bash
source ~/.bashrc
# On Linux with zsh
source ~/.zshrc
# On OSX or in Linux with none of the above.
source ~/.profile
```
