### ISSUE TITLE
Torch installation fails

### ISSUE THREAD

**Issue by gxarmanis** [torch/torch7#954]
I would like your help regarding the installation of Torch7 on Ubuntu 16.04.
I followed exactly the commands for its installation and after minutes of computing procedures i come up with that:

Generating OpenBLASConfig.cmake in /opt/OpenBLAS/lib/cmake/openblas
Generating OpenBLASConfigVersion.cmake in /opt/OpenBLAS/lib/cmake/openblas
Install OK!
make[1]: Leaving directory '/tmp/OpenBLAS'
==> Torch7's dependencies have been installed

So i tried to source (as stated) the path with:
 
labadmin@ENT01WS605:~/torch$ source ~/.bashrc
Since i saw nothing to happen ...well i supposed the work is done so i moved with the next command "luarocks install image"
BUT i get the error below:

Error: Your user does not have write permissions in /usr/local
-- you may want to run as a privileged user or use your local tree with --local.

So i thought of giving a try on running the /th command to start Torch but

labadmin@ENT01WS605:~/torch$ th
th: command not found

I have searched over topics here, others were dealing with that issue (without getting a reply), also i Googled for these and i read tons of different solutions that didnt helped me.

Can please someone help me with that?

Thank you!

**Comment by pavanky** [comment]
I looks like you ran `install-deps.sh`. But did you run `install.sh` after that?

**Comment by gxarmanis** [comment]
Thank you for replying back! 
I run the commands below (as there displayed on Torch's website: http://torch.ch/docs/getting-started.html#_) 

# in a terminal, run the commands WITHOUT sudo
git clone https://github.com/torch/distro.git ~/torch --recursive
cd ~/torch; bash install-deps;
./install.sh

So i suppose the install.sh command run successfully...

**Comment by pavanky** [comment]
Just asked the obvious question because the messages you posted only showed the dependencies being installed.

**Comment by gxarmanis** [comment]
No worries ...you are right but i thought that it would be better not to post the entire calculations...

How should i proceed now?

**Comment by gxarmanis** [comment]
I tried to reinstall again torch and for some strange reason now it works (run again the same commands).
Thank you for your time! 
I will close the issue for now...

**Comment by Evgsurf** [comment]
Hello guys.
I had the same problem 
I use Ubuntu 16.04 LTS 64 bit
I installed it several times, no luck.

The solution is "Read manual http://torch.ch/docs/getting-started.html#_  and run command source ~/.bashrc" 
I hope it will spend time for somebody
