### ISSUE TITLE
luajit: evaluate-rva.lua:56: attempt to index global 'model' (a nil value)

### ISSUE THREAD

**Issue by ruizhaogit** [torch/torch7#967]
Hi guys,

I try to evaluate the trained RAM model on Mnist using script "evaluate-rva.lua", but get this error: luajit: evaluate-rva.lua:56: attempt to index global 'model' (a nil value).

Does anyone know why?

Thank you!
Rui

**Comment by ksharsha** [comment]
It looks like you are trying to access the model before actually creating it or loading it.

**Comment by ruizhaogit** [comment]
I change this line "model = xp:model().module" to "model = xp:model()". Then it worked :)
