### ISSUE TITLE
torch.prod(...) wrongly returns NaN on GPU

### ISSUE THREAD

**Issue by vadimkantorov** [torch/torch7#975]
```
th> torch.prod(torch.CudaTensor{0})
nan

th> torch.prod(torch.Tensor{0})
0
```

discovered by @NTheo

**Comment by NTheo** [comment]
Thanks for the ping Vadim, but I think it's been fixed by someone else here
https://github.com/torch/cutorch/commit/9e91bf9a9a84948acc7b2954c455846359775d82
