### ISSUE TITLE
Update on qtwebkit dependency for Arch Linux

### ISSUE THREAD

**Issue by politeles** [torch/torch7#977]
Hi,
I'm working on Arch Linux. Apparently the support for qtwebkit was removed from the official repos.
See: <https://bbs.archlinux.org/viewtopic.php?id=223045>
I found there that the new package qt5-webkit-ng is compatible with the previous one.

The only modification needed is on file install-deps, line 271:

```bash
ipython qt4 qt5-webkit-ng || exit 1

```

I've compiled it and it's working.

Regards,
José Enrique

**Comment by pavanky** [comment]
@politeles send a PR to torch-distro ?

**Comment by politeles** [comment]
@pavanky done in https://github.com/torch/distro/pull/214
Thanks

**Comment by soumith** [comment]
thanks @politeles
